/* ══════════════════════════════════════════════════
   Bolee — Seed Vocabulary
   ──────────────────────────────────────────────────
   Theth (ਠੇਠ) Punjabi: the rural, unmixed register.
   Deliberately weighted away from Hindi-Urdu loanwords
   that already survive fine in urban speech.

   Schema per word:
     id        stable slug, `${category}-${nnn}`
     gurmukhi  the word in Gurmukhi script
     latin     romanisation (readable, not strict ISO)
     pos       noun | verb | adj | adv | pron | interj
     meaning   English gloss
     category  one of VOCAB_CATEGORIES
     example   { gurmukhi, latin } — a natural sentence
     tier      1 kids · 2 general · 3 advanced
     dialect   majhi | malwai | doabi | puadhi | common
     emoji     kids-mode visual cue / tap-answer choice
     status    seed data ships pre-verified
     source    'seed' — contributed words carry a user id
   ══════════════════════════════════════════════════ */

(function (global) {
  'use strict';

  var CATEGORIES = [
    { id: 'home',    gurmukhi: 'ਘਰ',     label: 'Home',     emoji: '🏠' },
    { id: 'farm',    gurmukhi: 'ਖੇਤੀ',    label: 'Farm',     emoji: '🌾' },
    { id: 'nature',  gurmukhi: 'ਕੁਦਰਤ',  label: 'Nature',   emoji: '🌳' },
    { id: 'body',    gurmukhi: 'ਸਰੀਰ',   label: 'Body',     emoji: '🫀' },
    { id: 'food',    gurmukhi: 'ਖਾਣਾ',   label: 'Food',     emoji: '🍲' },
    { id: 'kinship', gurmukhi: 'ਰਿਸ਼ਤੇ',  label: 'Kinship',  emoji: '👪' },
    { id: 'emotion', gurmukhi: 'ਭਾਵਨਾ',  label: 'Emotion',  emoji: '💛' },
    { id: 'time',    gurmukhi: 'ਸਮਾਂ',    label: 'Time',     emoji: '🕰️' }
  ];

  var DIALECTS = [
    { id: 'common', label: 'Common' },
    { id: 'majhi',  label: 'Majhi' },
    { id: 'malwai', label: 'Malwai' },
    { id: 'doabi',  label: 'Doabi' },
    { id: 'puadhi', label: 'Puadhi' }
  ];

  var TIERS = [
    { id: 1, label: 'Everyday',  hint: 'first words, good for children' },
    { id: 2, label: 'Village',   hint: 'common rural vocabulary' },
    { id: 3, label: 'Deep theth', hint: 'older words, fading from use' }
  ];

  /* Compact tuple form keeps this file readable and roughly a third
     the size of 200+ object literals. Expanded into full records below. */
  // [gurmukhi, latin, pos, meaning, tier, dialect, emoji, exGurmukhi, exLatin]
  var RAW = {

    /* ── ਘਰ · HOME ─────────────────────────────────── */
    home: [
      ['ਘਰ', 'ghar', 'noun', 'house, home', 1, 'common', '🏠',
       'ਸਾਡਾ ਘਰ ਪਿੰਡ ਦੇ ਸਿਰੇ ਤੇ ਹੈ।', 'saada ghar pind de sire te hai.'],
      ['ਚੁੱਲ੍ਹਾ', 'chulha', 'noun', 'traditional mud stove', 2, 'common', '🔥',
       'ਬੇਬੇ ਚੁੱਲ੍ਹੇ ਤੇ ਰੋਟੀ ਲਾਹ ਰਹੀ ਹੈ।', 'bebe chulhe te roti laah rahi hai.'],
      ['ਵਿਹੜਾ', 'vehrha', 'noun', 'courtyard', 2, 'common', '🏡',
       'ਵਿਹੜੇ ਵਿੱਚ ਮੰਜੇ ਡਾਹੇ ਪਏ ਨੇ।', 'vehrhe vich manje daahe pae ne.'],
      ['ਮੰਜਾ', 'manja', 'noun', 'woven string cot', 1, 'common', '🛏️',
       'ਬਾਪੂ ਮੰਜੇ ਤੇ ਪਿਆ ਹੈ।', 'baapu manje te piaa hai.'],
      ['ਪੀੜ੍ਹੀ', 'peerhi', 'noun', 'low woven stool', 2, 'common', '🪑',
       'ਪੀੜ੍ਹੀ ਤੇ ਬਹਿ ਜਾ।', 'peerhi te beh ja.'],
      ['ਬੂਹਾ', 'booha', 'noun', 'door', 1, 'common', '🚪',
       'ਬੂਹਾ ਭੇੜ ਦੇ।', 'booha bherh de.'],
      ['ਛੱਤ', 'chhat', 'noun', 'roof, terrace', 1, 'common', '🏘️',
       'ਗਰਮੀਆਂ ਵਿੱਚ ਅਸੀਂ ਛੱਤ ਤੇ ਸੌਂਦੇ ਹਾਂ।', 'garmiaan vich aseen chhat te saunde haan.'],
      ['ਕੰਧ', 'kandh', 'noun', 'wall', 1, 'common', '🧱',
       'ਕੰਧ ਉੱਤੇ ਬਿੱਲੀ ਬੈਠੀ ਹੈ।', 'kandh utte billi baithi hai.'],
      ['ਸਬਾਤ', 'sabaat', 'noun', 'inner room of a village house', 3, 'malwai', '🛋️',
       'ਸਬਾਤ ਵਿੱਚ ਦਾਣੇ ਪਏ ਨੇ।', 'sabaat vich daane pae ne.'],
      ['ਤੰਦੂਰ', 'tandoor', 'noun', 'clay oven', 2, 'common', '🍞',
       'ਪਿੰਡ ਦੇ ਸਾਂਝੇ ਤੰਦੂਰ ਤੇ ਰੋਟੀਆਂ ਲੱਗਦੀਆਂ ਨੇ।', 'pind de saanjhe tandoor te rotiaan laggdiaan ne.'],
      ['ਬਾਲਟੀ', 'baalti', 'noun', 'bucket', 1, 'common', '🪣',
       'ਬਾਲਟੀ ਭਰ ਕੇ ਲਿਆ।', 'baalti bhar ke liaa.'],
      ['ਘੜਾ', 'gharha', 'noun', 'earthen water pot', 2, 'common', '🏺',
       'ਘੜੇ ਦਾ ਪਾਣੀ ਠੰਢਾ ਹੁੰਦਾ ਹੈ।', 'gharhe da paani thandha hunda hai.'],
      ['ਝਾੜੂ', 'jhaarhu', 'noun', 'broom', 1, 'common', '🧹',
       'ਵਿਹੜੇ ਨੂੰ ਝਾੜੂ ਮਾਰ ਦੇ।', 'vehrhe nu jhaarhu maar de.'],
      ['ਚਾਦਰ', 'chaadar', 'noun', 'bedsheet', 1, 'common', '🧺',
       'ਮੰਜੇ ਤੇ ਸਾਫ਼ ਚਾਦਰ ਵਿਛਾ ਦੇ।', 'manje te saaf chaadar vichhaa de.'],
      ['ਰਜਾਈ', 'rajaai', 'noun', 'thick cotton quilt', 1, 'common', '🛌',
       'ਸਿਆਲ਼ ਵਿੱਚ ਰਜਾਈ ਬਿਨਾਂ ਨਹੀਂ ਸਰਦਾ।', 'siaal vich rajaai binaan naheen sarda.'],
      ['ਸੰਦੂਕ', 'sandook', 'noun', 'wooden storage trunk', 2, 'common', '🧳',
       'ਦਾਦੀ ਦੇ ਸੰਦੂਕ ਵਿੱਚ ਪੁਰਾਣੀਆਂ ਚੀਜ਼ਾਂ ਨੇ।', 'daadi de sandook vich puraaniaan cheezaan ne.'],
      ['ਚੌਂਕਾ', 'chaunka', 'noun', 'cooking area of the house', 3, 'common', '🧑‍🍳',
       'ਚੌਂਕੇ ਵਿੱਚ ਪੈਰ ਧੋ ਕੇ ਵੜੀਦਾ ਸੀ।', 'chaunke vich pair dho ke varheeda si.'],
      ['ਖੂੰਜਾ', 'khoonja', 'noun', 'corner', 2, 'common', '📐',
       'ਖੂੰਜੇ ਵਿੱਚ ਸੋਟੀ ਪਈ ਹੈ।', 'khoonje vich soti paee hai.'],
      ['ਬਨੇਰਾ', 'banera', 'noun', 'parapet on a roof', 3, 'majhi', '🏚️',
       'ਬਨੇਰੇ ਤੇ ਕਾਂ ਬੋਲਦਾ ਹੈ।', 'banere te kaan bolda hai.'],
      ['ਦਲਾਨ', 'dalaan', 'noun', 'covered verandah', 3, 'doabi', '🏛️',
       'ਦਲਾਨ ਵਿੱਚ ਛਾਂ ਹੈ।', 'dalaan vich chhaan hai.'],
      ['ਪਰਾਤ', 'paraat', 'noun', 'wide flat dough-kneading dish', 2, 'common', '🥣',
       'ਪਰਾਤ ਵਿੱਚ ਆਟਾ ਗੁੰਨ੍ਹ ਲੈ।', 'paraat vich aata gunnh lai.'],
      ['ਚਿਮਟਾ', 'chimta', 'noun', 'flat tongs', 2, 'common', '🥢',
       'ਚਿਮਟੇ ਨਾਲ ਰੋਟੀ ਫੜ।', 'chimte naal roti pharh.'],
      ['ਤਵਾ', 'tava', 'noun', 'flat iron griddle', 1, 'common', '🍳',
       'ਤਵਾ ਗਰਮ ਹੋ ਗਿਆ।', 'tava garam ho giaa.'],
      ['ਪੌੜੀ', 'paurhi', 'noun', 'ladder, stairs', 1, 'common', '🪜',
       'ਪੌੜੀ ਲਾ ਕੇ ਛੱਤ ਤੇ ਚੜ੍ਹ।', 'paurhi laa ke chhat te charrh.'],
      ['ਜਿੰਦਰਾ', 'jindra', 'noun', 'padlock', 2, 'common', '🔒',
       'ਬੂਹੇ ਨੂੰ ਜਿੰਦਰਾ ਮਾਰ ਦੇ।', 'boohe nu jindra maar de.'],
      ['ਖੂਹ', 'khooh', 'noun', 'well', 2, 'common', '🕳️',
       'ਖੂਹ ਵਿੱਚੋਂ ਪਾਣੀ ਕੱਢ।', 'khooh vichon paani kaddh.'],
      ['ਢਾਰਾ', 'dhaara', 'noun', 'thatched shelter', 3, 'malwai', '🛖',
       'ਖੇਤ ਵਿੱਚ ਢਾਰਾ ਪਾਇਆ ਹੋਇਆ ਹੈ।', 'khet vich dhaara paaiaa hoiaa hai.'],
      ['ਛੱਜ', 'chhajj', 'noun', 'winnowing basket', 3, 'common', '🧺',
       'ਛੱਜ ਨਾਲ ਦਾਣੇ ਛੱਟ ਲੈ।', 'chhajj naal daane chhatt lai.'],
      ['ਚੱਕੀ', 'chakki', 'noun', 'hand grinding mill', 3, 'common', '⚙️',
       'ਬੇਬੇ ਚੱਕੀ ਪੀਹ ਰਹੀ ਸੀ।', 'bebe chakki peeh rahi si.'],
      ['ਦੀਵਾ', 'deeva', 'noun', 'oil lamp', 2, 'common', '🪔',
       'ਸ਼ਾਮ ਨੂੰ ਦੀਵਾ ਬਾਲ਼ ਦੇ।', 'shaam nu deeva baal de.'],
      ['ਕੁੰਡਾ', 'kunda', 'noun', 'door latch', 2, 'common', '🔗',
       'ਬੂਹੇ ਦਾ ਕੁੰਡਾ ਲਾ ਦੇ।', 'boohe da kunda laa de.'],
      ['ਟੋਕਰੀ', 'tokri', 'noun', 'basket', 1, 'common', '🧳',
       'ਟੋਕਰੀ ਵਿੱਚ ਸਬਜ਼ੀ ਪਾ ਦੇ।', 'tokri vich sabzi paa de.'],
      ['ਗਲੀ', 'gali', 'noun', 'lane, street', 1, 'common', '🛣️',
       'ਸਾਡੀ ਗਲੀ ਤੰਗ ਹੈ।', 'saadi gali tang hai.'],
      ['ਸੱਥ', 'sath', 'noun', 'village meeting place', 3, 'malwai', '🗣️',
       'ਬਜ਼ੁਰਗ ਸੱਥ ਵਿੱਚ ਬੈਠੇ ਗੱਲਾਂ ਕਰਦੇ ਨੇ।', 'bazurag sath vich baithe gallaan karde ne.'],
      ['ਪਿੰਡ', 'pind', 'noun', 'village', 1, 'common', '🏞️',
       'ਸਾਡਾ ਪਿੰਡ ਨਹਿਰ ਕੰਢੇ ਹੈ।', 'saada pind nehar kandhe hai.'],
      ['ਚੁਬਾਰਾ', 'chubaara', 'noun', 'upper-storey room', 3, 'doabi', '🏢',
       'ਚੁਬਾਰੇ ਵਿੱਚ ਹਵਾ ਆਉਂਦੀ ਹੈ।', 'chubaare vich hava aaundi hai.'],
      ['ਨਲ਼ਕਾ', 'nalka', 'noun', 'hand pump', 2, 'common', '🚰',
       'ਨਲ਼ਕੇ ਤੋਂ ਪਾਣੀ ਭਰ ਲੈ।', 'nalke ton paani bhar lai.'],
      ['ਗੱਡਾ', 'gadda', 'noun', 'bullock cart', 3, 'malwai', '🛺',
       'ਗੱਡੇ ਉੱਤੇ ਤੂੜੀ ਲੱਦੀ ਹੋਈ ਹੈ।', 'gadde utte toorhi laddi hoee hai.'],
      ['ਖੁਰਪਾ', 'khurpa', 'noun', 'small weeding blade', 3, 'common', '🔧',
       'ਖੁਰਪੇ ਨਾਲ ਘਾਹ ਪੁੱਟ।', 'khurpe naal ghaah putt.'],
      ['ਰੱਸੀ', 'rassi', 'noun', 'rope', 1, 'common', '🪢',
       'ਰੱਸੀ ਨਾਲ ਬੰਨ੍ਹ ਦੇ।', 'rassi naal bannh de.'],
      ['ਸੋਟੀ', 'soti', 'noun', 'stick, staff', 1, 'common', '🥢',
       'ਬਾਬਾ ਸੋਟੀ ਲੈ ਕੇ ਤੁਰਦਾ ਹੈ।', 'baaba soti lai ke turda hai.'],
      ['ਪੱਖਾ', 'pakkha', 'noun', 'fan', 1, 'common', '💨',
       'ਪੱਖਾ ਚਲਾ ਦੇ।', 'pakkha chalaa de.'],
      ['ਪਟੜਾ', 'patrha', 'noun', 'low wooden plank seat', 3, 'malwai', '🪑',
       'ਪਟੜੇ ਤੇ ਬਹਿ ਕੇ ਰੋਟੀ ਖਾ।', 'patrhe te beh ke roti khaa.'],
      ['ਭੜੋਲਾ', 'bharhola', 'noun', 'large mud grain store', 3, 'malwai', '🛢️',
       'ਭੜੋਲੇ ਵਿੱਚ ਕਣਕ ਪਾਈ ਹੋਈ ਹੈ।', 'bharhole vich kanak paaee hoee hai.'],
      ['ਦਰਵਾਜ਼ਾ', 'darvaaza', 'noun', 'gateway, main door', 1, 'common', '🚧',
       'ਦਰਵਾਜ਼ੇ ਅੱਗੇ ਖੜ੍ਹਾ ਹੈ।', 'darvaaze agge kharrha hai.']
    ],

    /* ── ਖੇਤੀ · FARM ───────────────────────────────── */
    farm: [
      ['ਖੇਤ', 'khet', 'noun', 'field', 1, 'common', '🌾',
       'ਬਾਪੂ ਖੇਤ ਗਿਆ ਹੋਇਆ ਹੈ।', 'baapu khet giaa hoiaa hai.'],
      ['ਹਾਲੀ', 'haali', 'noun', 'ploughman', 3, 'malwai', '🧑‍🌾',
       'ਹਾਲੀ ਸਵੇਰੇ ਹੀ ਖੇਤ ਵੜ ਗਿਆ।', 'haali savere hi khet varh giaa.'],
      ['ਖੁਰਲੀ', 'khurli', 'noun', 'feeding trough for cattle', 2, 'malwai', '🪣',
       'ਮੱਝਾਂ ਖੁਰਲੀ ਤੇ ਖੜ੍ਹੀਆਂ ਨੇ।', 'majjhaan khurli te kharrhiaan ne.'],
      ['ਪੱਠੇ', 'patthe', 'noun', 'green fodder', 2, 'common', '🌿',
       'ਡੰਗਰਾਂ ਲਈ ਪੱਠੇ ਵੱਢ ਲਿਆ।', 'dangraan laee patthe vaddh liaa.'],
      ['ਡੰਗਰ', 'dangar', 'noun', 'livestock, cattle', 2, 'common', '🐐',
       'ਡੰਗਰ ਚਾਰਨ ਲੈ ਗਿਆ।', 'dangar chaaran lai giaa.'],
      ['ਮੱਝ', 'majjh', 'noun', 'water buffalo', 1, 'common', '🐃',
       'ਮੱਝ ਦਾ ਦੁੱਧ ਗਾੜ੍ਹਾ ਹੁੰਦਾ ਹੈ।', 'majjh da duddh gaarrha hunda hai.'],
      ['ਗਾਂ', 'gaan', 'noun', 'cow', 1, 'common', '🐄',
       'ਗਾਂ ਵਾੜੇ ਵਿੱਚ ਬੰਨ੍ਹੀ ਹੈ।', 'gaan vaarhe vich bannhi hai.'],
      ['ਬਲਦ', 'balad', 'noun', 'ox, bullock', 2, 'common', '🐂',
       'ਬਲਦਾਂ ਨਾਲ ਹਲ਼ ਵਾਹੁੰਦੇ ਸੀ।', 'baladaan naal hal vaahunde si.'],
      ['ਹਲ਼', 'hal', 'noun', 'plough', 2, 'common', '⚒️',
       'ਹਲ਼ ਵਾਹ ਕੇ ਜ਼ਮੀਨ ਤਿਆਰ ਕੀਤੀ।', 'hal vaah ke zameen tiaar keeti.'],
      ['ਵਾੜਾ', 'vaarha', 'noun', 'cattle enclosure', 2, 'malwai', '🚧',
       'ਵਾੜੇ ਵਿੱਚ ਡੰਗਰ ਬੰਨ੍ਹੇ ਨੇ।', 'vaarhe vich dangar bannhe ne.'],
      ['ਫ਼ਸਲ', 'fasal', 'noun', 'crop', 1, 'common', '🌽',
       'ਇਸ ਵਾਰ ਫ਼ਸਲ ਚੰਗੀ ਹੋਈ।', 'is vaar fasal changi hoee.'],
      ['ਕਣਕ', 'kanak', 'noun', 'wheat', 1, 'common', '🍞',
       'ਕਣਕ ਪੱਕ ਗਈ ਹੈ।', 'kanak pakk gaee hai.'],
      ['ਝੋਨਾ', 'jhona', 'noun', 'paddy, rice crop', 2, 'common', '🍚',
       'ਝੋਨਾ ਲਾਉਣ ਦਾ ਵੇਲ਼ਾ ਆ ਗਿਆ।', 'jhona laaun da vela aa giaa.'],
      ['ਸਰ੍ਹੋਂ', 'sarhon', 'noun', 'mustard', 2, 'common', '🌼',
       'ਸਰ੍ਹੋਂ ਦੇ ਫੁੱਲ ਖਿੜੇ ਨੇ।', 'sarhon de phull khirhe ne.'],
      ['ਕਮਾਦ', 'kamaad', 'noun', 'sugarcane crop', 3, 'malwai', '🎋',
       'ਕਮਾਦ ਪੀੜਨ ਲਈ ਭੇਜਿਆ।', 'kamaad peerhan laee bhejiaa.'],
      ['ਦਾਤੀ', 'daati', 'noun', 'sickle', 2, 'common', '🔪',
       'ਦਾਤੀ ਨਾਲ ਪੱਠੇ ਵੱਢੇ।', 'daati naal patthe vaddhe.'],
      ['ਕਹੀ', 'kahi', 'noun', 'spade, hoe', 2, 'common', '⛏️',
       'ਕਹੀ ਨਾਲ ਖਾਲ਼ ਬਣਾ।', 'kahi naal khaal banaa.'],
      ['ਖਾਲ਼', 'khaal', 'noun', 'irrigation channel', 3, 'malwai', '💧',
       'ਖਾਲ਼ ਵਿੱਚ ਪਾਣੀ ਵਗ ਰਿਹਾ ਹੈ।', 'khaal vich paani vag rihaa hai.'],
      ['ਟਿੰਡ', 'tind', 'noun', 'pot on a Persian wheel', 3, 'common', '🏺',
       'ਖੂਹ ਦੀਆਂ ਟਿੰਡਾਂ ਘੁੰਮਦੀਆਂ ਸਨ।', 'khooh diaan tindaan ghummdiaan san.'],
      ['ਪਿੜ', 'pirh', 'noun', 'threshing floor', 3, 'malwai', '🏟️',
       'ਪਿੜ ਵਿੱਚ ਕਣਕ ਗਾਹੀ ਜਾਂਦੀ ਸੀ।', 'pirh vich kanak gaahi jaandi si.'],
      ['ਤੂੜੀ', 'toorhi', 'noun', 'chopped straw fodder', 2, 'common', '🧺',
       'ਤੂੜੀ ਵਾਲਾ ਕੁੱਪ ਲਾ ਦਿੱਤਾ।', 'toorhi vaala kupp laa dittaa.'],
      ['ਕੁੱਪ', 'kupp', 'noun', 'conical straw stack', 3, 'malwai', '🗻',
       'ਪਿੰਡ ਦੇ ਬਾਹਰ ਕੁੱਪ ਖੜ੍ਹੇ ਨੇ।', 'pind de baahar kupp kharrhe ne.'],
      ['ਬੀਜ', 'beej', 'noun', 'seed', 1, 'common', '🌱',
       'ਚੰਗਾ ਬੀਜ ਪਾਓ।', 'changa beej pao.'],
      ['ਗੋਹਾ', 'goha', 'noun', 'cow dung', 2, 'common', '💩',
       'ਗੋਹੇ ਦੀਆਂ ਪਾਥੀਆਂ ਪੱਥ ਲਈਆਂ।', 'gohe diaan paathiaan patth laeeaan.'],
      ['ਪਾਥੀ', 'paathi', 'noun', 'dried dung cake used as fuel', 3, 'common', '🟤',
       'ਪਾਥੀਆਂ ਨਾਲ ਚੁੱਲ੍ਹਾ ਬਲ਼ਦਾ ਹੈ।', 'paathiaan naal chulha balda hai.'],
      ['ਟਰੈਕਟਰ', 'traictar', 'noun', 'tractor', 1, 'common', '🚜',
       'ਟਰੈਕਟਰ ਖੇਤ ਵਾਹ ਰਿਹਾ ਹੈ।', 'traictar khet vaah rihaa hai.'],
      ['ਵੱਟ', 'vatt', 'noun', 'raised field boundary', 2, 'common', '🛤️',
       'ਵੱਟ ਤੇ ਤੁਰ ਕੇ ਜਾਹ।', 'vatt te tur ke jaah.'],
      ['ਬੱਕਰੀ', 'bakri', 'noun', 'goat', 1, 'common', '🐑',
       'ਬੱਕਰੀ ਘਾਹ ਚਰ ਰਹੀ ਹੈ।', 'bakri ghaah char rahi hai.'],
      ['ਕੁੱਤਾ', 'kutta', 'noun', 'dog', 1, 'common', '🐕',
       'ਕੁੱਤਾ ਰਾਤ ਭਰ ਭੌਂਕਦਾ ਰਿਹਾ।', 'kutta raat bhar bhaunkda rihaa.'],
      ['ਕੱਟੀ', 'katti', 'noun', 'female buffalo calf', 3, 'malwai', '🐮',
       'ਕੱਟੀ ਨੂੰ ਦੁੱਧ ਪਿਆ ਦੇ।', 'katti nu duddh piaa de.'],
      ['ਵੱਛਾ', 'vachha', 'noun', 'calf', 2, 'common', '🐂',
       'ਵੱਛਾ ਮਾਂ ਮਗਰ ਭੱਜਦਾ ਹੈ।', 'vachha maan magar bhajjda hai.'],
      ['ਚਾਰਾ', 'chaara', 'noun', 'fodder', 2, 'common', '🌱',
       'ਡੰਗਰਾਂ ਨੂੰ ਚਾਰਾ ਪਾ ਦੇ।', 'dangraan nu chaara paa de.'],
      ['ਟੋਕਾ', 'toka', 'noun', 'fodder-chopping machine', 3, 'malwai', '🪚',
       'ਟੋਕੇ ਨਾਲ ਪੱਠੇ ਕੁਤਰ ਲੈ।', 'toke naal patthe kutar lai.'],
      ['ਮੋਟਰ', 'motar', 'noun', 'tubewell motor', 2, 'common', '🔌',
       'ਮੋਟਰ ਚਲਾ ਕੇ ਖੇਤ ਨੂੰ ਪਾਣੀ ਲਾ।', 'motar chalaa ke khet nu paani laa.'],
      ['ਨਹਿਰ', 'nehar', 'noun', 'canal', 2, 'common', '🚤',
       'ਨਹਿਰ ਵਿੱਚ ਪਾਣੀ ਪੂਰਾ ਹੈ।', 'nehar vich paani poora hai.'],
      ['ਵਾਢੀ', 'vaadhi', 'noun', 'harvest, reaping', 2, 'common', '🌾',
       'ਕਣਕ ਦੀ ਵਾਢੀ ਸ਼ੁਰੂ ਹੋ ਗਈ।', 'kanak di vaadhi shuroo ho gaee.'],
      ['ਬਿਜਾਈ', 'bijaaee', 'noun', 'sowing', 2, 'common', '🌰',
       'ਬਿਜਾਈ ਦਾ ਵੇਲ਼ਾ ਆ ਗਿਆ।', 'bijaaee da vela aa giaa.'],
      ['ਗਾਹੁਣਾ', 'gaahuna', 'verb', 'to thresh', 3, 'malwai', '🌀',
       'ਪਹਿਲਾਂ ਬਲਦਾਂ ਨਾਲ ਕਣਕ ਗਾਹੁੰਦੇ ਸੀ।', 'pehlaan baladaan naal kanak gaahunde si.'],
      ['ਛੱਟਣਾ', 'chhattna', 'verb', 'to winnow', 3, 'common', '💨',
       'ਦਾਣੇ ਛੱਟ ਕੇ ਸਾਫ਼ ਕਰ।', 'daane chhatt ke saaf kar.'],
      ['ਅੰਬ', 'amb', 'noun', 'mango', 1, 'common', '🥭',
       'ਅੰਬਾਂ ਦਾ ਬਾਗ਼ ਹੈ।', 'ambaan da baagh hai.'],
      ['ਬਾਗ਼', 'baagh', 'noun', 'orchard, garden', 1, 'common', '🌷',
       'ਬਾਗ਼ ਵਿੱਚ ਬੂਟੇ ਲਾਏ ਨੇ।', 'baagh vich boote laae ne.'],
      ['ਕਪਾਹ', 'kapaah', 'noun', 'cotton', 2, 'malwai', '☁️',
       'ਕਪਾਹ ਚੁਗਣ ਜਾਣਾ ਹੈ।', 'kapaah chugan jaana hai.'],
      ['ਜ਼ਮੀਨ', 'zameen', 'noun', 'land', 1, 'common', '🟫',
       'ਜ਼ਮੀਨ ਵੰਡੀ ਗਈ।', 'zameen vandi gaee.'],
      ['ਕਿੱਲਾ', 'killa', 'noun', 'acre of land', 3, 'malwai', '📏',
       'ਸਾਡੇ ਕੋਲ ਪੰਜ ਕਿੱਲੇ ਜ਼ਮੀਨ ਹੈ।', 'saade kol panj kille zameen hai.'],
      ['ਜੱਟ', 'jatt', 'noun', 'farmer (community term)', 2, 'common', '🧑‍🌾',
       'ਜੱਟ ਸਾਰਾ ਦਿਨ ਖੇਤ ਰਹਿੰਦਾ ਹੈ।', 'jatt saara din khet rehnda hai.']
    ],

    /* ── ਕੁਦਰਤ · NATURE ────────────────────────────── */
    nature: [
      ['ਰੁੱਖ', 'rukkh', 'noun', 'tree', 1, 'common', '🌳',
       'ਰੁੱਖ ਦੀ ਛਾਂ ਵਿੱਚ ਬਹਿ ਜਾ।', 'rukkh di chhaan vich beh ja.'],
      ['ਛਾਂ', 'chhaan', 'noun', 'shade', 1, 'common', '🌤️',
       'ਛਾਂ ਬੜੀ ਠੰਢੀ ਹੈ।', 'chhaan barhi thandhi hai.'],
      ['ਮੀਂਹ', 'meenh', 'noun', 'rain', 1, 'common', '🌧️',
       'ਰਾਤੀਂ ਮੀਂਹ ਪਿਆ।', 'raateen meenh piaa.'],
      ['ਹਨੇਰੀ', 'haneri', 'noun', 'dust storm, gale', 2, 'common', '🌪️',
       'ਹਨੇਰੀ ਆਈ ਤੇ ਸਭ ਕੁਝ ਉਡਾ ਲੈ ਗਈ।', 'haneri aaee te sabh kujh udaa lai gaee.'],
      ['ਧੁੱਪ', 'dhupp', 'noun', 'sunshine', 1, 'common', '☀️',
       'ਧੁੱਪ ਬੜੀ ਤਿੱਖੀ ਹੈ।', 'dhupp barhi tikkhi hai.'],
      ['ਕੱਕਰ', 'kakkar', 'noun', 'frost', 3, 'malwai', '❄️',
       'ਰਾਤੀਂ ਕੱਕਰ ਪੈ ਗਿਆ।', 'raateen kakkar pai giaa.'],
      ['ਧੁੰਦ', 'dhund', 'noun', 'fog', 2, 'common', '🌫️',
       'ਧੁੰਦ ਕਰਕੇ ਕੁਝ ਨਹੀਂ ਦਿਸਦਾ।', 'dhund karke kujh naheen disda.'],
      ['ਪੌਣ', 'paun', 'noun', 'wind, breeze', 2, 'common', '🍃',
       'ਠੰਢੀ ਪੌਣ ਵਗ ਰਹੀ ਹੈ।', 'thandhi paun vag rahi hai.'],
      ['ਨਦੀ', 'nadi', 'noun', 'river', 1, 'common', '🏞️',
       'ਨਦੀ ਦਾ ਪਾਣੀ ਚੜ੍ਹ ਗਿਆ।', 'nadi da paani charrh giaa.'],
      ['ਛੱਪੜ', 'chhappar', 'noun', 'village pond', 2, 'common', '🌊',
       'ਮੱਝਾਂ ਛੱਪੜ ਵਿੱਚ ਬੈਠੀਆਂ ਨੇ।', 'majjhaan chhappar vich baithiaan ne.'],
      ['ਟੋਭਾ', 'tobha', 'noun', 'water pit, small pond', 3, 'malwai', '💧',
       'ਟੋਭੇ ਕੰਢੇ ਬੋਹੜ ਹੈ।', 'tobhe kandhe bohrh hai.'],
      ['ਬੋਹੜ', 'bohrh', 'noun', 'banyan tree', 2, 'common', '🌴',
       'ਬੋਹੜ ਹੇਠ ਸੱਥ ਜੁੜਦੀ ਹੈ।', 'bohrh heth sath jurhdi hai.'],
      ['ਪਿੱਪਲ', 'pippal', 'noun', 'peepal tree', 2, 'common', '🌲',
       'ਪਿੱਪਲ ਦੇ ਪੱਤੇ ਖੜਕਦੇ ਨੇ।', 'pippal de patte kharhakde ne.'],
      ['ਕਿੱਕਰ', 'kikkar', 'noun', 'acacia tree', 2, 'common', '🌵',
       'ਕਿੱਕਰ ਦੇ ਕੰਡੇ ਤਿੱਖੇ ਨੇ।', 'kikkar de kande tikkhe ne.'],
      ['ਟਾਹਲੀ', 'taahli', 'noun', 'sheesham tree', 3, 'common', '🪵',
       'ਟਾਹਲੀ ਦੀ ਲੱਕੜ ਮਜ਼ਬੂਤ ਹੁੰਦੀ ਹੈ।', 'taahli di lakkarh mazboot hundi hai.'],
      ['ਚਿੜੀ', 'chirhi', 'noun', 'sparrow, small bird', 1, 'common', '🐦',
       'ਚਿੜੀ ਚੀਂ ਚੀਂ ਕਰਦੀ ਹੈ।', 'chirhi cheen cheen kardi hai.'],
      ['ਕਾਂ', 'kaan', 'noun', 'crow', 1, 'common', '🐦‍⬛',
       'ਕਾਂ ਬਨੇਰੇ ਤੇ ਬੋਲਿਆ।', 'kaan banere te boliaa.'],
      ['ਕੋਇਲ', 'koil', 'noun', 'koel, cuckoo', 2, 'common', '🐤',
       'ਕੋਇਲ ਦੀ ਕੂਕ ਸੁਣੀ।', 'koil di kook suni.'],
      ['ਸੱਪ', 'sapp', 'noun', 'snake', 1, 'common', '🐍',
       'ਖੇਤ ਵਿੱਚ ਸੱਪ ਨਿਕਲਿਆ।', 'khet vich sapp nikliaa.'],
      ['ਟਿੱਡੀ', 'tiddi', 'noun', 'locust, grasshopper', 2, 'common', '🦗',
       'ਟਿੱਡੀ ਦਲ ਨੇ ਫ਼ਸਲ ਖਾ ਲਈ।', 'tiddi dal ne fasal khaa laee.'],
      ['ਜੁਗਨੂੰ', 'jugnoon', 'noun', 'firefly', 2, 'common', '✨',
       'ਹਨੇਰੇ ਵਿੱਚ ਜੁਗਨੂੰ ਚਮਕਦੇ ਨੇ।', 'hanere vich jugnoon chamakde ne.'],
      ['ਮਿੱਟੀ', 'mitti', 'noun', 'soil, earth', 1, 'common', '🟫',
       'ਮੀਂਹ ਪਿੱਛੋਂ ਮਿੱਟੀ ਦੀ ਮਹਿਕ ਆਉਂਦੀ ਹੈ।', 'meenh pichhon mitti di mehak aaundi hai.'],
      ['ਚੰਨ', 'chann', 'noun', 'moon', 1, 'common', '🌙',
       'ਅੱਜ ਚੰਨ ਪੂਰਾ ਹੈ।', 'ajj chann poora hai.'],
      ['ਤਾਰਾ', 'taara', 'noun', 'star', 1, 'common', '⭐',
       'ਅਸਮਾਨ ਤਾਰਿਆਂ ਨਾਲ ਭਰਿਆ ਹੈ।', 'asmaan taariaan naal bhariaa hai.'],
      ['ਬੱਦਲ', 'baddal', 'noun', 'cloud', 1, 'common', '☁️',
       'ਬੱਦਲ ਘਿਰ ਆਏ ਨੇ।', 'baddal ghir aae ne.'],
      ['ਬਿਜਲੀ', 'bijli', 'noun', 'lightning', 2, 'common', '⚡',
       'ਬਿਜਲੀ ਕੜਕੀ।', 'bijli karhki.'],
      ['ਗਰਦ', 'gard', 'noun', 'dust', 2, 'common', '🌬️',
       'ਰਾਹ ਤੇ ਗਰਦ ਉੱਡਦੀ ਹੈ।', 'raah te gard uddadi hai.'],
      ['ਘਾਹ', 'ghaah', 'noun', 'grass', 1, 'common', '🌱',
       'ਘਾਹ ਹਰਾ ਹੋ ਗਿਆ।', 'ghaah haraa ho giaa.'],
      ['ਫੁੱਲ', 'phull', 'noun', 'flower', 1, 'common', '🌸',
       'ਫੁੱਲ ਖਿੜ ਪਏ ਨੇ।', 'phull khirh pae ne.'],
      ['ਪੱਤਾ', 'patta', 'noun', 'leaf', 1, 'common', '🍂',
       'ਪੱਤੇ ਝੜ ਰਹੇ ਨੇ।', 'patte jharh rahe ne.'],
      ['ਜੜ੍ਹ', 'jarrh', 'noun', 'root', 2, 'common', '🪴',
       'ਰੁੱਖ ਦੀ ਜੜ੍ਹ ਡੂੰਘੀ ਹੈ।', 'rukkh di jarrh doonghi hai.'],
      ['ਕੰਡਾ', 'kanda', 'noun', 'thorn', 1, 'common', '📌',
       'ਪੈਰ ਵਿੱਚ ਕੰਡਾ ਵੱਜ ਗਿਆ।', 'pair vich kanda vajj giaa.'],
      ['ਧਰਤੀ', 'dharti', 'noun', 'earth, ground', 1, 'common', '🌍',
       'ਧਰਤੀ ਮਾਂ ਵਰਗੀ ਹੈ।', 'dharti maan vargi hai.'],
      ['ਅਸਮਾਨ', 'asmaan', 'noun', 'sky', 1, 'common', '🌌',
       'ਅਸਮਾਨ ਸਾਫ਼ ਹੈ।', 'asmaan saaf hai.'],
      ['ਸੂਰਜ', 'sooraj', 'noun', 'sun', 1, 'common', '🌞',
       'ਸੂਰਜ ਚੜ੍ਹ ਪਿਆ।', 'sooraj charrh piaa.'],
      ['ਅੱਗ', 'agg', 'noun', 'fire', 1, 'common', '🔥',
       'ਅੱਗ ਬਾਲ਼ ਲੈ।', 'agg baal lai.'],
      ['ਪਾਣੀ', 'paani', 'noun', 'water', 1, 'common', '🚰',
       'ਪਾਣੀ ਪੀ ਲੈ।', 'paani pee lai.'],
      ['ਹਵਾ', 'hava', 'noun', 'air', 1, 'common', '🎐',
       'ਹਵਾ ਬੰਦ ਹੋ ਗਈ।', 'hava band ho gaee.'],
      ['ਪੱਥਰ', 'patthar', 'noun', 'stone', 1, 'common', '🪨',
       'ਪੱਥਰ ਚੁੱਕ ਕੇ ਸੁੱਟ ਦੇ।', 'patthar chukk ke sutt de.'],
      ['ਰੇਤ', 'ret', 'noun', 'sand', 2, 'common', '⏳',
       'ਨਦੀ ਕੰਢੇ ਰੇਤ ਹੈ।', 'nadi kandhe ret hai.'],
      ['ਚੂਹਾ', 'chooha', 'noun', 'mouse, rat', 1, 'common', '🐁',
       'ਚੂਹਾ ਦਾਣੇ ਖਾ ਗਿਆ।', 'chooha daane khaa giaa.'],
      ['ਗਿਰਝ', 'girajh', 'noun', 'vulture', 3, 'common', '🦅',
       'ਗਿਰਝਾਂ ਹੁਣ ਘੱਟ ਦਿਸਦੀਆਂ ਨੇ।', 'girjhaan hun ghatt disdiaan ne.'],
      ['ਮੋਰ', 'mor', 'noun', 'peacock', 1, 'common', '🦚',
       'ਮੋਰ ਪੈਲਾਂ ਪਾ ਰਿਹਾ ਹੈ।', 'mor pailaan paa rihaa hai.'],
      ['ਤਿੱਤਰ', 'tittar', 'noun', 'partridge', 3, 'malwai', '🐓',
       'ਤਿੱਤਰ ਬੋਲਦਾ ਸੁਣਿਆ।', 'tittar bolda suniaa.'],
      ['ਮੱਖੀ', 'makkhi', 'noun', 'fly', 1, 'common', '🪰',
       'ਮੱਖੀਆਂ ਬੜੀਆਂ ਨੇ।', 'makkhiaan barhiaan ne.']
    ],

    /* ── ਸਰੀਰ · BODY ───────────────────────────────── */
    body: [
      ['ਸਿਰ', 'sir', 'noun', 'head', 1, 'common', '🧠',
       'ਸਿਰ ਦੁਖ ਰਿਹਾ ਹੈ।', 'sir dukh rihaa hai.'],
      ['ਅੱਖ', 'akkh', 'noun', 'eye', 1, 'common', '👁️',
       'ਅੱਖ ਵਿੱਚ ਕੁਝ ਪੈ ਗਿਆ।', 'akkh vich kujh pai giaa.'],
      ['ਕੰਨ', 'kann', 'noun', 'ear', 1, 'common', '👂',
       'ਕੰਨ ਖੋਲ੍ਹ ਕੇ ਸੁਣ।', 'kann kholh ke sun.'],
      ['ਨੱਕ', 'nakk', 'noun', 'nose', 1, 'common', '👃',
       'ਨੱਕ ਵਗ ਰਿਹਾ ਹੈ।', 'nakk vag rihaa hai.'],
      ['ਮੂੰਹ', 'moonh', 'noun', 'mouth, face', 1, 'common', '👄',
       'ਮੂੰਹ ਧੋ ਲੈ।', 'moonh dho lai.'],
      ['ਹੱਥ', 'hatth', 'noun', 'hand', 1, 'common', '✋',
       'ਹੱਥ ਧੋ ਕੇ ਰੋਟੀ ਖਾ।', 'hatth dho ke roti khaa.'],
      ['ਪੈਰ', 'pair', 'noun', 'foot', 1, 'common', '🦶',
       'ਪੈਰ ਵਿੱਚ ਕੰਡਾ ਵੱਜਿਆ।', 'pair vich kanda vajjiaa.'],
      ['ਲੱਤ', 'latt', 'noun', 'leg', 1, 'common', '🦵',
       'ਲੱਤ ਵਿੱਚ ਪੀੜ ਹੈ।', 'latt vich peerh hai.'],
      ['ਬਾਂਹ', 'baanh', 'noun', 'arm', 1, 'common', '💪',
       'ਬਾਂਹ ਫੜ ਕੇ ਚੁੱਕ ਲੈ।', 'baanh pharh ke chukk lai.'],
      ['ਢਿੱਡ', 'dhidd', 'noun', 'belly, stomach', 1, 'common', '🫄',
       'ਢਿੱਡ ਭਰ ਗਿਆ।', 'dhidd bhar giaa.'],
      ['ਪਿੱਠ', 'pitth', 'noun', 'back', 1, 'common', '🔙',
       'ਪਿੱਠ ਤੇ ਭਾਰ ਚੁੱਕਿਆ।', 'pitth te bhaar chukkiaa.'],
      ['ਗਲ਼', 'gal', 'noun', 'throat, neck', 2, 'common', '🗣️',
       'ਗਲ਼ ਬਹਿ ਗਿਆ।', 'gal beh giaa.'],
      ['ਵਾਲ਼', 'vaal', 'noun', 'hair', 1, 'common', '💇',
       'ਵਾਲ਼ ਵਾਹ ਲੈ।', 'vaal vaah lai.'],
      ['ਦੰਦ', 'dand', 'noun', 'tooth', 1, 'common', '🦷',
       'ਦੰਦ ਦੁਖਦਾ ਹੈ।', 'dand dukhda hai.'],
      ['ਜੀਭ', 'jeebh', 'noun', 'tongue', 1, 'common', '👅',
       'ਜੀਭ ਸੜ ਗਈ।', 'jeebh sarh gaee.'],
      ['ਉਂਗਲ', 'ungal', 'noun', 'finger', 1, 'common', '☝️',
       'ਉਂਗਲ ਕੱਟੀ ਗਈ।', 'ungal katti gaee.'],
      ['ਗੋਡਾ', 'goda', 'noun', 'knee', 2, 'common', '🧎',
       'ਗੋਡੇ ਦੁਖਦੇ ਨੇ।', 'gode dukhde ne.'],
      ['ਮੋਢਾ', 'modha', 'noun', 'shoulder', 2, 'common', '🫸',
       'ਮੋਢੇ ਤੇ ਚੁੱਕ ਲੈ।', 'modhe te chukk lai.'],
      ['ਅੱਡੀ', 'addi', 'noun', 'heel', 2, 'common', '👠',
       'ਅੱਡੀ ਫਟ ਗਈ ਹੈ।', 'addi phat gaee hai.'],
      ['ਗੁੱਟ', 'gutt', 'noun', 'wrist', 2, 'common', '⌚',
       'ਗੁੱਟ ਤੇ ਕੜਾ ਪਾਇਆ ਹੈ।', 'gutt te karha paaiaa hai.'],
      ['ਮੱਥਾ', 'mattha', 'noun', 'forehead', 2, 'common', '😐',
       'ਮੱਥੇ ਤੇ ਤਿਊੜੀ ਪਾ ਲਈ।', 'matthe te tiurhi paa laee.'],
      ['ਲਹੂ', 'lahoo', 'noun', 'blood', 2, 'common', '🩸',
       'ਜ਼ਖ਼ਮ ਵਿੱਚੋਂ ਲਹੂ ਵਗਿਆ।', 'zakhm vichon lahoo vagiaa.'],
      ['ਸਾਹ', 'saah', 'noun', 'breath', 2, 'common', '💨',
       'ਸਾਹ ਚੜ੍ਹ ਗਿਆ।', 'saah charrh giaa.'],
      ['ਹੱਡੀ', 'haddi', 'noun', 'bone', 2, 'common', '🦴',
       'ਹੱਡੀ ਟੁੱਟ ਗਈ।', 'haddi tutt gaee.'],
      ['ਚਮੜੀ', 'chamrhi', 'noun', 'skin', 2, 'common', '🧴',
       'ਚਮੜੀ ਖੁਸ਼ਕ ਹੋ ਗਈ।', 'chamrhi khushk ho gaee.'],
      ['ਥੁੱਕ', 'thukk', 'noun', 'spit, saliva', 3, 'common', '💧',
       'ਮੂੰਹ ਵਿੱਚ ਥੁੱਕ ਸੁੱਕ ਗਿਆ।', 'moonh vich thukk sukk giaa.'],
      ['ਗਿੱਟਾ', 'gitta', 'noun', 'ankle', 3, 'malwai', '🧦',
       'ਗਿੱਟਾ ਮੁੜ ਗਿਆ।', 'gitta murh giaa.'],
      ['ਦਿਲ', 'dil', 'noun', 'heart', 1, 'common', '❤️',
       'ਦਿਲ ਬੜਾ ਵੱਡਾ ਹੈ ਉਹਦਾ।', 'dil barhaa vaddaa hai ohda.'],
      ['ਅੱਡ', 'add', 'noun', 'palm of the hand', 3, 'malwai', '🤲',
       'ਅੱਡ ਅੱਗੇ ਕਰ।', 'add agge kar.'],
      ['ਨਹੁੰ', 'nahun', 'noun', 'nail', 2, 'common', '💅',
       'ਨਹੁੰ ਕੱਟ ਲੈ।', 'nahun katt lai.'],
      ['ਭਰਵੱਟਾ', 'bharvatta', 'noun', 'eyebrow', 3, 'common', '👁️‍🗨️',
       'ਭਰਵੱਟੇ ਚੜ੍ਹਾ ਲਏ।', 'bharvatte charrhaa lae.'],
      ['ਬੁੱਲ੍ਹ', 'bullh', 'noun', 'lip', 2, 'common', '💋',
       'ਬੁੱਲ੍ਹ ਸੁੱਕ ਗਏ।', 'bullh sukk gae.'],
      ['ਗੱਲ੍ਹ', 'gallh', 'noun', 'cheek', 2, 'common', '😊',
       'ਗੱਲ੍ਹਾਂ ਲਾਲ ਹੋ ਗਈਆਂ।', 'gallhaan laal ho gaeeaan.'],
      ['ਠੋਡੀ', 'thodi', 'noun', 'chin', 3, 'common', '🙂',
       'ਠੋਡੀ ਤੇ ਹੱਥ ਰੱਖ ਕੇ ਬੈਠਾ ਸੀ।', 'thodi te hatth rakkh ke baitha si.'],
      ['ਦਾੜ੍ਹੀ', 'daarrhi', 'noun', 'beard', 1, 'common', '🧔‍♂️',
       'ਬਾਬੇ ਦੀ ਦਾੜ੍ਹੀ ਚਿੱਟੀ ਹੈ।', 'baabe di daarrhi chitti hai.'],
      ['ਮੁੱਛ', 'muchh', 'noun', 'moustache', 2, 'common', '👨‍🦰',
       'ਮੁੱਛਾਂ ਨੂੰ ਤਾਅ ਦਿੱਤਾ।', 'muchhaan nu taa dittaa.'],
      ['ਢਿੱਡ ਪੀੜ', 'dhidd peerh', 'noun', 'stomach ache', 2, 'common', '🤢',
       'ਮੈਨੂੰ ਢਿੱਡ ਪੀੜ ਹੈ।', 'mainu dhidd peerh hai.'],
      ['ਬੁਖ਼ਾਰ', 'bukhaar', 'noun', 'fever', 1, 'common', '🤒',
       'ਨਿਆਣੇ ਨੂੰ ਬੁਖ਼ਾਰ ਹੈ।', 'niaane nu bukhaar hai.'],
      ['ਖੰਘ', 'khangh', 'noun', 'cough', 1, 'common', '😷',
       'ਖੰਘ ਨਹੀਂ ਹਟਦੀ।', 'khangh naheen hatdi.'],
      ['ਜ਼ਖ਼ਮ', 'zakhm', 'noun', 'wound', 2, 'common', '🩹',
       'ਜ਼ਖ਼ਮ ਭਰ ਗਿਆ।', 'zakhm bhar giaa.'],
      ['ਨੀਂਦ', 'neend', 'noun', 'sleep', 1, 'common', '😴',
       'ਮੈਨੂੰ ਨੀਂਦ ਆ ਰਹੀ ਹੈ।', 'mainu neend aa rahi hai.'],
      ['ਪਸੀਨਾ', 'paseena', 'noun', 'sweat', 2, 'common', '💧',
       'ਗਰਮੀ ਨਾਲ ਪਸੀਨਾ ਆ ਗਿਆ।', 'garmi naal paseena aa giaa.'],
      ['ਅੱਥਰੂ', 'atthroo', 'noun', 'tear', 2, 'common', '😢',
       'ਅੱਥਰੂ ਵਹਿ ਤੁਰੇ।', 'atthroo veh ture.'],
      ['ਜਾਨ', 'jaan', 'noun', 'life, vitality', 2, 'common', '✨',
       'ਹੱਥਾਂ ਵਿੱਚ ਜਾਨ ਨਹੀਂ ਰਹੀ।', 'hatthaan vich jaan naheen rahi.'],
      ['ਕਮਰ', 'kamar', 'noun', 'waist', 2, 'common', '🩳',
       'ਕਮਰ ਦੁਖਦੀ ਹੈ।', 'kamar dukhdi hai.']
    ],

    /* ── ਖਾਣਾ · FOOD ───────────────────────────────── */
    food: [
      ['ਰੋਟੀ', 'roti', 'noun', 'flatbread; a meal', 1, 'common', '🫓',
       'ਰੋਟੀ ਖਾ ਲੈ।', 'roti khaa lai.'],
      ['ਦਾਲ', 'daal', 'noun', 'lentils', 1, 'common', '🍲',
       'ਦਾਲ ਧਰ ਦਿੱਤੀ ਹੈ।', 'daal dhar ditti hai.'],
      ['ਸਾਗ', 'saag', 'noun', 'mustard greens dish', 1, 'common', '🥬',
       'ਸਾਗ ਤੇ ਮੱਕੀ ਦੀ ਰੋਟੀ ਬਣੀ ਹੈ।', 'saag te makki di roti bani hai.'],
      ['ਲੱਸੀ', 'lassi', 'noun', 'buttermilk drink', 1, 'common', '🧉',
       'ਲੱਸੀ ਦਾ ਗਲਾਸ ਪੀ ਲੈ।', 'lassi da galaas pee lai.'],
      ['ਮੱਖਣ', 'makkhan', 'noun', 'butter', 1, 'common', '🧈',
       'ਰੋਟੀ ਤੇ ਮੱਖਣ ਲਾ ਦੇ।', 'roti te makkhan laa de.'],
      ['ਦੁੱਧ', 'duddh', 'noun', 'milk', 1, 'common', '🥛',
       'ਦੁੱਧ ਕਾੜ੍ਹ ਲੈ।', 'duddh kaarrh lai.'],
      ['ਦਹੀਂ', 'daheen', 'noun', 'yoghurt', 1, 'common', '🥣',
       'ਦਹੀਂ ਜਮਾ ਦਿੱਤਾ।', 'daheen jamaa dittaa.'],
      ['ਗੁੜ', 'gurh', 'noun', 'jaggery', 2, 'common', '🟤',
       'ਗੁੜ ਦੀ ਰੋੜੀ ਖਾ ਲੈ।', 'gurh di rorhi khaa lai.'],
      ['ਖੰਡ', 'khand', 'noun', 'sugar', 1, 'common', '🍬',
       'ਚਾਹ ਵਿੱਚ ਖੰਡ ਪਾ ਦੇ।', 'chaah vich khand paa de.'],
      ['ਆਟਾ', 'aata', 'noun', 'flour', 1, 'common', '🌾',
       'ਆਟਾ ਗੁੰਨ੍ਹ ਲੈ।', 'aata gunnh lai.'],
      ['ਮੱਕੀ', 'makki', 'noun', 'maize, corn', 1, 'common', '🌽',
       'ਮੱਕੀ ਦੀ ਰੋਟੀ ਸੁਆਦ ਹੁੰਦੀ ਹੈ।', 'makki di roti suaad hundi hai.'],
      ['ਛੋਲੇ', 'chhole', 'noun', 'chickpeas', 2, 'common', '🫘',
       'ਛੋਲੇ ਭਿਉਂ ਦਿੱਤੇ।', 'chhole bhiun ditte.'],
      ['ਅਚਾਰ', 'achaar', 'noun', 'pickle', 1, 'common', '🥒',
       'ਅੰਬ ਦਾ ਅਚਾਰ ਪਾਇਆ ਹੈ।', 'amb da achaar paaiaa hai.'],
      ['ਚਟਣੀ', 'chatni', 'noun', 'chutney', 2, 'common', '🌶️',
       'ਪੁਦੀਨੇ ਦੀ ਚਟਣੀ ਬਣਾ।', 'pudeene di chatni banaa.'],
      ['ਖੀਰ', 'kheer', 'noun', 'rice pudding', 2, 'common', '🍨',
       'ਖੀਰ ਬਣਾਈ ਹੈ।', 'kheer banaaee hai.'],
      ['ਪਕੌੜਾ', 'pakaurha', 'noun', 'fritter', 1, 'common', '🍤',
       'ਮੀਂਹ ਵਿੱਚ ਪਕੌੜੇ ਤਲ਼ੇ।', 'meenh vich pakaurhe tale.'],
      ['ਕੜ੍ਹੀ', 'karrhi', 'noun', 'gram-flour yoghurt curry', 2, 'common', '🍛',
       'ਕੜ੍ਹੀ ਚੌਲ ਬਣੇ ਨੇ।', 'karrhi chaul bane ne.'],
      ['ਪੰਜੀਰੀ', 'panjeeri', 'noun', 'sweet flour-nut preparation', 3, 'common', '🥜',
       'ਸਿਆਲ਼ ਵਿੱਚ ਪੰਜੀਰੀ ਖਾਈਦੀ ਹੈ।', 'siaal vich panjeeri khaaeedi hai.'],
      ['ਕੜਾਹ', 'karhaah', 'noun', 'sacred semolina pudding', 2, 'common', '🍮',
       'ਕੜਾਹ ਪ੍ਰਸ਼ਾਦ ਵਰਤਾਇਆ।', 'karhaah parshaad vartaaiaa.'],
      ['ਮਧਾਣੀ', 'madhaani', 'noun', 'wooden churning staff', 3, 'common', '🥄',
       'ਮਧਾਣੀ ਨਾਲ ਦਹੀਂ ਰਿੜਕਿਆ।', 'madhaani naal daheen rirhkiaa.'],
      ['ਚਾਟੀ', 'chaati', 'noun', 'earthen churning pot', 3, 'malwai', '🏺',
       'ਚਾਟੀ ਵਿੱਚ ਦਹੀਂ ਪਾਇਆ।', 'chaati vich daheen paaiaa.'],
      ['ਭੁੱਖ', 'bhukkh', 'noun', 'hunger', 1, 'common', '🍽️',
       'ਬੜੀ ਭੁੱਖ ਲੱਗੀ ਹੈ।', 'barhi bhukkh laggi hai.'],
      ['ਪਿਆਸ', 'piaas', 'noun', 'thirst', 1, 'common', '🥤',
       'ਪਿਆਸ ਨਾਲ ਗਲ਼ ਸੁੱਕ ਗਿਆ।', 'piaas naal gal sukk giaa.'],
      ['ਸੁਆਦ', 'suaad', 'noun', 'taste, flavour', 1, 'common', '😋',
       'ਬੜਾ ਸੁਆਦ ਬਣਿਆ ਹੈ।', 'barhaa suaad baniaa hai.'],
      ['ਚੌਲ', 'chaul', 'noun', 'rice', 1, 'common', '🍚',
       'ਚੌਲ ਧਰ ਦੇ।', 'chaul dhar de.'],
      ['ਸਬਜ਼ੀ', 'sabzi', 'noun', 'vegetable dish', 1, 'common', '🥕',
       'ਅੱਜ ਕਿਹੜੀ ਸਬਜ਼ੀ ਬਣੀ ਹੈ?', 'ajj kehrhi sabzi bani hai?'],
      ['ਦੇਸੀ ਘਿਓ', 'desi ghio', 'noun', 'clarified butter', 2, 'common', '🫗',
       'ਦੇਸੀ ਘਿਓ ਪਾ ਕੇ ਖਾ।', 'desi ghio paa ke khaa.'],
      ['ਚਾਹ', 'chaah', 'noun', 'tea', 1, 'common', '🍵',
       'ਚਾਹ ਧਰ ਦੇ।', 'chaah dhar de.'],
      ['ਪਰੌਂਠਾ', 'praunthaa', 'noun', 'stuffed flatbread', 1, 'common', '🥞',
       'ਆਲੂ ਵਾਲਾ ਪਰੌਂਠਾ ਬਣਿਆ ਹੈ।', 'aaloo vaala praunthaa baniaa hai.'],
      ['ਆਲੂ', 'aaloo', 'noun', 'potato', 1, 'common', '🥔',
       'ਆਲੂ ਉਬਾਲ਼ ਲੈ।', 'aaloo ubaal lai.'],
      ['ਪਿਆਜ਼', 'piaaz', 'noun', 'onion', 1, 'common', '🧅',
       'ਪਿਆਜ਼ ਕੱਟ ਦੇ।', 'piaaz katt de.'],
      ['ਲਸਣ', 'lasan', 'noun', 'garlic', 1, 'common', '🧄',
       'ਲਸਣ ਪਾ ਕੇ ਤੜਕਾ ਲਾ।', 'lasan paa ke tarhka laa.'],
      ['ਮਿਰਚ', 'mirach', 'noun', 'chilli', 1, 'common', '🌶️',
       'ਮਿਰਚ ਬੜੀ ਤੇਜ਼ ਹੈ।', 'mirach barhi tez hai.'],
      ['ਲੂਣ', 'loon', 'noun', 'salt', 1, 'common', '🧂',
       'ਲੂਣ ਘੱਟ ਹੈ।', 'loon ghatt hai.'],
      ['ਹਲਦੀ', 'haldi', 'noun', 'turmeric', 2, 'common', '🟡',
       'ਹਲਦੀ ਵਾਲਾ ਦੁੱਧ ਪੀ ਲੈ।', 'haldi vaala duddh pee lai.'],
      ['ਤੜਕਾ', 'tarhka', 'noun', 'tempering of spices', 2, 'common', '🍳',
       'ਦਾਲ ਨੂੰ ਤੜਕਾ ਲਾ ਦੇ।', 'daal nu tarhka laa de.'],
      ['ਭਾਜੀ', 'bhaaji', 'noun', 'cooked vegetable', 2, 'doabi', '🥗',
       'ਭਾਜੀ ਬਣ ਗਈ।', 'bhaaji ban gaee.'],
      ['ਮੱਠਾ', 'matthaa', 'noun', 'thin buttermilk', 3, 'malwai', '🫙',
       'ਮੱਠਾ ਪੀ ਕੇ ਠੰਢ ਪੈ ਗਈ।', 'matthaa pee ke thandh pai gaee.'],
      ['ਬੂਰਾ', 'boora', 'noun', 'coarse raw sugar', 3, 'malwai', '🍥',
       'ਰੋਟੀ ਤੇ ਬੂਰਾ ਪਾ ਕੇ ਖਾਧਾ।', 'roti te boora paa ke khaadhaa.'],
      ['ਸ਼ੱਕਰ', 'shakkar', 'noun', 'unrefined sugar', 3, 'common', '🍯',
       'ਸ਼ੱਕਰ ਤੇ ਘਿਓ ਨਾਲ ਰੋਟੀ।', 'shakkar te ghio naal roti.'],
      ['ਮੱਕੀ ਦੀ ਰੋਟੀ', 'makki di roti', 'noun', 'maize flatbread', 1, 'common', '🫓',
       'ਸਾਗ ਨਾਲ ਮੱਕੀ ਦੀ ਰੋਟੀ ਖਾਓ।', 'saag naal makki di roti khaao.'],
      ['ਜਲੇਬੀ', 'jalebi', 'noun', 'spiral syrup sweet', 1, 'common', '🍩',
       'ਮੇਲੇ ਵਿੱਚ ਜਲੇਬੀਆਂ ਮਿਲਦੀਆਂ ਨੇ।', 'mele vich jalebiaan mildiaan ne.'],
      ['ਮਿਠਾਈ', 'mithaaee', 'noun', 'sweets', 1, 'common', '🍬',
       'ਖ਼ੁਸ਼ੀ ਵਿੱਚ ਮਿਠਾਈ ਵੰਡੀ।', 'khushi vich mithaaee vandi.'],
      ['ਭੁੱਜਾ', 'bhujja', 'noun', 'roasted grain snack', 3, 'malwai', '🥜',
       'ਭੁੱਜਾ ਚੱਬਦੇ ਰਹੇ।', 'bhujja chabbde rahe.'],
      ['ਰਿੜਕਣਾ', 'rirhakna', 'verb', 'to churn', 3, 'common', '🥄',
       'ਬੇਬੇ ਸਵੇਰੇ ਦਹੀਂ ਰਿੜਕਦੀ ਹੈ।', 'bebe savere daheen rirhakdi hai.']
    ],

    /* ── ਰਿਸ਼ਤੇ · KINSHIP ──────────────────────────── */
    kinship: [
      ['ਬੇਬੇ', 'bebe', 'noun', 'mother (rural address)', 1, 'malwai', '👩',
       'ਬੇਬੇ ਨੇ ਰੋਟੀ ਪਕਾਈ।', 'bebe ne roti pakaaee.'],
      ['ਬਾਪੂ', 'baapu', 'noun', 'father (rural address)', 1, 'malwai', '👨',
       'ਬਾਪੂ ਖੇਤ ਗਿਆ ਹੈ।', 'baapu khet giaa hai.'],
      ['ਦਾਦਾ', 'daada', 'noun', 'paternal grandfather', 1, 'common', '👴',
       'ਦਾਦਾ ਜੀ ਕਹਾਣੀ ਸੁਣਾਉਂਦੇ ਨੇ।', 'daada ji kahaani sunaaunde ne.'],
      ['ਦਾਦੀ', 'daadi', 'noun', 'paternal grandmother', 1, 'common', '👵',
       'ਦਾਦੀ ਦੀ ਗੋਦ ਵਿੱਚ ਸੌਂ ਗਿਆ।', 'daadi di god vich saun giaa.'],
      ['ਨਾਨਾ', 'naana', 'noun', 'maternal grandfather', 1, 'common', '🧓',
       'ਨਾਨਾ ਜੀ ਪਿੰਡੋਂ ਆਏ ਨੇ।', 'naana ji pindon aae ne.'],
      ['ਨਾਨੀ', 'naani', 'noun', 'maternal grandmother', 1, 'common', '🧕',
       'ਨਾਨੀ ਦੇ ਘਰ ਜਾਣਾ ਹੈ।', 'naani de ghar jaana hai.'],
      ['ਭਰਾ', 'bhraa', 'noun', 'brother', 1, 'common', '👦',
       'ਮੇਰਾ ਭਰਾ ਵੱਡਾ ਹੈ।', 'mera bhraa vaddaa hai.'],
      ['ਭੈਣ', 'bhain', 'noun', 'sister', 1, 'common', '👧',
       'ਭੈਣ ਸਕੂਲ ਗਈ ਹੈ।', 'bhain skool gaee hai.'],
      ['ਚਾਚਾ', 'chaacha', 'noun', "father's younger brother", 1, 'common', '🧔',
       'ਚਾਚਾ ਸ਼ਹਿਰੋਂ ਆਇਆ।', 'chaacha shehron aaiaa.'],
      ['ਤਾਇਆ', 'taaiaa', 'noun', "father's elder brother", 1, 'common', '👳',
       'ਤਾਇਆ ਜੀ ਸੱਥ ਵਿੱਚ ਬੈਠੇ ਨੇ।', 'taaiaa ji sath vich baithe ne.'],
      ['ਭੂਆ', 'bhooaa', 'noun', "father's sister", 2, 'common', '💃',
       'ਭੂਆ ਦਾ ਪਿੰਡ ਨੇੜੇ ਹੈ।', 'bhooaa da pind nerhe hai.'],
      ['ਮਾਸੀ', 'maasi', 'noun', "mother's sister", 2, 'common', '🙎‍♀️',
       'ਮਾਸੀ ਨੇ ਬੜਾ ਲਾਡ ਕੀਤਾ।', 'maasi ne barhaa laad keetaa.'],
      ['ਮਾਮਾ', 'maama', 'noun', "mother's brother", 1, 'common', '🙋‍♂️',
       'ਮਾਮਾ ਜੀ ਲੈਣ ਆਏ ਨੇ।', 'maama ji lain aae ne.'],
      ['ਪੁੱਤ', 'putt', 'noun', 'son; term of endearment', 1, 'common', '🧒',
       'ਪੁੱਤ, ਰੋਟੀ ਖਾ ਲੈ।', 'putt, roti khaa lai.'],
      ['ਧੀ', 'dhee', 'noun', 'daughter', 1, 'common', '👶',
       'ਧੀ ਘਰ ਦੀ ਰੌਣਕ ਹੁੰਦੀ ਹੈ।', 'dhee ghar di raunak hundi hai.'],
      ['ਨੂੰਹ', 'noonh', 'noun', 'daughter-in-law', 2, 'common', '👰',
       'ਨੂੰਹ ਘਰ ਆਈ ਹੈ।', 'noonh ghar aaee hai.'],
      ['ਜਵਾਈ', 'javaaee', 'noun', 'son-in-law', 2, 'common', '🤵',
       'ਜਵਾਈ ਜੀ ਆਏ ਨੇ।', 'javaaee ji aae ne.'],
      ['ਸੱਸ', 'sass', 'noun', 'mother-in-law', 2, 'common', '👩‍🦳',
       'ਸੱਸ ਨੇ ਅਸੀਸ ਦਿੱਤੀ।', 'sass ne asees ditti.'],
      ['ਸਹੁਰਾ', 'sohra', 'noun', 'father-in-law', 2, 'common', '👨‍🦳',
       'ਸਹੁਰਾ ਸਾਹਬ ਬੈਠੇ ਨੇ।', 'sohra saahab baithe ne.'],
      ['ਦਿਓਰ', 'dior', 'noun', "husband's younger brother", 3, 'common', '🧑',
       'ਦਿਓਰ ਬੜਾ ਮਖੌਲੀਆ ਹੈ।', 'dior barhaa makhaulia hai.'],
      ['ਜੇਠ', 'jeth', 'noun', "husband's elder brother", 3, 'common', '🧑‍🦱',
       'ਜੇਠ ਜੀ ਦਾ ਬੜਾ ਅਦਬ ਹੈ।', 'jeth ji da barhaa adab hai.'],
      ['ਨਣਦ', 'nanad', 'noun', "husband's sister", 3, 'common', '👱‍♀️',
       'ਨਣਦ ਨਾਲ ਚੰਗੀ ਬਣਦੀ ਹੈ।', 'nanad naal changi bandi hai.'],
      ['ਪੇਕੇ', 'peke', 'noun', "a married woman's parental home", 3, 'common', '🏡',
       'ਉਹ ਪੇਕੇ ਗਈ ਹੋਈ ਹੈ।', 'oh peke gaee hoee hai.'],
      ['ਸਹੁਰੇ', 'sohre', 'noun', "in-laws' home", 2, 'common', '🏘️',
       'ਸਹੁਰੇ ਪਿੰਡ ਦੂਰ ਹੈ।', 'sohre pind door hai.'],
      ['ਸ਼ਰੀਕ', 'shareek', 'noun', 'kin-rival, extended-family rival', 3, 'malwai', '⚔️',
       'ਸ਼ਰੀਕਾਂ ਨਾਲ ਜ਼ਮੀਨ ਦਾ ਝਗੜਾ ਹੈ।', 'shareekaan naal zameen da jhagrhaa hai.'],
      ['ਯਾਰ', 'yaar', 'noun', 'close friend', 1, 'common', '🤝',
       'ਯਾਰਾਂ ਬਿਨਾਂ ਨਹੀਂ ਸਰਦਾ।', 'yaaraan binaan naheen sarda.'],
      ['ਗੁਆਂਢੀ', 'guaandhi', 'noun', 'neighbour', 1, 'common', '🏚️',
       'ਗੁਆਂਢੀ ਬੜੇ ਚੰਗੇ ਨੇ।', 'guaandhi barhe change ne.'],
      ['ਮਾਂ', 'maan', 'noun', 'mother', 1, 'common', '🤱',
       'ਮਾਂ ਦਾ ਪਿਆਰ ਬੇਅੰਤ ਹੈ।', 'maan da piaar beant hai.'],
      ['ਪਿਓ', 'pio', 'noun', 'father', 1, 'common', '🧍‍♂️',
       'ਪਿਓ ਪੁੱਤ ਇਕੱਠੇ ਗਏ।', 'pio putt ikatthe gae.'],
      ['ਪਰਿਵਾਰ', 'parivaar', 'noun', 'family', 1, 'common', '👪',
       'ਸਾਰਾ ਪਰਿਵਾਰ ਜੁੜ ਗਿਆ।', 'saara parivaar jurh giaa.'],
      ['ਟੱਬਰ', 'tabbar', 'noun', 'household, whole family', 3, 'malwai', '🏠',
       'ਸਾਰਾ ਟੱਬਰ ਵਿਆਹ ਤੇ ਆਇਆ।', 'saara tabbar viaah te aaiaa.'],
      ['ਵਿਆਹ', 'viaah', 'noun', 'wedding', 1, 'common', '💍',
       'ਵਿਆਹ ਦੀਆਂ ਤਿਆਰੀਆਂ ਚੱਲ ਰਹੀਆਂ ਨੇ।', 'viaah diaan tiaariaan chall rahiaan ne.'],
      ['ਬਰਾਤ', 'baraat', 'noun', 'wedding procession', 2, 'common', '🎺',
       'ਬਰਾਤ ਆ ਗਈ।', 'baraat aa gaee.'],
      ['ਮੁੰਡਾ', 'munda', 'noun', 'boy', 1, 'common', '👦',
       'ਮੁੰਡਾ ਸਕੂਲ ਗਿਆ।', 'munda skool giaa.'],
      ['ਕੁੜੀ', 'kurhi', 'noun', 'girl', 1, 'common', '👧',
       'ਕੁੜੀ ਬੜੀ ਸਿਆਣੀ ਹੈ।', 'kurhi barhi siaani hai.'],
      ['ਨਿਆਣਾ', 'niaana', 'noun', 'child', 1, 'malwai', '🧸',
       'ਨਿਆਣੇ ਖੇਡ ਰਹੇ ਨੇ।', 'niaane khed rahe ne.'],
      ['ਬਜ਼ੁਰਗ', 'bazurag', 'noun', 'elder', 2, 'common', '🕰️',
       'ਬਜ਼ੁਰਗਾਂ ਦੀ ਗੱਲ ਮੰਨ।', 'bazurgaan di gall mann.'],
      ['ਬੰਦਾ', 'banda', 'noun', 'man, person', 1, 'common', '🚶',
       'ਬੰਦਾ ਚੰਗਾ ਹੈ।', 'banda changa hai.'],
      ['ਤੀਵੀਂ', 'teeveen', 'noun', 'woman, wife', 3, 'malwai', '🚶‍♀️',
       'ਤੀਵੀਂ ਖੇਤ ਗਈ ਹੋਈ ਹੈ।', 'teeveen khet gaee hoee hai.'],
      ['ਘਰਵਾਲ਼ੀ', 'gharvaali', 'noun', 'wife', 2, 'common', '💑',
       'ਘਰਵਾਲ਼ੀ ਨੇ ਰੋਟੀ ਬਣਾਈ।', 'gharvaali ne roti banaaee.'],
      ['ਭਤੀਜਾ', 'bhateeja', 'noun', "brother's son", 2, 'common', '🧑‍🎓',
       'ਭਤੀਜਾ ਸ਼ਹਿਰ ਪੜ੍ਹਦਾ ਹੈ।', 'bhateeja shehar parrhda hai.'],
      ['ਭਾਣਜਾ', 'bhaanja', 'noun', "sister's son", 3, 'common', '🧑‍🔧',
       'ਭਾਣਜਾ ਨਾਨਕੇ ਆਇਆ ਹੈ।', 'bhaanja naanke aaiaa hai.'],
      ['ਦੋਹਤਾ', 'dohta', 'noun', "daughter's son", 3, 'common', '👼',
       'ਦੋਹਤਾ ਨਾਨੀ ਕੋਲ ਰਹਿੰਦਾ ਹੈ।', 'dohta naani kol rehnda hai.'],
      ['ਪੋਤਾ', 'pota', 'noun', "son's son", 2, 'common', '🧑‍🍼',
       'ਪੋਤਾ ਦਾਦੇ ਵਰਗਾ ਲੱਗਦਾ ਹੈ।', 'pota daade varga laggda hai.'],
      ['ਨਾਨਕੇ', 'naanke', 'noun', "mother's parental village", 3, 'common', '🚩',
       'ਗਰਮੀਆਂ ਵਿੱਚ ਨਾਨਕੇ ਜਾਈਦਾ ਸੀ।', 'garmiaan vich naanke jaaeeda si.']
    ],

    /* ── ਭਾਵਨਾ · EMOTION ──────────────────────────── */
    emotion: [
      ['ਖ਼ੁਸ਼ੀ', 'khushi', 'noun', 'happiness', 1, 'common', '😄',
       'ਘਰ ਵਿੱਚ ਖ਼ੁਸ਼ੀ ਦਾ ਮਾਹੌਲ ਹੈ।', 'ghar vich khushi da maahaul hai.'],
      ['ਦੁੱਖ', 'dukkh', 'noun', 'sorrow, pain', 1, 'common', '😢',
       'ਉਹਦਾ ਦੁੱਖ ਸਮਝ ਆਉਂਦਾ ਹੈ।', 'ohda dukkh samajh aaunda hai.'],
      ['ਮੋਹ', 'moh', 'noun', 'affection, attachment', 2, 'common', '💛',
       'ਮਾਂ ਦਾ ਮੋਹ ਬੜਾ ਡੂੰਘਾ ਹੁੰਦਾ ਹੈ।', 'maan da moh barhaa doongha hunda hai.'],
      ['ਗੁੱਸਾ', 'gussa', 'noun', 'anger', 1, 'common', '😠',
       'ਬਾਪੂ ਨੂੰ ਗੁੱਸਾ ਆ ਗਿਆ।', 'baapu nu gussa aa giaa.'],
      ['ਡਰ', 'dar', 'noun', 'fear', 1, 'common', '😨',
       'ਹਨੇਰੇ ਤੋਂ ਡਰ ਲੱਗਦਾ ਹੈ।', 'hanere ton dar laggda hai.'],
      ['ਹਾਸਾ', 'haasa', 'noun', 'laughter', 1, 'common', '😂',
       'ਸਾਰੇ ਪਾਸੇ ਹਾਸਾ ਪੈ ਗਿਆ।', 'saare paase haasa pai giaa.'],
      ['ਰੋਣਾ', 'rona', 'verb', 'to cry', 1, 'common', '😭',
       'ਨਿਆਣਾ ਰੋਣ ਲੱਗ ਪਿਆ।', 'niaana ron lagg piaa.'],
      ['ਸ਼ਰਮ', 'sharam', 'noun', 'shyness, shame', 2, 'common', '😳',
       'ਉਹਨੂੰ ਸ਼ਰਮ ਆ ਗਈ।', 'ohnu sharam aa gaee.'],
      ['ਹੌਸਲਾ', 'hausla', 'noun', 'courage, morale', 2, 'common', '💪',
       'ਹੌਸਲਾ ਨਾ ਹਾਰ।', 'hausla naa haar.'],
      ['ਉਦਾਸੀ', 'udaasi', 'noun', 'sadness, gloom', 2, 'common', '😔',
       'ਚਿਹਰੇ ਤੇ ਉਦਾਸੀ ਛਾਈ ਹੋਈ ਸੀ।', 'chehre te udaasi chhaaee hoee si.'],
      ['ਚਾਅ', 'chaa', 'noun', 'eager delight, longing', 3, 'common', '🤩',
       'ਵਿਆਹ ਦਾ ਬੜਾ ਚਾਅ ਹੈ।', 'viaah da barhaa chaa hai.'],
      ['ਤਾਂਘ', 'taangh', 'noun', 'yearning', 3, 'common', '🥺',
       'ਪਿੰਡ ਦੀ ਤਾਂਘ ਲੱਗੀ ਰਹਿੰਦੀ ਹੈ।', 'pind di taangh laggi rehndi hai.'],
      ['ਹੇਰਵਾ', 'herva', 'noun', 'ache of separation, homesickness', 3, 'majhi', '💔',
       'ਪਰਦੇਸ ਵਿੱਚ ਹੇਰਵਾ ਵੱਢ ਵੱਢ ਖਾਂਦਾ ਹੈ।', 'pardes vich herva vaddh vaddh khaanda hai.'],
      ['ਸਬਰ', 'sabar', 'noun', 'patience, forbearance', 2, 'common', '🧘',
       'ਸਬਰ ਰੱਖ, ਸਭ ਠੀਕ ਹੋਊ।', 'sabar rakkh, sabh theek hoo.'],
      ['ਈਰਖਾ', 'eerkha', 'noun', 'envy', 3, 'common', '😒',
       'ਈਰਖਾ ਬੰਦੇ ਨੂੰ ਖਾ ਜਾਂਦੀ ਹੈ।', 'eerkha bande nu khaa jaandi hai.'],
      ['ਮਾਣ', 'maan', 'noun', 'pride, honour', 2, 'common', '🎖️',
       'ਸਾਨੂੰ ਤੇਰੇ ਤੇ ਮਾਣ ਹੈ।', 'saanu tere te maan hai.'],
      ['ਲਾਡ', 'laad', 'noun', 'pampering affection', 2, 'common', '🤗',
       'ਨਿਆਣਿਆਂ ਨੂੰ ਬੜਾ ਲਾਡ ਕਰਦੀ ਹੈ।', 'niaaniaan nu barhaa laad kardi hai.'],
      ['ਤਰਸ', 'taras', 'noun', 'pity, compassion', 2, 'common', '🕊️',
       'ਮੈਨੂੰ ਉਹਦੇ ਤੇ ਤਰਸ ਆਇਆ।', 'mainu ohde te taras aaiaa.'],
      ['ਥਕੇਵਾਂ', 'thakevaan', 'noun', 'tiredness', 2, 'malwai', '😩',
       'ਸਾਰੇ ਦਿਨ ਦਾ ਥਕੇਵਾਂ ਲਹਿ ਗਿਆ।', 'saare din da thakevaan leh giaa.'],
      ['ਸੁੱਖ', 'sukkh', 'noun', 'ease, wellbeing', 2, 'common', '☮️',
       'ਰੱਬ ਸੁੱਖ ਰੱਖੇ।', 'rabb sukkh rakkhe.'],
      ['ਫ਼ਿਕਰ', 'fikar', 'noun', 'worry', 2, 'common', '😟',
       'ਫ਼ਿਕਰ ਨਾ ਕਰ।', 'fikar naa kar.'],
      ['ਹਿੰਮਤ', 'himmat', 'noun', 'grit, resolve', 2, 'common', '🔥',
       'ਹਿੰਮਤ ਕਰ, ਹੋ ਜਾਊ।', 'himmat kar, ho jaoo.'],
      ['ਨਿਮਰਤਾ', 'nimarta', 'noun', 'humility', 3, 'common', '🙏',
       'ਨਿਮਰਤਾ ਵੱਡੀ ਚੀਜ਼ ਹੈ।', 'nimarta vaddi cheez hai.'],
      ['ਗਿਲਾ', 'gila', 'noun', 'grievance, complaint', 3, 'common', '😤',
       'ਮੈਨੂੰ ਤੇਰੇ ਨਾਲ ਕੋਈ ਗਿਲਾ ਨਹੀਂ।', 'mainu tere naal koee gila naheen.'],
      ['ਧਰਵਾਸ', 'dharvaas', 'noun', 'consolation, reassurance', 3, 'majhi', '🫂',
       'ਉਹਨੇ ਮੈਨੂੰ ਧਰਵਾਸ ਦਿੱਤਾ।', 'ohne mainu dharvaas dittaa.'],
      ['ਅਸੀਸ', 'asees', 'noun', 'blessing', 2, 'common', '🙌',
       'ਵੱਡਿਆਂ ਦੀ ਅਸੀਸ ਲੈ।', 'vaddiaan di asees lai.'],
      ['ਰੌਣਕ', 'raunak', 'noun', 'liveliness, festive bustle', 2, 'common', '🎉',
       'ਵਿਆਹ ਵਾਲੇ ਘਰ ਰੌਣਕ ਹੈ।', 'viaah vaale ghar raunak hai.'],
      ['ਪਿਆਰ', 'piaar', 'noun', 'love', 1, 'common', '❤️',
       'ਪਿਆਰ ਨਾਲ ਬੋਲ।', 'piaar naal bol.'],
      ['ਨਫ਼ਰਤ', 'nafrat', 'noun', 'hatred', 2, 'common', '🚫',
       'ਨਫ਼ਰਤ ਕਿਸੇ ਦਾ ਭਲਾ ਨਹੀਂ ਕਰਦੀ।', 'nafrat kise da bhalaa naheen kardi.'],
      ['ਯਾਦ', 'yaad', 'noun', 'memory, remembrance', 1, 'common', '🧠',
       'ਪਿੰਡ ਦੀ ਯਾਦ ਆਉਂਦੀ ਹੈ।', 'pind di yaad aaundi hai.'],
      ['ਭਰੋਸਾ', 'bharosa', 'noun', 'trust', 2, 'common', '🤞',
       'ਮੈਨੂੰ ਤੇਰੇ ਤੇ ਭਰੋਸਾ ਹੈ।', 'mainu tere te bharosa hai.'],
      ['ਹੈਰਾਨੀ', 'hairaani', 'noun', 'surprise', 2, 'common', '😲',
       'ਸੁਣ ਕੇ ਹੈਰਾਨੀ ਹੋਈ।', 'sun ke hairaani hoee.'],
      ['ਪਛਤਾਵਾ', 'pachhtaava', 'noun', 'regret', 3, 'common', '😞',
       'ਹੁਣ ਪਛਤਾਵਾ ਕੀ ਕਰਨਾ।', 'hun pachhtaava ki karna.'],
      ['ਬੇਚੈਨੀ', 'bechaini', 'noun', 'restlessness', 3, 'common', '😖',
       'ਸਾਰੀ ਰਾਤ ਬੇਚੈਨੀ ਰਹੀ।', 'saari raat bechaini rahi.'],
      ['ਸ਼ੁਕਰ', 'shukar', 'noun', 'gratitude', 2, 'common', '🤝',
       'ਰੱਬ ਦਾ ਸ਼ੁਕਰ ਹੈ।', 'rabb da shukar hai.'],
      ['ਗ਼ਮ', 'gham', 'noun', 'grief', 2, 'common', '🖤',
       'ਗ਼ਮ ਵੰਡਿਆਂ ਘਟਦਾ ਹੈ।', 'gham vandiaan ghatda hai.'],
      ['ਖਿਝ', 'khijh', 'noun', 'irritation', 3, 'malwai', '😤',
       'ਮੈਨੂੰ ਬੜੀ ਖਿਝ ਆਉਂਦੀ ਹੈ।', 'mainu barhi khijh aaundi hai.'],
      ['ਤਸੱਲੀ', 'tasalli', 'noun', 'satisfaction, relief', 3, 'common', '😌',
       'ਹੁਣ ਤਸੱਲੀ ਹੋ ਗਈ।', 'hun tasalli ho gaee.'],
      ['ਉਮੀਦ', 'umeed', 'noun', 'hope', 2, 'common', '🌈',
       'ਉਮੀਦ ਨਾ ਛੱਡ।', 'umeed naa chhadd.'],
      ['ਇਕੱਲ', 'ikall', 'noun', 'loneliness', 3, 'common', '🕯️',
       'ਇਕੱਲ ਖਾਣ ਨੂੰ ਆਉਂਦੀ ਹੈ।', 'ikall khaan nu aaundi hai.'],
      ['ਸ਼ੌਕ', 'shauk', 'noun', 'keen interest, hobby', 2, 'common', '🎨',
       'ਉਹਨੂੰ ਗਾਉਣ ਦਾ ਸ਼ੌਕ ਹੈ।', 'ohnu gaaun da shauk hai.'],
      ['ਜੋਸ਼', 'josh', 'noun', 'zeal, fervour', 2, 'common', '⚡',
       'ਮੁੰਡਿਆਂ ਵਿੱਚ ਬੜਾ ਜੋਸ਼ ਸੀ।', 'mundiaan vich barhaa josh si.'],
      ['ਅਣਖ', 'anakh', 'noun', 'self-respect, honour', 3, 'malwai', '🛡️',
       'ਅਣਖ ਨਾਲ ਜਿਊਣਾ ਸਿੱਖ।', 'anakh naal jiuna sikh.'],
      ['ਦਿਲਾਸਾ', 'dilaasa', 'noun', 'comfort, solace', 3, 'common', '🫂',
       'ਦੋ ਬੋਲ ਦਿਲਾਸੇ ਦੇ ਬੋਲ ਦੇ।', 'do bol dilaase de bol de.'],
      ['ਬੇਸਬਰੀ', 'besabri', 'noun', 'impatience', 3, 'common', '⏳',
       'ਬੇਸਬਰੀ ਨਾਲ ਉਡੀਕ ਰਿਹਾ ਸੀ।', 'besabri naal udeek rihaa si.']
    ],

    /* ── ਸਮਾਂ · TIME ──────────────────────────────── */
    time: [
      ['ਸਵੇਰ', 'saver', 'noun', 'morning', 1, 'common', '🌅',
       'ਸਵੇਰੇ ਜਲਦੀ ਉੱਠੀਂ।', 'savere jaldi utthheen.'],
      ['ਦੁਪਹਿਰ', 'dupehar', 'noun', 'afternoon', 1, 'common', '🌞',
       'ਦੁਪਹਿਰ ਨੂੰ ਬੜੀ ਗਰਮੀ ਸੀ।', 'dupehar nu barhi garmi si.'],
      ['ਸ਼ਾਮ', 'shaam', 'noun', 'evening', 1, 'common', '🌇',
       'ਸ਼ਾਮ ਨੂੰ ਮਿਲਦੇ ਹਾਂ।', 'shaam nu milde haan.'],
      ['ਰਾਤ', 'raat', 'noun', 'night', 1, 'common', '🌃',
       'ਰਾਤ ਨੂੰ ਮੀਂਹ ਪਿਆ।', 'raat nu meenh piaa.'],
      ['ਅੱਜ', 'ajj', 'adv', 'today', 1, 'common', '📌',
       'ਅੱਜ ਛੁੱਟੀ ਹੈ।', 'ajj chhutti hai.'],
      ['ਕੱਲ੍ਹ', 'kallh', 'adv', 'yesterday; tomorrow', 1, 'common', '🗓️',
       'ਕੱਲ੍ਹ ਆਵਾਂਗਾ।', 'kallh aavaanga.'],
      ['ਪਰਸੋਂ', 'parson', 'adv', 'day before yesterday / after tomorrow', 2, 'common', '📆',
       'ਪਰਸੋਂ ਪਿੰਡ ਜਾਣਾ ਹੈ।', 'parson pind jaana hai.'],
      ['ਵੇਲ਼ਾ', 'vela', 'noun', 'time, occasion', 2, 'common', '⏰',
       'ਵੇਲ਼ਾ ਸਿਰ ਪਹੁੰਚ ਜਾਈਂ।', 'vela sir pahunch jaaeen.'],
      ['ਸਿਆਲ਼', 'siaal', 'noun', 'winter', 2, 'common', '🥶',
       'ਸਿਆਲ਼ ਬੜਾ ਕੜਾਕੇ ਦਾ ਹੈ।', 'siaal barhaa karhaake da hai.'],
      ['ਹੁਨਾਲ਼', 'hunaal', 'noun', 'summer', 3, 'malwai', '🥵',
       'ਹੁਨਾਲ਼ ਵਿੱਚ ਲੂ ਵਗਦੀ ਹੈ।', 'hunaal vich loo vagdi hai.'],
      ['ਬਰਸਾਤ', 'barsaat', 'noun', 'rainy season', 2, 'common', '🌧️',
       'ਬਰਸਾਤ ਸ਼ੁਰੂ ਹੋ ਗਈ।', 'barsaat shuroo ho gaee.'],
      ['ਸਾਲ', 'saal', 'noun', 'year', 1, 'common', '📅',
       'ਸਾਲ ਲੰਘ ਗਿਆ।', 'saal langh giaa.'],
      ['ਮਹੀਨਾ', 'maheena', 'noun', 'month', 1, 'common', '🌗',
       'ਮਹੀਨਾ ਹੋ ਗਿਆ ਮਿਲਿਆਂ ਨੂੰ।', 'maheena ho giaa miliaan nu.'],
      ['ਹਫ਼ਤਾ', 'hafta', 'noun', 'week', 1, 'common', '7️⃣',
       'ਅਗਲੇ ਹਫ਼ਤੇ ਆਵਾਂਗਾ।', 'agle hafte aavaanga.'],
      ['ਦਿਨ', 'din', 'noun', 'day', 1, 'common', '☀️',
       'ਦਿਨ ਚੜ੍ਹ ਗਿਆ।', 'din charrh giaa.'],
      ['ਘੜੀ', 'gharhi', 'noun', 'moment; watch', 2, 'common', '⌚',
       'ਦੋ ਘੜੀਆਂ ਬਹਿ ਜਾ।', 'do gharhiaan beh ja.'],
      ['ਤੜਕੇ', 'tarhke', 'adv', 'at dawn, very early', 3, 'malwai', '🌄',
       'ਤੜਕੇ ਉੱਠ ਕੇ ਖੇਤ ਗਿਆ।', 'tarhke utth ke khet giaa.'],
      ['ਲੌਢਾ ਵੇਲ਼ਾ', 'laudha vela', 'noun', 'late afternoon', 3, 'malwai', '🌆',
       'ਲੌਢੇ ਵੇਲ਼ੇ ਮੁੜ ਆਈਂ।', 'laudhe vele murh aaeen.'],
      ['ਡੂੰਘੀ ਰਾਤ', 'doonghi raat', 'noun', 'deep night', 3, 'common', '🌌',
       'ਡੂੰਘੀ ਰਾਤ ਤੱਕ ਗੱਲਾਂ ਕਰਦੇ ਰਹੇ।', 'doonghi raat takk gallaan karde rahe.'],
      ['ਹੁਣ', 'hun', 'adv', 'now', 1, 'common', '⏱️',
       'ਹੁਣ ਚੱਲੀਏ।', 'hun challiye.'],
      ['ਫੇਰ', 'pher', 'adv', 'then, again, later', 1, 'common', '🔁',
       'ਫੇਰ ਮਿਲਾਂਗੇ।', 'pher milaange.'],
      ['ਛੇਤੀ', 'chheti', 'adv', 'quickly, soon', 1, 'common', '⚡',
       'ਛੇਤੀ ਕਰ।', 'chheti kar.'],
      ['ਦੇਰ', 'der', 'noun', 'delay, lateness', 1, 'common', '🐢',
       'ਬੜੀ ਦੇਰ ਹੋ ਗਈ।', 'barhi der ho gaee.'],
      ['ਸਦਾ', 'sada', 'adv', 'always, forever', 2, 'common', '♾️',
       'ਸਦਾ ਖ਼ੁਸ਼ ਰਹੁ।', 'sada khush rahu.'],
      ['ਕਦੇ', 'kade', 'adv', 'ever, sometime', 1, 'common', '❓',
       'ਕਦੇ ਪਿੰਡ ਵੀ ਆ ਜਾਇਆ ਕਰ।', 'kade pind vi aa jaaiaa kar.'],
      ['ਪਹਿਲਾਂ', 'pehlaan', 'adv', 'before, earlier', 1, 'common', '⬅️',
       'ਪਹਿਲਾਂ ਰੋਟੀ ਖਾ ਲੈ।', 'pehlaan roti khaa lai.'],
      ['ਮਗਰੋਂ', 'magron', 'adv', 'afterwards', 2, 'malwai', '➡️',
       'ਮਗਰੋਂ ਗੱਲ ਕਰਾਂਗੇ।', 'magron gall karaange.'],
      ['ਪਲ', 'pal', 'noun', 'moment', 2, 'common', '⚡',
       'ਦੋ ਪਲ ਰੁਕ ਜਾ।', 'do pal ruk ja.'],
      ['ਉਮਰ', 'umar', 'noun', 'age, lifespan', 1, 'common', '🎂',
       'ਸਾਰੀ ਉਮਰ ਖੇਤਾਂ ਵਿੱਚ ਲੰਘ ਗਈ।', 'saari umar khetaan vich langh gaee.'],
      ['ਜਵਾਨੀ', 'javaani', 'noun', 'youth', 2, 'common', '🌱',
       'ਜਵਾਨੀ ਛੇਤੀ ਲੰਘ ਜਾਂਦੀ ਹੈ।', 'javaani chheti langh jaandi hai.'],
      ['ਬੁਢਾਪਾ', 'budhaapa', 'noun', 'old age', 2, 'common', '🦯',
       'ਬੁਢਾਪਾ ਆ ਗਿਆ।', 'budhaapa aa giaa.'],
      ['ਸਦੀ', 'sadi', 'noun', 'century', 3, 'common', '🏛️',
       'ਸਦੀ ਬੀਤ ਗਈ।', 'sadi beet gaee.'],
      ['ਵਾਰੀ', 'vaari', 'noun', 'turn, occasion', 2, 'common', '🔄',
       'ਹੁਣ ਤੇਰੀ ਵਾਰੀ ਹੈ।', 'hun teri vaari hai.'],
      ['ਹਮੇਸ਼ਾ', 'hamesha', 'adv', 'always', 1, 'common', '🔒',
       'ਹਮੇਸ਼ਾ ਸੱਚ ਬੋਲ।', 'hamesha sach bol.'],
      ['ਕਦੇ ਕਦੇ', 'kade kade', 'adv', 'occasionally', 2, 'common', '🎲',
       'ਕਦੇ ਕਦੇ ਮਿਲ ਲਿਆ ਕਰ।', 'kade kade mil liaa kar.'],
      ['ਅਜੇ', 'aje', 'adv', 'still, yet', 1, 'common', '⌛',
       'ਅਜੇ ਨਹੀਂ ਆਇਆ।', 'aje naheen aaiaa.'],
      ['ਹੁਣੇ', 'hune', 'adv', 'just now', 1, 'common', '📍',
       'ਉਹ ਹੁਣੇ ਗਿਆ ਹੈ।', 'oh hune giaa hai.'],
      ['ਸਵੱਖਤੇ', 'savakhte', 'adv', 'early in the morning', 3, 'malwai', '🌄',
       'ਸਵੱਖਤੇ ਉੱਠ ਕੇ ਤੁਰ ਪਿਆ।', 'savakhte utth ke tur piaa.'],
      ['ਆਥਣ', 'aathan', 'noun', 'dusk, evening', 3, 'malwai', '🌒',
       'ਆਥਣ ਵੇਲ਼ੇ ਡੰਗਰ ਮੁੜਦੇ ਨੇ।', 'aathan vele dangar murhde ne.'],
      ['ਪਹੁ ਫੁਟਾਲਾ', 'pahu phutaala', 'noun', 'daybreak', 3, 'common', '🔆',
       'ਪਹੁ ਫੁਟਾਲੇ ਨਾਲ ਹੀ ਨਿਕਲ ਪਏ।', 'pahu phutaale naal hi nikal pae.'],
      ['ਅੱਧੀ ਰਾਤ', 'addhi raat', 'noun', 'midnight', 2, 'common', '🌚',
       'ਅੱਧੀ ਰਾਤ ਨੂੰ ਮੀਂਹ ਪਿਆ।', 'addhi raat nu meenh piaa.'],
      ['ਤਿਉਹਾਰ', 'tiuhaar', 'noun', 'festival', 1, 'common', '🎊',
       'ਤਿਉਹਾਰ ਤੇ ਸਾਰੇ ਜੁੜਦੇ ਨੇ।', 'tiuhaar te saare jurhde ne.'],
      ['ਵਿਸਾਖੀ', 'visaakhi', 'noun', 'Vaisakhi, harvest festival', 2, 'common', '🥁',
       'ਵਿਸਾਖੀ ਤੇ ਮੇਲਾ ਲੱਗਦਾ ਹੈ।', 'visaakhi te mela laggda hai.'],
      ['ਲੋਹੜੀ', 'lohrhi', 'noun', 'Lohri, midwinter festival', 2, 'common', '🕯️',
       'ਲੋਹੜੀ ਦੀ ਅੱਗ ਬਾਲ਼ੀ।', 'lohrhi di agg baali.'],
      ['ਮੇਲਾ', 'mela', 'noun', 'fair, gathering', 1, 'common', '🎡',
       'ਪਿੰਡ ਵਿੱਚ ਮੇਲਾ ਲੱਗਿਆ ਹੈ।', 'pind vich mela laggiaa hai.']
    ]
  };

  /* ── Expand tuples into full records ─────────────── */
  var WORDS = [];
  Object.keys(RAW).forEach(function (category) {
    RAW[category].forEach(function (t, i) {
      WORDS.push({
        id: category + '-' + String(i + 1).padStart(3, '0'),
        gurmukhi: t[0],
        latin: t[1],
        pos: t[2],
        meaning: t[3],
        category: category,
        tier: t[4],
        dialect: t[5],
        emoji: t[6],
        example: { gurmukhi: t[7], latin: t[8] },
        status: 'verified',
        source: 'seed'
      });
    });
  });

  global.VOCAB = WORDS;
  global.VOCAB_CATEGORIES = CATEGORIES;
  global.VOCAB_DIALECTS = DIALECTS;
  global.VOCAB_TIERS = TIERS;

})(window);
