/* ══════════════════════════════════════════════════
   Punjabi Vocabulary Database — 200 Entries
   Categories: home | farm | nature | body | food | kinship | emotion | time
   ══════════════════════════════════════════════════ */

const VOCABULARY = [
  // ── HOME (1-25) ──
  { id:1, gurmukhi:"ਘਰ", latin:"ghar", pos:"noun", meaning:"house", category:"home", example:{ gurmukhi:"ਸਾਡਾ ਘਰ ਬਹੁਤ ਵੱਡਾ ਹੈ", latin:"saada ghar bahut vadda hai" }},
  { id:2, gurmukhi:"ਦਰਵਾਜ਼ਾ", latin:"darvaaza", pos:"noun", meaning:"door", category:"home", example:{ gurmukhi:"ਦਰਵਾਜ਼ਾ ਬੰਦ ਕਰੋ", latin:"darvaaza band karo" }},
  { id:3, gurmukhi:"ਖਿੜਕੀ", latin:"khidki", pos:"noun", meaning:"window", category:"home", example:{ gurmukhi:"ਖਿੜਕੀ ਖੋਲ੍ਹੋ", latin:"khidki kholho" }},
  { id:4, gurmukhi:"ਕੰਧ", latin:"kandh", pos:"noun", meaning:"wall", category:"home", example:{ gurmukhi:"ਕੰਧ ਉੱਤੇ ਤਸਵੀਰ ਹੈ", latin:"kandh utte tasveer hai" }},
  { id:5, gurmukhi:"ਛੱਤ", latin:"chhat", pos:"noun", meaning:"roof", category:"home", example:{ gurmukhi:"ਛੱਤ ਤੋਂ ਪਾਣੀ ਆ ਰਿਹਾ ਹੈ", latin:"chhat ton paani aa riha hai" }},
  { id:6, gurmukhi:"ਕਮਰਾ", latin:"kamra", pos:"noun", meaning:"room", category:"home", example:{ gurmukhi:"ਇਹ ਮੇਰਾ ਕਮਰਾ ਹੈ", latin:"ih mera kamra hai" }},
  { id:7, gurmukhi:"ਰਸੋਈ", latin:"rasoi", pos:"noun", meaning:"kitchen", category:"home", example:{ gurmukhi:"ਮਾਂ ਰਸੋਈ ਵਿੱਚ ਹੈ", latin:"maan rasoi vich hai" }},
  { id:8, gurmukhi:"ਮੰਜਾ", latin:"manja", pos:"noun", meaning:"cot/bed", category:"home", example:{ gurmukhi:"ਮੰਜੇ ਉੱਤੇ ਬੈਠੋ", latin:"manje utte baitho" }},
  { id:9, gurmukhi:"ਕੁਰਸੀ", latin:"kursi", pos:"noun", meaning:"chair", category:"home", example:{ gurmukhi:"ਕੁਰਸੀ ਉੱਤੇ ਬੈਠੋ", latin:"kursi utte baitho" }},
  { id:10, gurmukhi:"ਮੇਜ਼", latin:"mez", pos:"noun", meaning:"table", category:"home", example:{ gurmukhi:"ਕਿਤਾਬ ਮੇਜ਼ ਉੱਤੇ ਹੈ", latin:"kitaab mez utte hai" }},
  { id:11, gurmukhi:"ਸ਼ੀਸ਼ਾ", latin:"sheesha", pos:"noun", meaning:"mirror", category:"home", example:{ gurmukhi:"ਸ਼ੀਸ਼ੇ ਵਿੱਚ ਵੇਖੋ", latin:"sheeshe vich vekho" }},
  { id:12, gurmukhi:"ਪੱਖਾ", latin:"pakkha", pos:"noun", meaning:"fan", category:"home", example:{ gurmukhi:"ਪੱਖਾ ਚਾਲੂ ਕਰੋ", latin:"pakkha chaalu karo" }},
  { id:13, gurmukhi:"ਬੱਤੀ", latin:"batti", pos:"noun", meaning:"light/lamp", category:"home", example:{ gurmukhi:"ਬੱਤੀ ਬੰਦ ਕਰੋ", latin:"batti band karo" }},
  { id:14, gurmukhi:"ਤਾਲਾ", latin:"taala", pos:"noun", meaning:"lock", category:"home", example:{ gurmukhi:"ਦਰਵਾਜ਼ੇ ਨੂੰ ਤਾਲਾ ਲਾਓ", latin:"darvaaze noon taala laao" }},
  { id:15, gurmukhi:"ਚਾਬੀ", latin:"chaabi", pos:"noun", meaning:"key", category:"home", example:{ gurmukhi:"ਚਾਬੀ ਕਿੱਥੇ ਹੈ", latin:"chaabi kitthe hai" }},
  { id:16, gurmukhi:"ਵਿਹੜਾ", latin:"vihra", pos:"noun", meaning:"courtyard", category:"home", example:{ gurmukhi:"ਬੱਚੇ ਵਿਹੜੇ ਵਿੱਚ ਖੇਡਦੇ ਹਨ", latin:"bachche vihre vich khedde han" }},
  { id:17, gurmukhi:"ਪੌੜੀ", latin:"paudi", pos:"noun", meaning:"stairs", category:"home", example:{ gurmukhi:"ਪੌੜੀਆਂ ਚੜ੍ਹੋ", latin:"paudiaan chadho" }},
  { id:18, gurmukhi:"ਅਲਮਾਰੀ", latin:"almaari", pos:"noun", meaning:"cupboard", category:"home", example:{ gurmukhi:"ਕੱਪੜੇ ਅਲਮਾਰੀ ਵਿੱਚ ਰੱਖੋ", latin:"kappde almaari vich rakkho" }},
  { id:19, gurmukhi:"ਝਾੜੂ", latin:"jhaadu", pos:"noun", meaning:"broom", category:"home", example:{ gurmukhi:"ਝਾੜੂ ਲਾਓ", latin:"jhaadu laao" }},
  { id:20, gurmukhi:"ਬਾਲਟੀ", latin:"baalti", pos:"noun", meaning:"bucket", category:"home", example:{ gurmukhi:"ਬਾਲਟੀ ਵਿੱਚ ਪਾਣੀ ਭਰੋ", latin:"baalti vich paani bharo" }},
  { id:21, gurmukhi:"ਸਾਬਣ", latin:"saaban", pos:"noun", meaning:"soap", category:"home", example:{ gurmukhi:"ਸਾਬਣ ਨਾਲ ਹੱਥ ਧੋਵੋ", latin:"saaban naal hatth dhovo" }},
  { id:22, gurmukhi:"ਤੌਲੀਆ", latin:"taulia", pos:"noun", meaning:"towel", category:"home", example:{ gurmukhi:"ਤੌਲੀਆ ਲਿਆਓ", latin:"taulia liaao" }},
  { id:23, gurmukhi:"ਚੁੱਲ੍ਹਾ", latin:"chullha", pos:"noun", meaning:"stove/hearth", category:"home", example:{ gurmukhi:"ਚੁੱਲ੍ਹਾ ਬਾਲੋ", latin:"chullha baalo" }},
  { id:24, gurmukhi:"ਸਿਰਹਾਣਾ", latin:"sirhaana", pos:"noun", meaning:"pillow", category:"home", example:{ gurmukhi:"ਸਿਰਹਾਣਾ ਨਰਮ ਹੈ", latin:"sirhaana naram hai" }},
  { id:25, gurmukhi:"ਚਾਦਰ", latin:"chaadar", pos:"noun", meaning:"bedsheet", category:"home", example:{ gurmukhi:"ਨਵੀਂ ਚਾਦਰ ਵਿਛਾਓ", latin:"naveen chaadar vichhaao" }},
  // ── FARM (26-50) ──
  { id:26, gurmukhi:"ਖੇਤ", latin:"khet", pos:"noun", meaning:"field", category:"farm", example:{ gurmukhi:"ਖੇਤ ਵਿੱਚ ਕਣਕ ਹੈ", latin:"khet vich kanak hai" }},
  { id:27, gurmukhi:"ਹਲ", latin:"hal", pos:"noun", meaning:"plough", category:"farm", example:{ gurmukhi:"ਕਿਸਾਨ ਹਲ ਚਲਾਉਂਦਾ ਹੈ", latin:"kisaan hal chalaunda hai" }},
  { id:28, gurmukhi:"ਕਿਸਾਨ", latin:"kisaan", pos:"noun", meaning:"farmer", category:"farm", example:{ gurmukhi:"ਕਿਸਾਨ ਮਿਹਨਤੀ ਹੈ", latin:"kisaan mihnati hai" }},
  { id:29, gurmukhi:"ਬੀਜ", latin:"beej", pos:"noun", meaning:"seed", category:"farm", example:{ gurmukhi:"ਬੀਜ ਬੀਜੋ", latin:"beej beejo" }},
  { id:30, gurmukhi:"ਫ਼ਸਲ", latin:"fasal", pos:"noun", meaning:"crop", category:"farm", example:{ gurmukhi:"ਫ਼ਸਲ ਚੰਗੀ ਹੋਈ ਹੈ", latin:"fasal changi hoee hai" }},
  { id:31, gurmukhi:"ਕਣਕ", latin:"kanak", pos:"noun", meaning:"wheat", category:"farm", example:{ gurmukhi:"ਕਣਕ ਪੱਕ ਗਈ ਹੈ", latin:"kanak pakk gai hai" }},
  { id:32, gurmukhi:"ਝੋਨਾ", latin:"jhona", pos:"noun", meaning:"paddy/rice crop", category:"farm", example:{ gurmukhi:"ਝੋਨਾ ਲਾਉਣ ਦਾ ਵੇਲਾ ਹੈ", latin:"jhona laaun da vela hai" }},
  { id:33, gurmukhi:"ਟਰੈਕਟਰ", latin:"tractor", pos:"noun", meaning:"tractor", category:"farm", example:{ gurmukhi:"ਟਰੈਕਟਰ ਖੇਤ ਵਿੱਚ ਹੈ", latin:"tractor khet vich hai" }},
  { id:34, gurmukhi:"ਗਾਂ", latin:"gaaN", pos:"noun", meaning:"cow", category:"farm", example:{ gurmukhi:"ਗਾਂ ਦੁੱਧ ਦਿੰਦੀ ਹੈ", latin:"gaaN duddh dindi hai" }},
  { id:35, gurmukhi:"ਮੱਝ", latin:"majjh", pos:"noun", meaning:"buffalo", category:"farm", example:{ gurmukhi:"ਮੱਝ ਨਹਿਰ ਵਿੱਚ ਨਹਾਉਂਦੀ ਹੈ", latin:"majjh nehir vich nahaundi hai" }},
  { id:36, gurmukhi:"ਬਲਦ", latin:"balad", pos:"noun", meaning:"ox/bull", category:"farm", example:{ gurmukhi:"ਬਲਦ ਗੱਡੀ ਖਿੱਚਦਾ ਹੈ", latin:"balad gaddi khichda hai" }},
  { id:37, gurmukhi:"ਕੁੱਕੜ", latin:"kukkaD", pos:"noun", meaning:"rooster", category:"farm", example:{ gurmukhi:"ਕੁੱਕੜ ਸਵੇਰੇ ਬਾਂਗ ਦਿੰਦਾ ਹੈ", latin:"kukkaD savere baang dinda hai" }},
  { id:38, gurmukhi:"ਕੁੱਤਾ", latin:"kutta", pos:"noun", meaning:"dog", category:"farm", example:{ gurmukhi:"ਕੁੱਤਾ ਘਰ ਦੀ ਰਾਖੀ ਕਰਦਾ ਹੈ", latin:"kutta ghar di raakhi karda hai" }},
  { id:39, gurmukhi:"ਬੱਕਰੀ", latin:"bakkri", pos:"noun", meaning:"goat", category:"farm", example:{ gurmukhi:"ਬੱਕਰੀ ਘਾਹ ਖਾਂਦੀ ਹੈ", latin:"bakkri ghaah khaandi hai" }},
  { id:40, gurmukhi:"ਨਹਿਰ", latin:"nehir", pos:"noun", meaning:"canal", category:"farm", example:{ gurmukhi:"ਨਹਿਰ ਵਿੱਚ ਪਾਣੀ ਵਗਦਾ ਹੈ", latin:"nehir vich paani vagda hai" }},
  { id:41, gurmukhi:"ਖੂਹ", latin:"khooh", pos:"noun", meaning:"well", category:"farm", example:{ gurmukhi:"ਖੂਹ ਵਿੱਚੋਂ ਪਾਣੀ ਕੱਢੋ", latin:"khooh vichon paani kaddho" }},
  { id:42, gurmukhi:"ਵਾਢੀ", latin:"vaadhi", pos:"noun", meaning:"harvest", category:"farm", example:{ gurmukhi:"ਵਾਢੀ ਦਾ ਮੌਸਮ ਆ ਗਿਆ", latin:"vaadhi da mausam aa gya" }},
  { id:43, gurmukhi:"ਦਾਤਰੀ", latin:"daatri", pos:"noun", meaning:"sickle", category:"farm", example:{ gurmukhi:"ਦਾਤਰੀ ਨਾਲ ਕਣਕ ਵੱਢੋ", latin:"daatri naal kanak vaddho" }},
  { id:44, gurmukhi:"ਪਿੰਡ", latin:"pind", pos:"noun", meaning:"village", category:"farm", example:{ gurmukhi:"ਸਾਡਾ ਪਿੰਡ ਸੋਹਣਾ ਹੈ", latin:"saada pind sohna hai" }},
  { id:45, gurmukhi:"ਖਾਦ", latin:"khaad", pos:"noun", meaning:"fertilizer", category:"farm", example:{ gurmukhi:"ਖੇਤ ਵਿੱਚ ਖਾਦ ਪਾਓ", latin:"khet vich khaad paao" }},
  { id:46, gurmukhi:"ਬਿਜਾਈ", latin:"bijaai", pos:"noun", meaning:"sowing", category:"farm", example:{ gurmukhi:"ਬਿਜਾਈ ਦਾ ਸਮਾਂ ਹੈ", latin:"bijaai da samaan hai" }},
  { id:47, gurmukhi:"ਮਿੱਟੀ", latin:"mitti", pos:"noun", meaning:"soil/earth", category:"farm", example:{ gurmukhi:"ਇਹ ਮਿੱਟੀ ਉਪਜਾਊ ਹੈ", latin:"ih mitti upjaoo hai" }},
  { id:48, gurmukhi:"ਘੋੜਾ", latin:"ghoda", pos:"noun", meaning:"horse", category:"farm", example:{ gurmukhi:"ਘੋੜਾ ਤੇਜ਼ ਦੌੜਦਾ ਹੈ", latin:"ghoda tez daurdaa hai" }},
  { id:49, gurmukhi:"ਤੂੜੀ", latin:"toodi", pos:"noun", meaning:"straw/chaff", category:"farm", example:{ gurmukhi:"ਤੂੜੀ ਦਾ ਗੱਠਾ ਬੰਨ੍ਹੋ", latin:"toodi da gattha bannho" }},
  { id:50, gurmukhi:"ਜ਼ਮੀਨ", latin:"zameen", pos:"noun", meaning:"land", category:"farm", example:{ gurmukhi:"ਸਾਡੀ ਜ਼ਮੀਨ ਪਿੰਡ ਵਿੱਚ ਹੈ", latin:"saadi zameen pind vich hai" }},
  // ── NATURE (51-75) ──
  { id:51, gurmukhi:"ਸੂਰਜ", latin:"sooraj", pos:"noun", meaning:"sun", category:"nature", example:{ gurmukhi:"ਸੂਰਜ ਚੜ੍ਹ ਗਿਆ", latin:"sooraj chadh gya" }},
  { id:52, gurmukhi:"ਚੰਦ", latin:"chand", pos:"noun", meaning:"moon", category:"nature", example:{ gurmukhi:"ਅੱਜ ਚੰਦ ਸੋਹਣਾ ਹੈ", latin:"ajj chand sohna hai" }},
  { id:53, gurmukhi:"ਤਾਰਾ", latin:"taara", pos:"noun", meaning:"star", category:"nature", example:{ gurmukhi:"ਅਸਮਾਨ ਵਿੱਚ ਤਾਰੇ ਚਮਕਦੇ ਹਨ", latin:"asmaan vich taare chamakde han" }},
  { id:54, gurmukhi:"ਮੀਂਹ", latin:"meenh", pos:"noun", meaning:"rain", category:"nature", example:{ gurmukhi:"ਮੀਂਹ ਪੈ ਰਿਹਾ ਹੈ", latin:"meenh pai riha hai" }},
  { id:55, gurmukhi:"ਹਵਾ", latin:"hava", pos:"noun", meaning:"wind/air", category:"nature", example:{ gurmukhi:"ਠੰਡੀ ਹਵਾ ਚੱਲ ਰਹੀ ਹੈ", latin:"thandi hava chall rahi hai" }},
  { id:56, gurmukhi:"ਦਰਿਆ", latin:"darya", pos:"noun", meaning:"river", category:"nature", example:{ gurmukhi:"ਦਰਿਆ ਵਿੱਚ ਪਾਣੀ ਬਹੁਤ ਹੈ", latin:"darya vich paani bahut hai" }},
  { id:57, gurmukhi:"ਪਹਾੜ", latin:"pahaad", pos:"noun", meaning:"mountain", category:"nature", example:{ gurmukhi:"ਪਹਾੜ ਬਹੁਤ ਉੱਚਾ ਹੈ", latin:"pahaad bahut uchcha hai" }},
  { id:58, gurmukhi:"ਰੁੱਖ", latin:"rukkh", pos:"noun", meaning:"tree", category:"nature", example:{ gurmukhi:"ਰੁੱਖ ਦੀ ਛਾਂ ਵਿੱਚ ਬੈਠੋ", latin:"rukkh di chhaan vich baitho" }},
  { id:59, gurmukhi:"ਫੁੱਲ", latin:"phull", pos:"noun", meaning:"flower", category:"nature", example:{ gurmukhi:"ਬਾਗ ਵਿੱਚ ਫੁੱਲ ਖਿੜੇ ਹਨ", latin:"baag vich phull khide han" }},
  { id:60, gurmukhi:"ਘਾਹ", latin:"ghaah", pos:"noun", meaning:"grass", category:"nature", example:{ gurmukhi:"ਘਾਹ ਹਰਾ ਹੈ", latin:"ghaah hara hai" }},
  { id:61, gurmukhi:"ਅਸਮਾਨ", latin:"asmaan", pos:"noun", meaning:"sky", category:"nature", example:{ gurmukhi:"ਅਸਮਾਨ ਨੀਲਾ ਹੈ", latin:"asmaan neela hai" }},
  { id:62, gurmukhi:"ਬੱਦਲ", latin:"baddal", pos:"noun", meaning:"cloud", category:"nature", example:{ gurmukhi:"ਬੱਦਲ ਛਾ ਗਏ ਹਨ", latin:"baddal chhaa gae han" }},
  { id:63, gurmukhi:"ਧੁੱਪ", latin:"dhupp", pos:"noun", meaning:"sunshine", category:"nature", example:{ gurmukhi:"ਬਾਹਰ ਧੁੱਪ ਹੈ", latin:"baahar dhupp hai" }},
  { id:64, gurmukhi:"ਛਾਂ", latin:"chhaan", pos:"noun", meaning:"shade", category:"nature", example:{ gurmukhi:"ਛਾਂ ਵਿੱਚ ਆਰਾਮ ਕਰੋ", latin:"chhaan vich aaraam karo" }},
  { id:65, gurmukhi:"ਪੱਤਾ", latin:"patta", pos:"noun", meaning:"leaf", category:"nature", example:{ gurmukhi:"ਪੱਤੇ ਡਿੱਗ ਰਹੇ ਹਨ", latin:"patte digg rahe han" }},
  { id:66, gurmukhi:"ਬਰਫ਼", latin:"baraf", pos:"noun", meaning:"snow/ice", category:"nature", example:{ gurmukhi:"ਪਹਾੜਾਂ ਉੱਤੇ ਬਰਫ਼ ਪਈ ਹੈ", latin:"pahaadaan utte baraf pai hai" }},
  { id:67, gurmukhi:"ਝੀਲ", latin:"jheel", pos:"noun", meaning:"lake", category:"nature", example:{ gurmukhi:"ਝੀਲ ਦਾ ਪਾਣੀ ਸਾਫ਼ ਹੈ", latin:"jheel da paani saaf hai" }},
  { id:68, gurmukhi:"ਪੰਛੀ", latin:"panchhi", pos:"noun", meaning:"bird", category:"nature", example:{ gurmukhi:"ਪੰਛੀ ਉੱਡ ਰਹੇ ਹਨ", latin:"panchhi udd rahe han" }},
  { id:69, gurmukhi:"ਮੱਛੀ", latin:"machhhi", pos:"noun", meaning:"fish", category:"nature", example:{ gurmukhi:"ਮੱਛੀ ਪਾਣੀ ਵਿੱਚ ਤਰਦੀ ਹੈ", latin:"machhhi paani vich tardi hai" }},
  { id:70, gurmukhi:"ਸੱਪ", latin:"sapp", pos:"noun", meaning:"snake", category:"nature", example:{ gurmukhi:"ਸੱਪ ਤੋਂ ਦੂਰ ਰਹੋ", latin:"sapp ton door raho" }},
  { id:71, gurmukhi:"ਜੰਗਲ", latin:"jangal", pos:"noun", meaning:"forest", category:"nature", example:{ gurmukhi:"ਜੰਗਲ ਸੰਘਣਾ ਹੈ", latin:"jangal sanghna hai" }},
  { id:72, gurmukhi:"ਨਦੀ", latin:"nadi", pos:"noun", meaning:"stream/river", category:"nature", example:{ gurmukhi:"ਨਦੀ ਵਿੱਚ ਪਾਣੀ ਵਗਦਾ ਹੈ", latin:"nadi vich paani vagda hai" }},
  { id:73, gurmukhi:"ਤਿਤਲੀ", latin:"titli", pos:"noun", meaning:"butterfly", category:"nature", example:{ gurmukhi:"ਤਿਤਲੀ ਫੁੱਲ ਉੱਤੇ ਬੈਠੀ ਹੈ", latin:"titli phull utte baithi hai" }},
  { id:74, gurmukhi:"ਮੋਰ", latin:"mor", pos:"noun", meaning:"peacock", category:"nature", example:{ gurmukhi:"ਮੋਰ ਨੱਚ ਰਿਹਾ ਹੈ", latin:"mor nachch riha hai" }},
  { id:75, gurmukhi:"ਧਰਤੀ", latin:"dharti", pos:"noun", meaning:"earth", category:"nature", example:{ gurmukhi:"ਧਰਤੀ ਗੋਲ ਹੈ", latin:"dharti gol hai" }},
  // ── BODY (76-100) ──
  { id:76, gurmukhi:"ਸਿਰ", latin:"sir", pos:"noun", meaning:"head", category:"body", example:{ gurmukhi:"ਸਿਰ ਦਰਦ ਹੋ ਰਿਹਾ ਹੈ", latin:"sir darad ho riha hai" }},
  { id:77, gurmukhi:"ਅੱਖ", latin:"akkh", pos:"noun", meaning:"eye", category:"body", example:{ gurmukhi:"ਅੱਖਾਂ ਬੰਦ ਕਰੋ", latin:"akkhaan band karo" }},
  { id:78, gurmukhi:"ਕੰਨ", latin:"kann", pos:"noun", meaning:"ear", category:"body", example:{ gurmukhi:"ਧਿਆਨ ਨਾਲ ਕੰਨ ਲਾ ਕੇ ਸੁਣੋ", latin:"dhiaan naal kann laa ke suno" }},
  { id:79, gurmukhi:"ਨੱਕ", latin:"nakk", pos:"noun", meaning:"nose", category:"body", example:{ gurmukhi:"ਨੱਕ ਵਗ ਰਿਹਾ ਹੈ", latin:"nakk vag riha hai" }},
  { id:80, gurmukhi:"ਮੂੰਹ", latin:"moonh", pos:"noun", meaning:"mouth/face", category:"body", example:{ gurmukhi:"ਮੂੰਹ ਧੋਵੋ", latin:"moonh dhovo" }},
  { id:81, gurmukhi:"ਦੰਦ", latin:"dand", pos:"noun", meaning:"tooth", category:"body", example:{ gurmukhi:"ਦੰਦ ਸਾਫ਼ ਕਰੋ", latin:"dand saaf karo" }},
  { id:82, gurmukhi:"ਜੀਭ", latin:"jeebh", pos:"noun", meaning:"tongue", category:"body", example:{ gurmukhi:"ਜੀਭ ਬਾਹਰ ਨਾ ਕੱਢੋ", latin:"jeebh baahar na kaddho" }},
  { id:83, gurmukhi:"ਹੱਥ", latin:"hatth", pos:"noun", meaning:"hand", category:"body", example:{ gurmukhi:"ਹੱਥ ਧੋ ਕੇ ਖਾਓ", latin:"hatth dho ke khaao" }},
  { id:84, gurmukhi:"ਉਂਗਲ", latin:"ungal", pos:"noun", meaning:"finger", category:"body", example:{ gurmukhi:"ਉਂਗਲ ਨਾ ਕਰੋ", latin:"ungal na karo" }},
  { id:85, gurmukhi:"ਪੈਰ", latin:"pair", pos:"noun", meaning:"foot/leg", category:"body", example:{ gurmukhi:"ਪੈਰ ਦੁਖਦਾ ਹੈ", latin:"pair dukhda hai" }},
  { id:86, gurmukhi:"ਗੋਡਾ", latin:"goda", pos:"noun", meaning:"knee", category:"body", example:{ gurmukhi:"ਗੋਡੇ ਵਿੱਚ ਦਰਦ ਹੈ", latin:"gode vich darad hai" }},
  { id:87, gurmukhi:"ਢਿੱਡ", latin:"dhidd", pos:"noun", meaning:"stomach/belly", category:"body", example:{ gurmukhi:"ਢਿੱਡ ਵਿੱਚ ਦਰਦ ਹੈ", latin:"dhidd vich darad hai" }},
  { id:88, gurmukhi:"ਛਾਤੀ", latin:"chhaati", pos:"noun", meaning:"chest", category:"body", example:{ gurmukhi:"ਛਾਤੀ ਚੌੜੀ ਕਰੋ", latin:"chhaati chaudi karo" }},
  { id:89, gurmukhi:"ਪਿੱਠ", latin:"pitth", pos:"noun", meaning:"back", category:"body", example:{ gurmukhi:"ਪਿੱਠ ਸਿੱਧੀ ਰੱਖੋ", latin:"pitth siddhi rakkho" }},
  { id:90, gurmukhi:"ਮੋਢਾ", latin:"modha", pos:"noun", meaning:"shoulder", category:"body", example:{ gurmukhi:"ਮੋਢੇ ਉੱਤੇ ਹੱਥ ਰੱਖੋ", latin:"modhe utte hatth rakkho" }},
  { id:91, gurmukhi:"ਗਲਾ", latin:"gala", pos:"noun", meaning:"throat/neck", category:"body", example:{ gurmukhi:"ਗਲਾ ਖ਼ਰਾਬ ਹੈ", latin:"gala kharaab hai" }},
  { id:92, gurmukhi:"ਵਾਲ", latin:"vaal", pos:"noun", meaning:"hair", category:"body", example:{ gurmukhi:"ਵਾਲ ਕਾਲੇ ਹਨ", latin:"vaal kaale han" }},
  { id:93, gurmukhi:"ਦਿਲ", latin:"dil", pos:"noun", meaning:"heart", category:"body", example:{ gurmukhi:"ਦਿਲ ਖੁਸ਼ ਹੈ", latin:"dil khush hai" }},
  { id:94, gurmukhi:"ਖ਼ੂਨ", latin:"khoon", pos:"noun", meaning:"blood", category:"body", example:{ gurmukhi:"ਖ਼ੂਨ ਲਾਲ ਹੁੰਦਾ ਹੈ", latin:"khoon laal hunda hai" }},
  { id:95, gurmukhi:"ਹੱਡੀ", latin:"haddi", pos:"noun", meaning:"bone", category:"body", example:{ gurmukhi:"ਹੱਡੀ ਮਜ਼ਬੂਤ ਹੈ", latin:"haddi mazboot hai" }},
  { id:96, gurmukhi:"ਚਮੜੀ", latin:"chamdi", pos:"noun", meaning:"skin", category:"body", example:{ gurmukhi:"ਚਮੜੀ ਨਰਮ ਹੈ", latin:"chamdi naram hai" }},
  { id:97, gurmukhi:"ਬੁੱਲ੍ਹ", latin:"bullh", pos:"noun", meaning:"lip", category:"body", example:{ gurmukhi:"ਬੁੱਲ੍ਹ ਸੁੱਕੇ ਹਨ", latin:"bullh sukke han" }},
  { id:98, gurmukhi:"ਦਾੜ੍ਹੀ", latin:"daadhi", pos:"noun", meaning:"beard", category:"body", example:{ gurmukhi:"ਦਾੜ੍ਹੀ ਲੰਮੀ ਹੈ", latin:"daadhi lammi hai" }},
  { id:99, gurmukhi:"ਨਹੁੰ", latin:"nahun", pos:"noun", meaning:"nail", category:"body", example:{ gurmukhi:"ਨਹੁੰ ਕੱਟੋ", latin:"nahun katto" }},
  { id:100, gurmukhi:"ਬਾਂਹ", latin:"baanh", pos:"noun", meaning:"arm", category:"body", example:{ gurmukhi:"ਬਾਂਹ ਫੜੋ", latin:"baanh phado" }},
  // ── FOOD (101-125) ──
  { id:101, gurmukhi:"ਰੋਟੀ", latin:"roti", pos:"noun", meaning:"bread/chapati", category:"food", example:{ gurmukhi:"ਰੋਟੀ ਗਰਮ ਖਾਓ", latin:"roti garam khaao" }},
  { id:102, gurmukhi:"ਦਾਲ", latin:"daal", pos:"noun", meaning:"lentils", category:"food", example:{ gurmukhi:"ਦਾਲ ਬਹੁਤ ਸੁਆਦ ਹੈ", latin:"daal bahut suaad hai" }},
  { id:103, gurmukhi:"ਚਾਵਲ", latin:"chaaval", pos:"noun", meaning:"rice", category:"food", example:{ gurmukhi:"ਚਾਵਲ ਪਕਾਓ", latin:"chaaval pakaao" }},
  { id:104, gurmukhi:"ਸਬਜ਼ੀ", latin:"sabzi", pos:"noun", meaning:"vegetable", category:"food", example:{ gurmukhi:"ਅੱਜ ਕਿਹੜੀ ਸਬਜ਼ੀ ਬਣਾਈ", latin:"ajj kihdi sabzi banaai" }},
  { id:105, gurmukhi:"ਮੱਖਣ", latin:"makkhan", pos:"noun", meaning:"butter", category:"food", example:{ gurmukhi:"ਰੋਟੀ ਉੱਤੇ ਮੱਖਣ ਲਾਓ", latin:"roti utte makkhan laao" }},
  { id:106, gurmukhi:"ਘਿਓ", latin:"ghio", pos:"noun", meaning:"ghee", category:"food", example:{ gurmukhi:"ਦਾਲ ਵਿੱਚ ਘਿਓ ਪਾਓ", latin:"daal vich ghio paao" }},
  { id:107, gurmukhi:"ਦੁੱਧ", latin:"duddh", pos:"noun", meaning:"milk", category:"food", example:{ gurmukhi:"ਗਰਮ ਦੁੱਧ ਪੀਓ", latin:"garam duddh peeo" }},
  { id:108, gurmukhi:"ਦਹੀਂ", latin:"daheen", pos:"noun", meaning:"yogurt", category:"food", example:{ gurmukhi:"ਦਹੀਂ ਖੱਟਾ ਹੈ", latin:"daheen khatta hai" }},
  { id:109, gurmukhi:"ਲੱਸੀ", latin:"lassi", pos:"noun", meaning:"buttermilk", category:"food", example:{ gurmukhi:"ਠੰਡੀ ਲੱਸੀ ਪੀਓ", latin:"thandi lassi peeo" }},
  { id:110, gurmukhi:"ਚਾਹ", latin:"chaah", pos:"noun", meaning:"tea", category:"food", example:{ gurmukhi:"ਚਾਹ ਬਣਾ ਦਿਓ", latin:"chaah bana dio" }},
  { id:111, gurmukhi:"ਪਾਣੀ", latin:"paani", pos:"noun", meaning:"water", category:"food", example:{ gurmukhi:"ਇੱਕ ਗਲਾਸ ਪਾਣੀ ਦਿਓ", latin:"ikk glass paani dio" }},
  { id:112, gurmukhi:"ਲੂਣ", latin:"loon", pos:"noun", meaning:"salt", category:"food", example:{ gurmukhi:"ਲੂਣ ਘੱਟ ਪਾਓ", latin:"loon ghatt paao" }},
  { id:113, gurmukhi:"ਮਿਰਚ", latin:"mirch", pos:"noun", meaning:"chili/pepper", category:"food", example:{ gurmukhi:"ਲਾਲ ਮਿਰਚ ਤਿੱਖੀ ਹੈ", latin:"laal mirch tikkhi hai" }},
  { id:114, gurmukhi:"ਹਲਦੀ", latin:"haldi", pos:"noun", meaning:"turmeric", category:"food", example:{ gurmukhi:"ਹਲਦੀ ਵਾਲਾ ਦੁੱਧ ਪੀਓ", latin:"haldi vaala duddh peeo" }},
  { id:115, gurmukhi:"ਆਟਾ", latin:"aata", pos:"noun", meaning:"flour", category:"food", example:{ gurmukhi:"ਆਟਾ ਗੁੰਨ੍ਹੋ", latin:"aata gunnho" }},
  { id:116, gurmukhi:"ਅਚਾਰ", latin:"achaar", pos:"noun", meaning:"pickle", category:"food", example:{ gurmukhi:"ਅੰਬ ਦਾ ਅਚਾਰ ਸੁਆਦ ਹੈ", latin:"amb da achaar suaad hai" }},
  { id:117, gurmukhi:"ਮਿੱਠਾ", latin:"mittha", pos:"adjective", meaning:"sweet", category:"food", example:{ gurmukhi:"ਇਹ ਬਹੁਤ ਮਿੱਠਾ ਹੈ", latin:"ih bahut mittha hai" }},
  { id:118, gurmukhi:"ਖੱਟਾ", latin:"khatta", pos:"adjective", meaning:"sour", category:"food", example:{ gurmukhi:"ਨਿੰਬੂ ਖੱਟਾ ਹੈ", latin:"nimboo khatta hai" }},
  { id:119, gurmukhi:"ਕੌੜਾ", latin:"kauda", pos:"adjective", meaning:"bitter", category:"food", example:{ gurmukhi:"ਕਰੇਲਾ ਕੌੜਾ ਹੁੰਦਾ ਹੈ", latin:"karela kauda hunda hai" }},
  { id:120, gurmukhi:"ਪਰਾਉਂਠਾ", latin:"parauntha", pos:"noun", meaning:"stuffed flatbread", category:"food", example:{ gurmukhi:"ਆਲੂ ਦਾ ਪਰਾਉਂਠਾ ਬਣਾਓ", latin:"aaloo da parauntha banaao" }},
  { id:121, gurmukhi:"ਸਾਗ", latin:"saag", pos:"noun", meaning:"mustard greens", category:"food", example:{ gurmukhi:"ਸਾਗ ਮੱਕੀ ਦੀ ਰੋਟੀ ਨਾਲ ਖਾਓ", latin:"saag makki di roti naal khaao" }},
  { id:122, gurmukhi:"ਜਲੇਬੀ", latin:"jalebi", pos:"noun", meaning:"jalebi (sweet)", category:"food", example:{ gurmukhi:"ਗਰਮ ਜਲੇਬੀ ਲਿਆਓ", latin:"garam jalebi liaao" }},
  { id:123, gurmukhi:"ਖੀਰ", latin:"kheer", pos:"noun", meaning:"rice pudding", category:"food", example:{ gurmukhi:"ਖੀਰ ਬਹੁਤ ਸੁਆਦ ਬਣੀ ਹੈ", latin:"kheer bahut suaad bani hai" }},
  { id:124, gurmukhi:"ਫ਼ਲ", latin:"fal", pos:"noun", meaning:"fruit", category:"food", example:{ gurmukhi:"ਫ਼ਲ ਖਾਣੇ ਚੰਗੇ ਹਨ", latin:"fal khaane change han" }},
  { id:125, gurmukhi:"ਮਸਾਲਾ", latin:"masaala", pos:"noun", meaning:"spice", category:"food", example:{ gurmukhi:"ਮਸਾਲਾ ਪਾ ਕੇ ਪਕਾਓ", latin:"masaala paa ke pakaao" }},
  // ── KINSHIP (126-150) ──
  { id:126, gurmukhi:"ਮਾਂ", latin:"maan", pos:"noun", meaning:"mother", category:"kinship", example:{ gurmukhi:"ਮਾਂ ਸਭ ਤੋਂ ਪਿਆਰੀ ਹੈ", latin:"maan sabh ton pyaari hai" }},
  { id:127, gurmukhi:"ਪਿਤਾ", latin:"pita", pos:"noun", meaning:"father", category:"kinship", example:{ gurmukhi:"ਪਿਤਾ ਜੀ ਕੰਮ ਤੇ ਗਏ ਹਨ", latin:"pita ji kamm te gae han" }},
  { id:128, gurmukhi:"ਭਰਾ", latin:"bhra", pos:"noun", meaning:"brother", category:"kinship", example:{ gurmukhi:"ਮੇਰਾ ਭਰਾ ਵੱਡਾ ਹੈ", latin:"mera bhra vadda hai" }},
  { id:129, gurmukhi:"ਭੈਣ", latin:"bhain", pos:"noun", meaning:"sister", category:"kinship", example:{ gurmukhi:"ਮੇਰੀ ਭੈਣ ਸੋਹਣੀ ਹੈ", latin:"meri bhain sohni hai" }},
  { id:130, gurmukhi:"ਪਤੀ", latin:"pati", pos:"noun", meaning:"husband", category:"kinship", example:{ gurmukhi:"ਮੇਰਾ ਪਤੀ ਚੰਗਾ ਹੈ", latin:"mera pati changa hai" }},
  { id:131, gurmukhi:"ਪਤਨੀ", latin:"patni", pos:"noun", meaning:"wife", category:"kinship", example:{ gurmukhi:"ਮੇਰੀ ਪਤਨੀ ਅਧਿਆਪਕ ਹੈ", latin:"meri patni adhiaapak hai" }},
  { id:132, gurmukhi:"ਪੁੱਤਰ", latin:"puttar", pos:"noun", meaning:"son", category:"kinship", example:{ gurmukhi:"ਪੁੱਤਰ ਸਕੂਲ ਗਿਆ ਹੈ", latin:"puttar school gya hai" }},
  { id:133, gurmukhi:"ਧੀ", latin:"dhee", pos:"noun", meaning:"daughter", category:"kinship", example:{ gurmukhi:"ਧੀ ਪੜ੍ਹਾਈ ਕਰ ਰਹੀ ਹੈ", latin:"dhee padhaai kar rahi hai" }},
  { id:134, gurmukhi:"ਦਾਦਾ", latin:"daada", pos:"noun", meaning:"paternal grandfather", category:"kinship", example:{ gurmukhi:"ਦਾਦਾ ਜੀ ਕਹਾਣੀ ਸੁਣਾਉਂਦੇ ਹਨ", latin:"daada ji kahaani sunaunde han" }},
  { id:135, gurmukhi:"ਦਾਦੀ", latin:"daadi", pos:"noun", meaning:"paternal grandmother", category:"kinship", example:{ gurmukhi:"ਦਾਦੀ ਜੀ ਪਿਆਰੀਆਂ ਹਨ", latin:"daadi ji pyaariaan han" }},
  { id:136, gurmukhi:"ਨਾਨਾ", latin:"naana", pos:"noun", meaning:"maternal grandfather", category:"kinship", example:{ gurmukhi:"ਨਾਨਾ ਜੀ ਪਿੰਡ ਵਿੱਚ ਰਹਿੰਦੇ ਹਨ", latin:"naana ji pind vich rehinde han" }},
  { id:137, gurmukhi:"ਨਾਨੀ", latin:"naani", pos:"noun", meaning:"maternal grandmother", category:"kinship", example:{ gurmukhi:"ਨਾਨੀ ਜੀ ਨੇ ਖੀਰ ਬਣਾਈ", latin:"naani ji ne kheer banaai" }},
  { id:138, gurmukhi:"ਚਾਚਾ", latin:"chaacha", pos:"noun", meaning:"paternal uncle", category:"kinship", example:{ gurmukhi:"ਚਾਚਾ ਜੀ ਘਰ ਆਏ ਹਨ", latin:"chaacha ji ghar aae han" }},
  { id:139, gurmukhi:"ਚਾਚੀ", latin:"chaachi", pos:"noun", meaning:"paternal aunt (uncle's wife)", category:"kinship", example:{ gurmukhi:"ਚਾਚੀ ਜੀ ਖਾਣਾ ਬਣਾ ਰਹੀ ਹੈ", latin:"chaachi ji khaana bana rahi hai" }},
  { id:140, gurmukhi:"ਮਾਮਾ", latin:"maama", pos:"noun", meaning:"maternal uncle", category:"kinship", example:{ gurmukhi:"ਮਾਮਾ ਜੀ ਸ਼ਹਿਰ ਤੋਂ ਆਏ ਹਨ", latin:"maama ji shehir ton aae han" }},
  { id:141, gurmukhi:"ਮਾਮੀ", latin:"maami", pos:"noun", meaning:"maternal aunt (uncle's wife)", category:"kinship", example:{ gurmukhi:"ਮਾਮੀ ਜੀ ਬਹੁਤ ਪਿਆਰੀ ਹੈ", latin:"maami ji bahut pyaari hai" }},
  { id:142, gurmukhi:"ਭੂਆ", latin:"bhooa", pos:"noun", meaning:"paternal aunt (father's sister)", category:"kinship", example:{ gurmukhi:"ਭੂਆ ਜੀ ਦਿੱਲੀ ਰਹਿੰਦੀ ਹੈ", latin:"bhooa ji dilli rehndi hai" }},
  { id:143, gurmukhi:"ਮਾਸੀ", latin:"maasi", pos:"noun", meaning:"maternal aunt (mother's sister)", category:"kinship", example:{ gurmukhi:"ਮਾਸੀ ਜੀ ਕੱਲ੍ਹ ਆਉਣਗੀਆਂ", latin:"maasi ji kallh aaungiaan" }},
  { id:144, gurmukhi:"ਸਹੁਰਾ", latin:"sahura", pos:"noun", meaning:"father-in-law", category:"kinship", example:{ gurmukhi:"ਸਹੁਰਾ ਜੀ ਸਤਿਕਾਰਯੋਗ ਹਨ", latin:"sahura ji satikaarayog han" }},
  { id:145, gurmukhi:"ਸੱਸ", latin:"sass", pos:"noun", meaning:"mother-in-law", category:"kinship", example:{ gurmukhi:"ਸੱਸ ਜੀ ਬਹੁਤ ਚੰਗੀ ਹੈ", latin:"sass ji bahut changi hai" }},
  { id:146, gurmukhi:"ਜੀਜਾ", latin:"jeeja", pos:"noun", meaning:"sister's husband", category:"kinship", example:{ gurmukhi:"ਜੀਜਾ ਜੀ ਡਾਕਟਰ ਹਨ", latin:"jeeja ji doctor han" }},
  { id:147, gurmukhi:"ਭਾਬੀ", latin:"bhaabi", pos:"noun", meaning:"brother's wife", category:"kinship", example:{ gurmukhi:"ਭਾਬੀ ਜੀ ਖਾਣਾ ਲਿਆਈ", latin:"bhaabi ji khaana liaai" }},
  { id:148, gurmukhi:"ਭਤੀਜਾ", latin:"bhateeja", pos:"noun", meaning:"nephew (brother's son)", category:"kinship", example:{ gurmukhi:"ਭਤੀਜਾ ਬਹੁਤ ਸ਼ਰਾਰਤੀ ਹੈ", latin:"bhateeja bahut sharaartee hai" }},
  { id:149, gurmukhi:"ਭਾਣਜਾ", latin:"bhaanja", pos:"noun", meaning:"nephew (sister's son)", category:"kinship", example:{ gurmukhi:"ਭਾਣਜਾ ਖੇਡ ਰਿਹਾ ਹੈ", latin:"bhaanja khed riha hai" }},
  { id:150, gurmukhi:"ਪਰਿਵਾਰ", latin:"parivaar", pos:"noun", meaning:"family", category:"kinship", example:{ gurmukhi:"ਸਾਡਾ ਪਰਿਵਾਰ ਵੱਡਾ ਹੈ", latin:"saada parivaar vadda hai" }},
  // ── EMOTION (151-175) ──
  { id:151, gurmukhi:"ਖ਼ੁਸ਼ੀ", latin:"khushi", pos:"noun", meaning:"happiness", category:"emotion", example:{ gurmukhi:"ਖ਼ੁਸ਼ੀ ਨਾਲ ਨੱਚੋ", latin:"khushi naal nachcho" }},
  { id:152, gurmukhi:"ਉਦਾਸ", latin:"udaas", pos:"adjective", meaning:"sad", category:"emotion", example:{ gurmukhi:"ਉਹ ਬਹੁਤ ਉਦਾਸ ਹੈ", latin:"oh bahut udaas hai" }},
  { id:153, gurmukhi:"ਗੁੱਸਾ", latin:"gussa", pos:"noun", meaning:"anger", category:"emotion", example:{ gurmukhi:"ਗੁੱਸਾ ਨਾ ਕਰੋ", latin:"gussa na karo" }},
  { id:154, gurmukhi:"ਪਿਆਰ", latin:"pyaar", pos:"noun", meaning:"love", category:"emotion", example:{ gurmukhi:"ਪਿਆਰ ਨਾਲ ਬੋਲੋ", latin:"pyaar naal bolo" }},
  { id:155, gurmukhi:"ਡਰ", latin:"dar", pos:"noun", meaning:"fear", category:"emotion", example:{ gurmukhi:"ਡਰ ਨਾ ਕਰੋ", latin:"dar na karo" }},
  { id:156, gurmukhi:"ਹੈਰਾਨ", latin:"hairaan", pos:"adjective", meaning:"surprised", category:"emotion", example:{ gurmukhi:"ਮੈਂ ਬਹੁਤ ਹੈਰਾਨ ਹਾਂ", latin:"main bahut hairaan haan" }},
  { id:157, gurmukhi:"ਸ਼ਰਮ", latin:"sharam", pos:"noun", meaning:"shame/shyness", category:"emotion", example:{ gurmukhi:"ਸ਼ਰਮ ਨਾ ਕਰੋ", latin:"sharam na karo" }},
  { id:158, gurmukhi:"ਉਮੀਦ", latin:"umeed", pos:"noun", meaning:"hope", category:"emotion", example:{ gurmukhi:"ਉਮੀਦ ਨਾ ਛੱਡੋ", latin:"umeed na chhaddo" }},
  { id:159, gurmukhi:"ਚਿੰਤਾ", latin:"chinta", pos:"noun", meaning:"worry", category:"emotion", example:{ gurmukhi:"ਚਿੰਤਾ ਨਾ ਕਰੋ", latin:"chinta na karo" }},
  { id:160, gurmukhi:"ਮਾਣ", latin:"maan", pos:"noun", meaning:"pride/honour", category:"emotion", example:{ gurmukhi:"ਸਾਨੂੰ ਮਾਣ ਹੈ", latin:"saanoon maan hai" }},
  { id:161, gurmukhi:"ਦੁੱਖ", latin:"dukkh", pos:"noun", meaning:"sorrow/pain", category:"emotion", example:{ gurmukhi:"ਦੁੱਖ ਵੰਡਾਓ", latin:"dukkh vandaao" }},
  { id:162, gurmukhi:"ਸੁੱਖ", latin:"sukkh", pos:"noun", meaning:"peace/comfort", category:"emotion", example:{ gurmukhi:"ਸੁੱਖ ਨਾਲ ਰਹੋ", latin:"sukkh naal raho" }},
  { id:163, gurmukhi:"ਹਾਸਾ", latin:"haasa", pos:"noun", meaning:"laughter", category:"emotion", example:{ gurmukhi:"ਹਾਸਾ ਸਭ ਤੋਂ ਚੰਗੀ ਦਵਾਈ ਹੈ", latin:"haasa sabh ton changi davaai hai" }},
  { id:164, gurmukhi:"ਰੋਣਾ", latin:"rona", pos:"verb", meaning:"to cry", category:"emotion", example:{ gurmukhi:"ਬੱਚਾ ਰੋ ਰਿਹਾ ਹੈ", latin:"bachcha ro riha hai" }},
  { id:165, gurmukhi:"ਹੌਸਲਾ", latin:"hausla", pos:"noun", meaning:"courage", category:"emotion", example:{ gurmukhi:"ਹੌਸਲਾ ਰੱਖੋ", latin:"hausla rakkho" }},
  { id:166, gurmukhi:"ਈਰਖ਼ਾ", latin:"eerkhaa", pos:"noun", meaning:"jealousy", category:"emotion", example:{ gurmukhi:"ਈਰਖ਼ਾ ਚੰਗੀ ਨਹੀਂ ਹੈ", latin:"eerkhaa changi naheen hai" }},
  { id:167, gurmukhi:"ਸ਼ੁਕਰ", latin:"shukar", pos:"noun", meaning:"gratitude", category:"emotion", example:{ gurmukhi:"ਰੱਬ ਦਾ ਸ਼ੁਕਰ ਕਰੋ", latin:"rabb da shukar karo" }},
  { id:168, gurmukhi:"ਤਰਸ", latin:"taras", pos:"noun", meaning:"compassion/pity", category:"emotion", example:{ gurmukhi:"ਤਰਸ ਖਾਓ", latin:"taras khaao" }},
  { id:169, gurmukhi:"ਖ਼ੁਸ਼", latin:"khush", pos:"adjective", meaning:"happy", category:"emotion", example:{ gurmukhi:"ਮੈਂ ਬਹੁਤ ਖ਼ੁਸ਼ ਹਾਂ", latin:"main bahut khush haan" }},
  { id:170, gurmukhi:"ਨਫ਼ਰਤ", latin:"nafrat", pos:"noun", meaning:"hatred", category:"emotion", example:{ gurmukhi:"ਨਫ਼ਰਤ ਨਾ ਕਰੋ", latin:"nafrat na karo" }},
  { id:171, gurmukhi:"ਯਾਦ", latin:"yaad", pos:"noun", meaning:"memory/missing", category:"emotion", example:{ gurmukhi:"ਤੇਰੀ ਯਾਦ ਆਉਂਦੀ ਹੈ", latin:"teri yaad aundi hai" }},
  { id:172, gurmukhi:"ਸਬਰ", latin:"sabar", pos:"noun", meaning:"patience", category:"emotion", example:{ gurmukhi:"ਸਬਰ ਰੱਖੋ", latin:"sabar rakkho" }},
  { id:173, gurmukhi:"ਸ਼ਾਂਤ", latin:"shaant", pos:"adjective", meaning:"calm/peaceful", category:"emotion", example:{ gurmukhi:"ਸ਼ਾਂਤ ਰਹੋ", latin:"shaant raho" }},
  { id:174, gurmukhi:"ਥੱਕਿਆ", latin:"thakkia", pos:"adjective", meaning:"tired", category:"emotion", example:{ gurmukhi:"ਮੈਂ ਬਹੁਤ ਥੱਕਿਆ ਹਾਂ", latin:"main bahut thakkia haan" }},
  { id:175, gurmukhi:"ਇਕੱਲਾ", latin:"ikalla", pos:"adjective", meaning:"lonely/alone", category:"emotion", example:{ gurmukhi:"ਇਕੱਲਾ ਨਾ ਰਹੋ", latin:"ikalla na raho" }},
  // ── TIME (176-200) ──
  { id:176, gurmukhi:"ਸਮਾਂ", latin:"samaan", pos:"noun", meaning:"time", category:"time", example:{ gurmukhi:"ਸਮਾਂ ਬਹੁਤ ਕੀਮਤੀ ਹੈ", latin:"samaan bahut keemti hai" }},
  { id:177, gurmukhi:"ਅੱਜ", latin:"ajj", pos:"adverb", meaning:"today", category:"time", example:{ gurmukhi:"ਅੱਜ ਛੁੱਟੀ ਹੈ", latin:"ajj chhutti hai" }},
  { id:178, gurmukhi:"ਕੱਲ੍ਹ", latin:"kallh", pos:"adverb", meaning:"yesterday/tomorrow", category:"time", example:{ gurmukhi:"ਕੱਲ੍ਹ ਮੀਂਹ ਪਿਆ ਸੀ", latin:"kallh meenh pya si" }},
  { id:179, gurmukhi:"ਸਵੇਰ", latin:"saver", pos:"noun", meaning:"morning", category:"time", example:{ gurmukhi:"ਸਵੇਰੇ ਜਲਦੀ ਉੱਠੋ", latin:"savere jaldi uttho" }},
  { id:180, gurmukhi:"ਦੁਪਹਿਰ", latin:"dupahir", pos:"noun", meaning:"afternoon", category:"time", example:{ gurmukhi:"ਦੁਪਹਿਰ ਨੂੰ ਆਰਾਮ ਕਰੋ", latin:"dupahir noon aaraam karo" }},
  { id:181, gurmukhi:"ਸ਼ਾਮ", latin:"shaam", pos:"noun", meaning:"evening", category:"time", example:{ gurmukhi:"ਸ਼ਾਮ ਨੂੰ ਸੈਰ ਕਰੋ", latin:"shaam noon sair karo" }},
  { id:182, gurmukhi:"ਰਾਤ", latin:"raat", pos:"noun", meaning:"night", category:"time", example:{ gurmukhi:"ਰਾਤ ਨੂੰ ਜਲਦੀ ਸੌਂ ਜਾਓ", latin:"raat noon jaldi saun jaao" }},
  { id:183, gurmukhi:"ਘੰਟਾ", latin:"ghanta", pos:"noun", meaning:"hour", category:"time", example:{ gurmukhi:"ਇੱਕ ਘੰਟਾ ਲੱਗੇਗਾ", latin:"ikk ghanta laggega" }},
  { id:184, gurmukhi:"ਮਿੰਟ", latin:"mint", pos:"noun", meaning:"minute", category:"time", example:{ gurmukhi:"ਪੰਜ ਮਿੰਟ ਰੁਕੋ", latin:"panj mint ruko" }},
  { id:185, gurmukhi:"ਹਫ਼ਤਾ", latin:"hafta", pos:"noun", meaning:"week", category:"time", example:{ gurmukhi:"ਇੱਕ ਹਫ਼ਤਾ ਬਾਅਦ ਮਿਲਾਂਗੇ", latin:"ikk hafta baad milaange" }},
  { id:186, gurmukhi:"ਮਹੀਨਾ", latin:"maheena", pos:"noun", meaning:"month", category:"time", example:{ gurmukhi:"ਇਹ ਮਹੀਨਾ ਗਰਮ ਹੈ", latin:"ih maheena garam hai" }},
  { id:187, gurmukhi:"ਸਾਲ", latin:"saal", pos:"noun", meaning:"year", category:"time", example:{ gurmukhi:"ਨਵਾਂ ਸਾਲ ਮੁਬਾਰਕ", latin:"navaan saal mubaarak" }},
  { id:188, gurmukhi:"ਸੋਮਵਾਰ", latin:"somvaar", pos:"noun", meaning:"Monday", category:"time", example:{ gurmukhi:"ਸੋਮਵਾਰ ਨੂੰ ਕੰਮ ਹੈ", latin:"somvaar noon kamm hai" }},
  { id:189, gurmukhi:"ਐਤਵਾਰ", latin:"aitvaar", pos:"noun", meaning:"Sunday", category:"time", example:{ gurmukhi:"ਐਤਵਾਰ ਨੂੰ ਛੁੱਟੀ ਹੈ", latin:"aitvaar noon chhutti hai" }},
  { id:190, gurmukhi:"ਬਸੰਤ", latin:"basant", pos:"noun", meaning:"spring", category:"time", example:{ gurmukhi:"ਬਸੰਤ ਰੁੱਤ ਸੋਹਣੀ ਹੈ", latin:"basant rutt sohni hai" }},
  { id:191, gurmukhi:"ਗਰਮੀ", latin:"garmi", pos:"noun", meaning:"summer/heat", category:"time", example:{ gurmukhi:"ਗਰਮੀ ਬਹੁਤ ਪੈ ਰਹੀ ਹੈ", latin:"garmi bahut pai rahi hai" }},
  { id:192, gurmukhi:"ਸਰਦੀ", latin:"sardi", pos:"noun", meaning:"winter/cold", category:"time", example:{ gurmukhi:"ਸਰਦੀ ਲੱਗ ਰਹੀ ਹੈ", latin:"sardi lagg rahi hai" }},
  { id:193, gurmukhi:"ਬਰਸਾਤ", latin:"barsaat", pos:"noun", meaning:"rainy season", category:"time", example:{ gurmukhi:"ਬਰਸਾਤ ਦਾ ਮੌਸਮ ਆ ਗਿਆ", latin:"barsaat da mausam aa gya" }},
  { id:194, gurmukhi:"ਪਿਛਲਾ", latin:"pichhla", pos:"adjective", meaning:"previous/last", category:"time", example:{ gurmukhi:"ਪਿਛਲੇ ਸਾਲ ਅਸੀਂ ਗਏ ਸੀ", latin:"pichhle saal aseen gae si" }},
  { id:195, gurmukhi:"ਅਗਲਾ", latin:"agla", pos:"adjective", meaning:"next", category:"time", example:{ gurmukhi:"ਅਗਲੇ ਹਫ਼ਤੇ ਮਿਲਾਂਗੇ", latin:"agle hafte milaange" }},
  { id:196, gurmukhi:"ਹੁਣ", latin:"hun", pos:"adverb", meaning:"now", category:"time", example:{ gurmukhi:"ਹੁਣ ਚੱਲੋ", latin:"hun challo" }},
  { id:197, gurmukhi:"ਫਿਰ", latin:"phir", pos:"adverb", meaning:"then/again", category:"time", example:{ gurmukhi:"ਫਿਰ ਮਿਲਾਂਗੇ", latin:"phir milaange" }},
  { id:198, gurmukhi:"ਹਮੇਸ਼ਾ", latin:"hamesha", pos:"adverb", meaning:"always", category:"time", example:{ gurmukhi:"ਹਮੇਸ਼ਾ ਸੱਚ ਬੋਲੋ", latin:"hamesha sachch bolo" }},
  { id:199, gurmukhi:"ਕਦੇ", latin:"kade", pos:"adverb", meaning:"sometimes/ever", category:"time", example:{ gurmukhi:"ਕਦੇ ਸਾਡੇ ਘਰ ਆਓ", latin:"kade saade ghar aao" }},
  { id:200, gurmukhi:"ਜਲਦੀ", latin:"jaldi", pos:"adverb", meaning:"quickly/soon", category:"time", example:{ gurmukhi:"ਜਲਦੀ ਕਰੋ", latin:"jaldi karo" }}
];
