/* ══════════════════════════════════════════════════
   Bolee — Seed Vocabulary
   ──────────────────────────────────────────────────
   Theth (ਠੇਠ) Punjabi: the rural, unmixed register.
   Deliberately weighted away from Hindi-Urdu loanwords
   that already survive fine in urban speech.

   Schema per word:
     id        stable slug, `${category}-${nnn}`
     gurmukhi  the word in Gurmukhi script
     latin     romanisation (readable, not strict ISO)
     pos       noun | verb | adj | adv | pron | interj
     meaning   English gloss
     category  one of VOCAB_CATEGORIES
     example   { gurmukhi, latin } — a natural sentence
     tier      1 kids · 2 general · 3 advanced
     dialect   majhi | malwai | doabi | puadhi | common
     emoji     kids-mode visual cue / tap-answer choice
     status    seed data ships pre-verified
     source    'seed' — contributed words carry a user id
   ══════════════════════════════════════════════════ */

(function (global) {
  'use strict';

  var CATEGORIES = [
    { id: 'home',    gurmukhi: 'ਘਰ',     label: 'Home',     emoji: '🏠' },
    { id: 'farm',    gurmukhi: 'ਖੇਤੀ',    label: 'Farm',     emoji: '🌾' },
    { id: 'nature',  gurmukhi: 'ਕੁਦਰਤ',  label: 'Nature',   emoji: '🌳' },
    { id: 'body',    gurmukhi: 'ਸਰੀਰ',   label: 'Body',     emoji: '🫀' },
    { id: 'food',    gurmukhi: 'ਖਾਣਾ',   label: 'Food',     emoji: '🍲' },
    { id: 'kinship', gurmukhi: 'ਰਿਸ਼ਤੇ',  label: 'Kinship',  emoji: '👪' },
    { id: 'emotion', gurmukhi: 'ਭਾਵਨਾ',  label: 'Emotion',  emoji: '💛' },
    { id: 'time',    gurmukhi: 'ਸਮਾਂ',    label: 'Time',     emoji: '🕰️' }
  ];

  var DIALECTS = [
    { id: 'common', label: 'Common' },
    { id: 'majhi',  label: 'Majhi' },
    { id: 'malwai', label: 'Malwai' },
    { id: 'doabi',  label: 'Doabi' },
    { id: 'puadhi', label: 'Puadhi' }
  ];

  var TIERS = [
    { id: 1, label: 'Everyday',  hint: 'first words, good for children' },
    { id: 2, label: 'Village',   hint: 'common rural vocabulary' },
    { id: 3, label: 'Deep theth', hint: 'older words, fading from use' }
  ];

  /* Compact tuple form keeps this file readable and roughly a third
     the size of 200+ object literals. Expanded into full records below. */
  // [gurmukhi, latin, pos, meaning, tier, dialect, emoji, exGurmukhi, exLatin]
  var RAW = {

    /* ── ਘਰ · HOME ─────────────────────────────────── */
    home: [
      ['ਘਰ', 'ghar', 'noun', 'house, home', 1, 'common', '🏠',
       'ਸਾਡਾ ਘਰ ਪਿੰਡ ਦੇ ਸਿਰੇ ਤੇ ਹੈ।', 'saada ghar pind de sire te hai.'],
      ['ਚੁੱਲ੍ਹਾ', 'chulha', 'noun', 'traditional mud stove', 2, 'common', '🔥',
       'ਬੇਬੇ ਚੁੱਲ੍ਹੇ ਤੇ ਰੋਟੀ ਲਾਹ ਰਹੀ ਹੈ।', 'bebe chulhe te roti laah rahi hai.'],
      ['ਵਿਹੜਾ', 'vehrha', 'noun', 'courtyard', 2, 'common', '🧱',
       'ਵਿਹੜੇ ਵਿੱਚ ਮੰਜੇ ਡਾਹੇ ਪਏ ਨੇ।', 'vehrhe vich manje daahe pae ne.'],
      ['ਮੰਜਾ', 'manja', 'noun', 'woven string cot', 1, 'common', '🛏️',
       'ਬਾਪੂ ਮੰਜੇ ਤੇ ਪਿਆ ਹੈ।', 'baapu manje te piaa hai.'],
      ['ਪੀੜ੍ਹੀ', 'peerhi', 'noun', 'low woven stool', 2, 'common', '🪑',
       'ਪੀੜ੍ਹੀ ਤੇ ਬਹਿ ਜਾ।', 'peerhi te beh ja.'],
      ['ਬੂਹਾ', 'booha', 'noun', 'door', 1, 'common', '🚪',
       'ਬੂਹਾ ਭੇੜ ਦੇ।', 'booha bherh de.'],
      ['ਛੱਤ', 'chhat', 'noun', 'roof, terrace', 1, 'common', '🏘️',
       'ਗਰਮੀਆਂ ਵਿੱਚ ਅਸੀਂ ਛੱਤ ਤੇ ਸੌਂਦੇ ਹਾਂ।', 'garmiaan vich aseen chhat te saunde haan.'],
      ['ਕੰਧ', 'kandh', 'noun', 'wall', 1, 'common', '🧱',
       'ਕੰਧ ਉੱਤੇ ਬਿੱਲੀ ਬੈਠੀ ਹੈ।', 'kandh utte billi baithi hai.'],
      ['ਸਬਾਤ', 'sabaat', 'noun', 'inner room of a village house', 3, 'malwai', '🚪',
       'ਸਬਾਤ ਵਿੱਚ ਦਾਣੇ ਪਏ ਨੇ।', 'sabaat vich daane pae ne.'],
      ['ਤੰਦੂਰ', 'tandoor', 'noun', 'clay oven', 2, 'common', '🍞',
       'ਪਿੰਡ ਦੇ ਸਾਂਝੇ ਤੰਦੂਰ ਤੇ ਰੋਟੀਆਂ ਲੱਗਦੀਆਂ ਨੇ।', 'pind de saanjhe tandoor te rotiaan laggdiaan ne.'],
      ['ਬਾਲਟੀ', 'baalti', 'noun', 'bucket', 1, 'common', '🪣',
       'ਬਾਲਟੀ ਭਰ ਕੇ ਲਿਆ।', 'baalti bhar ke liaa.'],
      ['ਘੜਾ', 'gharha', 'noun', 'earthen water pot', 2, 'common', '🏺',
       'ਘੜੇ ਦਾ ਪਾਣੀ ਠੰਢਾ ਹੁੰਦਾ ਹੈ।', 'gharhe da paani thandha hunda hai.'],
      ['ਝਾੜੂ', 'jhaarhu', 'noun', 'broom', 1, 'common', '🧹',
       'ਵਿਹੜੇ ਨੂੰ ਝਾੜੂ ਮਾਰ ਦੇ।', 'vehrhe nu jhaarhu maar de.'],
      ['ਚਾਦਰ', 'chaadar', 'noun', 'bedsheet', 1, 'common', '🧺',
       'ਮੰਜੇ ਤੇ ਸਾਫ਼ ਚਾਦਰ ਵਿਛਾ ਦੇ।', 'manje te saaf chaadar vichhaa de.'],
      ['ਰਜਾਈ', 'rajaai', 'noun', 'thick cotton quilt', 1, 'common', '🛌',
       'ਸਿਆਲ਼ ਵਿੱਚ ਰਜਾਈ ਬਿਨਾਂ ਨਹੀਂ ਸਰਦਾ।', 'siaal vich rajaai binaan naheen sarda.'],
      ['ਸੰਦੂਕ', 'sandook', 'noun', 'wooden storage trunk', 2, 'common', '🧳',
       'ਦਾਦੀ ਦੇ ਸੰਦੂਕ ਵਿੱਚ ਪੁਰਾਣੀਆਂ ਚੀਜ਼ਾਂ ਨੇ।', 'daadi de sandook vich puraaniaan cheezaan ne.'],
      ['ਚੌਂਕਾ', 'chaunka', 'noun', 'cooking area of the house', 3, 'common', '🍳',
       'ਚੌਂਕੇ ਵਿੱਚ ਪੈਰ ਧੋ ਕੇ ਵੜੀਦਾ ਸੀ।', 'chaunke vich pair dho ke varheeda si.'],
      ['ਖੂੰਜਾ', 'khoonja', 'noun', 'corner', 2, 'common', '📐',
       'ਖੂੰਜੇ ਵਿੱਚ ਸੋਟੀ ਪਈ ਹੈ।', 'khoonje vich soti paee hai.'],
      ['ਬਨੇਰਾ', 'banera', 'noun', 'parapet on a roof', 3, 'majhi', '🏚️',
       'ਬਨੇਰੇ ਤੇ ਕਾਂ ਬੋਲਦਾ ਹੈ।', 'banere te kaan bolda hai.'],
      ['ਦਲਾਨ', 'dalaan', 'noun', 'covered verandah', 3, 'doabi', '🏛️',
       'ਦਲਾਨ ਵਿੱਚ ਛਾਂ ਹੈ।', 'dalaan vich chhaan hai.'],
      ['ਪਰਾਤ', 'paraat', 'noun', 'wide flat dough-kneading dish', 2, 'common', '🥣',
       'ਪਰਾਤ ਵਿੱਚ ਆਟਾ ਗੁੰਨ੍ਹ ਲੈ।', 'paraat vich aata gunnh lai.'],
      ['ਚਿਮਟਾ', 'chimta', 'noun', 'flat tongs', 2, 'common', '🥢',
       'ਚਿਮਟੇ ਨਾਲ ਰੋਟੀ ਫੜ।', 'chimte naal roti pharh.'],
      ['ਤਵਾ', 'tava', 'noun', 'flat iron griddle', 1, 'common', '🍳',
       'ਤਵਾ ਗਰਮ ਹੋ ਗਿਆ।', 'tava garam ho giaa.'],
      ['ਪੌੜੀ', 'paurhi', 'noun', 'ladder, stairs', 1, 'common', '🪜',
       'ਪੌੜੀ ਲਾ ਕੇ ਛੱਤ ਤੇ ਚੜ੍ਹ।', 'paurhi laa ke chhat te charrh.'],
      ['ਜਿੰਦਰਾ', 'jindra', 'noun', 'padlock', 2, 'common', '🔒',
       'ਬੂਹੇ ਨੂੰ ਜਿੰਦਰਾ ਮਾਰ ਦੇ।', 'boohe nu jindra maar de.'],
      ['ਖੂਹ', 'khooh', 'noun', 'well', 2, 'common', '🕳️',
       'ਖੂਹ ਵਿੱਚੋਂ ਪਾਣੀ ਕੱਢ।', 'khooh vichon paani kaddh.'],
      ['ਢਾਰਾ', 'dhaara', 'noun', 'thatched shelter', 3, 'malwai', '🛖',
       'ਖੇਤ ਵਿੱਚ ਢਾਰਾ ਪਾਇਆ ਹੋਇਆ ਹੈ।', 'khet vich dhaara paaiaa hoiaa hai.']
    ],

    /* ── ਖੇਤੀ · FARM ───────────────────────────────── */
    farm: [
      ['ਖੇਤ', 'khet', 'noun', 'field', 1, 'common', '🌾',
       'ਬਾਪੂ ਖੇਤ ਗਿਆ ਹੋਇਆ ਹੈ।', 'baapu khet giaa hoiaa hai.'],
      ['ਹਾਲੀ', 'haali', 'noun', 'ploughman', 3, 'malwai', '🧑‍🌾',
       'ਹਾਲੀ ਸਵੇਰੇ ਹੀ ਖੇਤ ਵੜ ਗਿਆ।', 'haali savere hi khet varh giaa.'],
      ['ਖੁਰਲੀ', 'khurli', 'noun', 'feeding trough for cattle', 2, 'malwai', '🐃',
       'ਮੱਝਾਂ ਖੁਰਲੀ ਤੇ ਖੜ੍ਹੀਆਂ ਨੇ।', 'majjhaan khurli te kharrhiaan ne.'],
      ['ਪੱਠੇ', 'patthe', 'noun', 'green fodder', 2, 'common', '🌿',
       'ਡੰਗਰਾਂ ਲਈ ਪੱਠੇ ਵੱਢ ਲਿਆ।', 'dangraan laee patthe vaddh liaa.'],
      ['ਡੰਗਰ', 'dangar', 'noun', 'livestock, cattle', 2, 'common', '🐄',
       'ਡੰਗਰ ਚਾਰਨ ਲੈ ਗਿਆ।', 'dangar chaaran lai giaa.'],
      ['ਮੱਝ', 'majjh', 'noun', 'water buffalo', 1, 'common', '🐃',
       'ਮੱਝ ਦਾ ਦੁੱਧ ਗਾੜ੍ਹਾ ਹੁੰਦਾ ਹੈ।', 'majjh da duddh gaarrha hunda hai.'],
      ['ਗਾਂ', 'gaan', 'noun', 'cow', 1, 'common', '🐄',
       'ਗਾਂ ਵਾੜੇ ਵਿੱਚ ਬੰਨ੍ਹੀ ਹੈ।', 'gaan vaarhe vich bannhi hai.'],
      ['ਬਲਦ', 'balad', 'noun', 'ox, bullock', 2, 'common', '🐂',
       'ਬਲਦਾਂ ਨਾਲ ਹਲ਼ ਵਾਹੁੰਦੇ ਸੀ।', 'baladaan naal hal vaahunde si.'],
      ['ਹਲ਼', 'hal', 'noun', 'plough', 2, 'common', '⚒️',
       'ਹਲ਼ ਵਾਹ ਕੇ ਜ਼ਮੀਨ ਤਿਆਰ ਕੀਤੀ।', 'hal vaah ke zameen tiaar keeti.'],
      ['ਵਾੜਾ', 'vaarha', 'noun', 'cattle enclosure', 2, 'malwai', '🚧',
       'ਵਾੜੇ ਵਿੱਚ ਡੰਗਰ ਬੰਨ੍ਹੇ ਨੇ।', 'vaarhe vich dangar bannhe ne.'],
      ['ਫ਼ਸਲ', 'fasal', 'noun', 'crop', 1, 'common', '🌾',
       'ਇਸ ਵਾਰ ਫ਼ਸਲ ਚੰਗੀ ਹੋਈ।', 'is vaar fasal changi hoee.'],
      ['ਕਣਕ', 'kanak', 'noun', 'wheat', 1, 'common', '🌾',
       'ਕਣਕ ਪੱਕ ਗਈ ਹੈ।', 'kanak pakk gaee hai.'],
      ['ਝੋਨਾ', 'jhona', 'noun', 'paddy, rice crop', 2, 'common', '🌾',
       'ਝੋਨਾ ਲਾਉਣ ਦਾ ਵੇਲ਼ਾ ਆ ਗਿਆ।', 'jhona laaun da vela aa giaa.'],
      ['ਸਰ੍ਹੋਂ', 'sarhon', 'noun', 'mustard', 2, 'common', '🌼',
       'ਸਰ੍ਹੋਂ ਦੇ ਫੁੱਲ ਖਿੜੇ ਨੇ।', 'sarhon de phull khirhe ne.'],
      ['ਕਮਾਦ', 'kamaad', 'noun', 'sugarcane crop', 3, 'malwai', '🎋',
       'ਕਮਾਦ ਪੀੜਨ ਲਈ ਭੇਜਿਆ।', 'kamaad peerhan laee bhejiaa.'],
      ['ਦਾਤੀ', 'daati', 'noun', 'sickle', 2, 'common', '🔪',
       'ਦਾਤੀ ਨਾਲ ਪੱਠੇ ਵੱਢੇ।', 'daati naal patthe vaddhe.'],
      ['ਕਹੀ', 'kahi', 'noun', 'spade, hoe', 2, 'common', '⛏️',
       'ਕਹੀ ਨਾਲ ਖਾਲ਼ ਬਣਾ।', 'kahi naal khaal banaa.'],
      ['ਖਾਲ਼', 'khaal', 'noun', 'irrigation channel', 3, 'malwai', '💧',
       'ਖਾਲ਼ ਵਿੱਚ ਪਾਣੀ ਵਗ ਰਿਹਾ ਹੈ।', 'khaal vich paani vag rihaa hai.'],
      ['ਟਿੰਡ', 'tind', 'noun', 'pot on a Persian wheel', 3, 'common', '🏺',
       'ਖੂਹ ਦੀਆਂ ਟਿੰਡਾਂ ਘੁੰਮਦੀਆਂ ਸਨ।', 'khooh diaan tindaan ghummdiaan san.'],
      ['ਪਿੜ', 'pirh', 'noun', 'threshing floor', 3, 'malwai', '🌾',
       'ਪਿੜ ਵਿੱਚ ਕਣਕ ਗਾਹੀ ਜਾਂਦੀ ਸੀ।', 'pirh vich kanak gaahi jaandi si.'],
      ['ਤੂੜੀ', 'toorhi', 'noun', 'chopped straw fodder', 2, 'common', '🌾',
       'ਤੂੜੀ ਵਾਲਾ ਕੁੱਪ ਲਾ ਦਿੱਤਾ।', 'toorhi vaala kupp laa dittaa.'],
      ['ਕੁੱਪ', 'kupp', 'noun', 'conical straw stack', 3, 'malwai', '🗻',
       'ਪਿੰਡ ਦੇ ਬਾਹਰ ਕੁੱਪ ਖੜ੍ਹੇ ਨੇ।', 'pind de baahar kupp kharrhe ne.'],
      ['ਬੀਜ', 'beej', 'noun', 'seed', 1, 'common', '🌱',
       'ਚੰਗਾ ਬੀਜ ਪਾਓ।', 'changa beej pao.'],
      ['ਗੋਹਾ', 'goha', 'noun', 'cow dung', 2, 'common', '💩',
       'ਗੋਹੇ ਦੀਆਂ ਪਾਥੀਆਂ ਪੱਥ ਲਈਆਂ।', 'gohe diaan paathiaan patth laeeaan.'],
      ['ਪਾਥੀ', 'paathi', 'noun', 'dried dung cake used as fuel', 3, 'common', '🟤',
       'ਪਾਥੀਆਂ ਨਾਲ ਚੁੱਲ੍ਹਾ ਬਲ਼ਦਾ ਹੈ।', 'paathiaan naal chulha balda hai.'],
      ['ਟਰੈਕਟਰ', 'traictar', 'noun', 'tractor', 1, 'common', '🚜',
       'ਟਰੈਕਟਰ ਖੇਤ ਵਾਹ ਰਿਹਾ ਹੈ।', 'traictar khet vaah rihaa hai.'],
      ['ਵੱਟ', 'vatt', 'noun', 'raised field boundary', 2, 'common', '🛤️',
       'ਵੱਟ ਤੇ ਤੁਰ ਕੇ ਜਾਹ।', 'vatt te tur ke jaah.']
    ],

    /* ── ਕੁਦਰਤ · NATURE ────────────────────────────── */
    nature: [
      ['ਰੁੱਖ', 'rukkh', 'noun', 'tree', 1, 'common', '🌳',
       'ਰੁੱਖ ਦੀ ਛਾਂ ਵਿੱਚ ਬਹਿ ਜਾ।', 'rukkh di chhaan vich beh ja.'],
      ['ਛਾਂ', 'chhaan', 'noun', 'shade', 1, 'common', '🌤️',
       'ਛਾਂ ਬੜੀ ਠੰਢੀ ਹੈ।', 'chhaan barhi thandhi hai.'],
      ['ਮੀਂਹ', 'meenh', 'noun', 'rain', 1, 'common', '🌧️',
       'ਰਾਤੀਂ ਮੀਂਹ ਪਿਆ।', 'raateen meenh piaa.'],
      ['ਹਨੇਰੀ', 'haneri', 'noun', 'dust storm, gale', 2, 'common', '🌪️',
       'ਹਨੇਰੀ ਆਈ ਤੇ ਸਭ ਕੁਝ ਉਡਾ ਲੈ ਗਈ।', 'haneri aaee te sabh kujh udaa lai gaee.'],
      ['ਧੁੱਪ', 'dhupp', 'noun', 'sunshine', 1, 'common', '☀️',
       'ਧੁੱਪ ਬੜੀ ਤਿੱਖੀ ਹੈ।', 'dhupp barhi tikkhi hai.'],
      ['ਕੱਕਰ', 'kakkar', 'noun', 'frost', 3, 'malwai', '❄️',
       'ਰਾਤੀਂ ਕੱਕਰ ਪੈ ਗਿਆ।', 'raateen kakkar pai giaa.'],
      ['ਧੁੰਦ', 'dhund', 'noun', 'fog', 2, 'common', '🌫️',
       'ਧੁੰਦ ਕਰਕੇ ਕੁਝ ਨਹੀਂ ਦਿਸਦਾ।', 'dhund karke kujh naheen disda.'],
      ['ਪੌਣ', 'paun', 'noun', 'wind, breeze', 2, 'common', '🍃',
       'ਠੰਢੀ ਪੌਣ ਵਗ ਰਹੀ ਹੈ।', 'thandhi paun vag rahi hai.'],
      ['ਨਦੀ', 'nadi', 'noun', 'river', 1, 'common', '🏞️',
       'ਨਦੀ ਦਾ ਪਾਣੀ ਚੜ੍ਹ ਗਿਆ।', 'nadi da paani charrh giaa.'],
      ['ਛੱਪੜ', 'chhappar', 'noun', 'village pond', 2, 'common', '🌊',
       'ਮੱਝਾਂ ਛੱਪੜ ਵਿੱਚ ਬੈਠੀਆਂ ਨੇ।', 'majjhaan chhappar vich baithiaan ne.'],
      ['ਟੋਭਾ', 'tobha', 'noun', 'water pit, small pond', 3, 'malwai', '💧',
       'ਟੋਭੇ ਕੰਢੇ ਬੋਹੜ ਹੈ।', 'tobhe kandhe bohrh hai.'],
      ['ਬੋਹੜ', 'bohrh', 'noun', 'banyan tree', 2, 'common', '🌳',
       'ਬੋਹੜ ਹੇਠ ਸੱਥ ਜੁੜਦੀ ਹੈ।', 'bohrh heth sath jurhdi hai.'],
      ['ਪਿੱਪਲ', 'pippal', 'noun', 'peepal tree', 2, 'common', '🌲',
       'ਪਿੱਪਲ ਦੇ ਪੱਤੇ ਖੜਕਦੇ ਨੇ।', 'pippal de patte kharhakde ne.'],
      ['ਕਿੱਕਰ', 'kikkar', 'noun', 'acacia tree', 2, 'common', '🌵',
       'ਕਿੱਕਰ ਦੇ ਕੰਡੇ ਤਿੱਖੇ ਨੇ।', 'kikkar de kande tikkhe ne.'],
      ['ਟਾਹਲੀ', 'taahli', 'noun', 'sheesham tree', 3, 'common', '🌳',
       'ਟਾਹਲੀ ਦੀ ਲੱਕੜ ਮਜ਼ਬੂਤ ਹੁੰਦੀ ਹੈ।', 'taahli di lakkarh mazboot hundi hai.'],
      ['ਚਿੜੀ', 'chirhi', 'noun', 'sparrow, small bird', 1, 'common', '🐦',
       'ਚਿੜੀ ਚੀਂ ਚੀਂ ਕਰਦੀ ਹੈ।', 'chirhi cheen cheen kardi hai.'],
      ['ਕਾਂ', 'kaan', 'noun', 'crow', 1, 'common', '🐦‍⬛',
       'ਕਾਂ ਬਨੇਰੇ ਤੇ ਬੋਲਿਆ।', 'kaan banere te boliaa.'],
      ['ਕੋਇਲ', 'koil', 'noun', 'koel, cuckoo', 2, 'common', '🐤',
       'ਕੋਇਲ ਦੀ ਕੂਕ ਸੁਣੀ।', 'koil di kook suni.'],
      ['ਸੱਪ', 'sapp', 'noun', 'snake', 1, 'common', '🐍',
       'ਖੇਤ ਵਿੱਚ ਸੱਪ ਨਿਕਲਿਆ।', 'khet vich sapp nikliaa.'],
      ['ਟਿੱਡੀ', 'tiddi', 'noun', 'locust, grasshopper', 2, 'common', '🦗',
       'ਟਿੱਡੀ ਦਲ ਨੇ ਫ਼ਸਲ ਖਾ ਲਈ।', 'tiddi dal ne fasal khaa laee.'],
      ['ਜੁਗਨੂੰ', 'jugnoon', 'noun', 'firefly', 2, 'common', '✨',
       'ਹਨੇਰੇ ਵਿੱਚ ਜੁਗਨੂੰ ਚਮਕਦੇ ਨੇ।', 'hanere vich jugnoon chamakde ne.'],
      ['ਮਿੱਟੀ', 'mitti', 'noun', 'soil, earth', 1, 'common', '🟫',
       'ਮੀਂਹ ਪਿੱਛੋਂ ਮਿੱਟੀ ਦੀ ਮਹਿਕ ਆਉਂਦੀ ਹੈ।', 'meenh pichhon mitti di mehak aaundi hai.'],
      ['ਚੰਨ', 'chann', 'noun', 'moon', 1, 'common', '🌙',
       'ਅੱਜ ਚੰਨ ਪੂਰਾ ਹੈ।', 'ajj chann poora hai.'],
      ['ਤਾਰਾ', 'taara', 'noun', 'star', 1, 'common', '⭐',
       'ਅਸਮਾਨ ਤਾਰਿਆਂ ਨਾਲ ਭਰਿਆ ਹੈ।', 'asmaan taariaan naal bhariaa hai.'],
      ['ਬੱਦਲ', 'baddal', 'noun', 'cloud', 1, 'common', '☁️',
       'ਬੱਦਲ ਘਿਰ ਆਏ ਨੇ।', 'baddal ghir aae ne.'],
      ['ਬਿਜਲੀ', 'bijli', 'noun', 'lightning', 2, 'common', '⚡',
       'ਬਿਜਲੀ ਕੜਕੀ।', 'bijli karhki.'],
      ['ਗਰਦ', 'gard', 'noun', 'dust', 2, 'common', '🌬️',
       'ਰਾਹ ਤੇ ਗਰਦ ਉੱਡਦੀ ਹੈ।', 'raah te gard uddadi hai.']
    ],

    /* ── ਸਰੀਰ · BODY ───────────────────────────────── */
    body: [
      ['ਸਿਰ', 'sir', 'noun', 'head', 1, 'common', '🧠',
       'ਸਿਰ ਦੁਖ ਰਿਹਾ ਹੈ।', 'sir dukh rihaa hai.'],
      ['ਅੱਖ', 'akkh', 'noun', 'eye', 1, 'common', '👁️',
       'ਅੱਖ ਵਿੱਚ ਕੁਝ ਪੈ ਗਿਆ।', 'akkh vich kujh pai giaa.'],
      ['ਕੰਨ', 'kann', 'noun', 'ear', 1, 'common', '👂',
       'ਕੰਨ ਖੋਲ੍ਹ ਕੇ ਸੁਣ।', 'kann kholh ke sun.'],
      ['ਨੱਕ', 'nakk', 'noun', 'nose', 1, 'common', '👃',
       'ਨੱਕ ਵਗ ਰਿਹਾ ਹੈ।', 'nakk vag rihaa hai.'],
      ['ਮੂੰਹ', 'moonh', 'noun', 'mouth, face', 1, 'common', '👄',
       'ਮੂੰਹ ਧੋ ਲੈ।', 'moonh dho lai.'],
      ['ਹੱਥ', 'hatth', 'noun', 'hand', 1, 'common', '✋',
       'ਹੱਥ ਧੋ ਕੇ ਰੋਟੀ ਖਾ।', 'hatth dho ke roti khaa.'],
      ['ਪੈਰ', 'pair', 'noun', 'foot', 1, 'common', '🦶',
       'ਪੈਰ ਵਿੱਚ ਕੰਡਾ ਵੱਜਿਆ।', 'pair vich kanda vajjiaa.'],
      ['ਲੱਤ', 'latt', 'noun', 'leg', 1, 'common', '🦵',
       'ਲੱਤ ਵਿੱਚ ਪੀੜ ਹੈ।', 'latt vich peerh hai.'],
      ['ਬਾਂਹ', 'baanh', 'noun', 'arm', 1, 'common', '💪',
       'ਬਾਂਹ ਫੜ ਕੇ ਚੁੱਕ ਲੈ।', 'baanh pharh ke chukk lai.'],
      ['ਢਿੱਡ', 'dhidd', 'noun', 'belly, stomach', 1, 'common', '🫄',
       'ਢਿੱਡ ਭਰ ਗਿਆ।', 'dhidd bhar giaa.'],
      ['ਪਿੱਠ', 'pitth', 'noun', 'back', 1, 'common', '🔙',
       'ਪਿੱਠ ਤੇ ਭਾਰ ਚੁੱਕਿਆ।', 'pitth te bhaar chukkiaa.'],
      ['ਗਲ਼', 'gal', 'noun', 'throat, neck', 2, 'common', '🗣️',
       'ਗਲ਼ ਬਹਿ ਗਿਆ।', 'gal beh giaa.'],
      ['ਵਾਲ਼', 'vaal', 'noun', 'hair', 1, 'common', '💇',
       'ਵਾਲ਼ ਵਾਹ ਲੈ।', 'vaal vaah lai.'],
      ['ਦੰਦ', 'dand', 'noun', 'tooth', 1, 'common', '🦷',
       'ਦੰਦ ਦੁਖਦਾ ਹੈ।', 'dand dukhda hai.'],
      ['ਜੀਭ', 'jeebh', 'noun', 'tongue', 1, 'common', '👅',
       'ਜੀਭ ਸੜ ਗਈ।', 'jeebh sarh gaee.'],
      ['ਉਂਗਲ', 'ungal', 'noun', 'finger', 1, 'common', '☝️',
       'ਉਂਗਲ ਕੱਟੀ ਗਈ।', 'ungal katti gaee.'],
      ['ਗੋਡਾ', 'goda', 'noun', 'knee', 2, 'common', '🦵',
       'ਗੋਡੇ ਦੁਖਦੇ ਨੇ।', 'gode dukhde ne.'],
      ['ਮੋਢਾ', 'modha', 'noun', 'shoulder', 2, 'common', '🫸',
       'ਮੋਢੇ ਤੇ ਚੁੱਕ ਲੈ।', 'modhe te chukk lai.'],
      ['ਅੱਡੀ', 'addi', 'noun', 'heel', 2, 'common', '🦶',
       'ਅੱਡੀ ਫਟ ਗਈ ਹੈ।', 'addi phat gaee hai.'],
      ['ਗੁੱਟ', 'gutt', 'noun', 'wrist', 2, 'common', '⌚',
       'ਗੁੱਟ ਤੇ ਕੜਾ ਪਾਇਆ ਹੈ।', 'gutt te karha paaiaa hai.'],
      ['ਮੱਥਾ', 'mattha', 'noun', 'forehead', 2, 'common', '😐',
       'ਮੱਥੇ ਤੇ ਤਿਊੜੀ ਪਾ ਲਈ।', 'matthe te tiurhi paa laee.'],
      ['ਲਹੂ', 'lahoo', 'noun', 'blood', 2, 'common', '🩸',
       'ਜ਼ਖ਼ਮ ਵਿੱਚੋਂ ਲਹੂ ਵਗਿਆ।', 'zakhm vichon lahoo vagiaa.'],
      ['ਸਾਹ', 'saah', 'noun', 'breath', 2, 'common', '💨',
       'ਸਾਹ ਚੜ੍ਹ ਗਿਆ।', 'saah charrh giaa.'],
      ['ਹੱਡੀ', 'haddi', 'noun', 'bone', 2, 'common', '🦴',
       'ਹੱਡੀ ਟੁੱਟ ਗਈ।', 'haddi tutt gaee.'],
      ['ਚਮੜੀ', 'chamrhi', 'noun', 'skin', 2, 'common', '🧴',
       'ਚਮੜੀ ਖੁਸ਼ਕ ਹੋ ਗਈ।', 'chamrhi khushk ho gaee.'],
      ['ਥੁੱਕ', 'thukk', 'noun', 'spit, saliva', 3, 'common', '💧',
       'ਮੂੰਹ ਵਿੱਚ ਥੁੱਕ ਸੁੱਕ ਗਿਆ।', 'moonh vich thukk sukk giaa.'],
      ['ਗਿੱਟਾ', 'gitta', 'noun', 'ankle', 3, 'malwai', '🦶',
       'ਗਿੱਟਾ ਮੁੜ ਗਿਆ।', 'gitta murh giaa.']
    ],

    /* ── ਖਾਣਾ · FOOD ───────────────────────────────── */
    food: [
      ['ਰੋਟੀ', 'roti', 'noun', 'flatbread; a meal', 1, 'common', '🫓',
       'ਰੋਟੀ ਖਾ ਲੈ।', 'roti khaa lai.'],
      ['ਦਾਲ', 'daal', 'noun', 'lentils', 1, 'common', '🍲',
       'ਦਾਲ ਧਰ ਦਿੱਤੀ ਹੈ।', 'daal dhar ditti hai.'],
      ['ਸਾਗ', 'saag', 'noun', 'mustard greens dish', 1, 'common', '🥬',
       'ਸਾਗ ਤੇ ਮੱਕੀ ਦੀ ਰੋਟੀ ਬਣੀ ਹੈ।', 'saag te makki di roti bani hai.'],
      ['ਲੱਸੀ', 'lassi', 'noun', 'buttermilk drink', 1, 'common', '🥛',
       'ਲੱਸੀ ਦਾ ਗਲਾਸ ਪੀ ਲੈ।', 'lassi da galaas pee lai.'],
      ['ਮੱਖਣ', 'makkhan', 'noun', 'butter', 1, 'common', '🧈',
       'ਰੋਟੀ ਤੇ ਮੱਖਣ ਲਾ ਦੇ।', 'roti te makkhan laa de.'],
      ['ਦੁੱਧ', 'duddh', 'noun', 'milk', 1, 'common', '🥛',
       'ਦੁੱਧ ਕਾੜ੍ਹ ਲੈ।', 'duddh kaarrh lai.'],
      ['ਦਹੀਂ', 'daheen', 'noun', 'yoghurt', 1, 'common', '🥣',
       'ਦਹੀਂ ਜਮਾ ਦਿੱਤਾ।', 'daheen jamaa dittaa.'],
      ['ਗੁੜ', 'gurh', 'noun', 'jaggery', 2, 'common', '🟤',
       'ਗੁੜ ਦੀ ਰੋੜੀ ਖਾ ਲੈ।', 'gurh di rorhi khaa lai.'],
      ['ਖੰਡ', 'khand', 'noun', 'sugar', 1, 'common', '🍬',
       'ਚਾਹ ਵਿੱਚ ਖੰਡ ਪਾ ਦੇ।', 'chaah vich khand paa de.'],
      ['ਆਟਾ', 'aata', 'noun', 'flour', 1, 'common', '🌾',
       'ਆਟਾ ਗੁੰਨ੍ਹ ਲੈ।', 'aata gunnh lai.'],
      ['ਮੱਕੀ', 'makki', 'noun', 'maize, corn', 1, 'common', '🌽',
       'ਮੱਕੀ ਦੀ ਰੋਟੀ ਸੁਆਦ ਹੁੰਦੀ ਹੈ।', 'makki di roti suaad hundi hai.'],
      ['ਛੋਲੇ', 'chhole', 'noun', 'chickpeas', 2, 'common', '🫘',
       'ਛੋਲੇ ਭਿਉਂ ਦਿੱਤੇ।', 'chhole bhiun ditte.'],
      ['ਅਚਾਰ', 'achaar', 'noun', 'pickle', 1, 'common', '🥒',
       'ਅੰਬ ਦਾ ਅਚਾਰ ਪਾਇਆ ਹੈ।', 'amb da achaar paaiaa hai.'],
      ['ਚਟਣੀ', 'chatni', 'noun', 'chutney', 2, 'common', '🌶️',
       'ਪੁਦੀਨੇ ਦੀ ਚਟਣੀ ਬਣਾ।', 'pudeene di chatni banaa.'],
      ['ਖੀਰ', 'kheer', 'noun', 'rice pudding', 2, 'common', '🍚',
       'ਖੀਰ ਬਣਾਈ ਹੈ।', 'kheer banaaee hai.'],
      ['ਪਕੌੜਾ', 'pakaurha', 'noun', 'fritter', 1, 'common', '🍤',
       'ਮੀਂਹ ਵਿੱਚ ਪਕੌੜੇ ਤਲ਼ੇ।', 'meenh vich pakaurhe tale.'],
      ['ਕੜ੍ਹੀ', 'karrhi', 'noun', 'gram-flour yoghurt curry', 2, 'common', '🍛',
       'ਕੜ੍ਹੀ ਚੌਲ ਬਣੇ ਨੇ।', 'karrhi chaul bane ne.'],
      ['ਪੰਜੀਰੀ', 'panjeeri', 'noun', 'sweet flour-nut preparation', 3, 'common', '🥜',
       'ਸਿਆਲ਼ ਵਿੱਚ ਪੰਜੀਰੀ ਖਾਈਦੀ ਹੈ।', 'siaal vich panjeeri khaaeedi hai.'],
      ['ਕੜਾਹ', 'karhaah', 'noun', 'sacred semolina pudding', 2, 'common', '🍮',
       'ਕੜਾਹ ਪ੍ਰਸ਼ਾਦ ਵਰਤਾਇਆ।', 'karhaah parshaad vartaaiaa.'],
      ['ਮਧਾਣੀ', 'madhaani', 'noun', 'wooden churning staff', 3, 'common', '🥄',
       'ਮਧਾਣੀ ਨਾਲ ਦਹੀਂ ਰਿੜਕਿਆ।', 'madhaani naal daheen rirhkiaa.'],
      ['ਚਾਟੀ', 'chaati', 'noun', 'earthen churning pot', 3, 'malwai', '🏺',
       'ਚਾਟੀ ਵਿੱਚ ਦਹੀਂ ਪਾਇਆ।', 'chaati vich daheen paaiaa.'],
      ['ਭੁੱਖ', 'bhukkh', 'noun', 'hunger', 1, 'common', '😋',
       'ਬੜੀ ਭੁੱਖ ਲੱਗੀ ਹੈ।', 'barhi bhukkh laggi hai.'],
      ['ਪਿਆਸ', 'piaas', 'noun', 'thirst', 1, 'common', '🥤',
       'ਪਿਆਸ ਨਾਲ ਗਲ਼ ਸੁੱਕ ਗਿਆ।', 'piaas naal gal sukk giaa.'],
      ['ਸੁਆਦ', 'suaad', 'noun', 'taste, flavour', 1, 'common', '😋',
       'ਬੜਾ ਸੁਆਦ ਬਣਿਆ ਹੈ।', 'barhaa suaad baniaa hai.'],
      ['ਚੌਲ', 'chaul', 'noun', 'rice', 1, 'common', '🍚',
       'ਚੌਲ ਧਰ ਦੇ।', 'chaul dhar de.'],
      ['ਸਬਜ਼ੀ', 'sabzi', 'noun', 'vegetable dish', 1, 'common', '🥕',
       'ਅੱਜ ਕਿਹੜੀ ਸਬਜ਼ੀ ਬਣੀ ਹੈ?', 'ajj kehrhi sabzi bani hai?'],
      ['ਦੇਸੀ ਘਿਓ', 'desi ghio', 'noun', 'clarified butter', 2, 'common', '🧈',
       'ਦੇਸੀ ਘਿਓ ਪਾ ਕੇ ਖਾ।', 'desi ghio paa ke khaa.']
    ],

    /* ── ਰਿਸ਼ਤੇ · KINSHIP ──────────────────────────── */
    kinship: [
      ['ਬੇਬੇ', 'bebe', 'noun', 'mother (rural address)', 1, 'malwai', '👩',
       'ਬੇਬੇ ਨੇ ਰੋਟੀ ਪਕਾਈ।', 'bebe ne roti pakaaee.'],
      ['ਬਾਪੂ', 'baapu', 'noun', 'father (rural address)', 1, 'malwai', '👨',
       'ਬਾਪੂ ਖੇਤ ਗਿਆ ਹੈ।', 'baapu khet giaa hai.'],
      ['ਦਾਦਾ', 'daada', 'noun', 'paternal grandfather', 1, 'common', '👴',
       'ਦਾਦਾ ਜੀ ਕਹਾਣੀ ਸੁਣਾਉਂਦੇ ਨੇ।', 'daada ji kahaani sunaaunde ne.'],
      ['ਦਾਦੀ', 'daadi', 'noun', 'paternal grandmother', 1, 'common', '👵',
       'ਦਾਦੀ ਦੀ ਗੋਦ ਵਿੱਚ ਸੌਂ ਗਿਆ।', 'daadi di god vich saun giaa.'],
      ['ਨਾਨਾ', 'naana', 'noun', 'maternal grandfather', 1, 'common', '👴',
       'ਨਾਨਾ ਜੀ ਪਿੰਡੋਂ ਆਏ ਨੇ।', 'naana ji pindon aae ne.'],
      ['ਨਾਨੀ', 'naani', 'noun', 'maternal grandmother', 1, 'common', '👵',
       'ਨਾਨੀ ਦੇ ਘਰ ਜਾਣਾ ਹੈ।', 'naani de ghar jaana hai.'],
      ['ਭਰਾ', 'bhraa', 'noun', 'brother', 1, 'common', '👦',
       'ਮੇਰਾ ਭਰਾ ਵੱਡਾ ਹੈ।', 'mera bhraa vaddaa hai.'],
      ['ਭੈਣ', 'bhain', 'noun', 'sister', 1, 'common', '👧',
       'ਭੈਣ ਸਕੂਲ ਗਈ ਹੈ।', 'bhain skool gaee hai.'],
      ['ਚਾਚਾ', 'chaacha', 'noun', "father's younger brother", 1, 'common', '🧔',
       'ਚਾਚਾ ਸ਼ਹਿਰੋਂ ਆਇਆ।', 'chaacha shehron aaiaa.'],
      ['ਤਾਇਆ', 'taaiaa', 'noun', "father's elder brother", 1, 'common', '🧓',
       'ਤਾਇਆ ਜੀ ਸੱਥ ਵਿੱਚ ਬੈਠੇ ਨੇ।', 'taaiaa ji sath vich baithe ne.'],
      ['ਭੂਆ', 'bhooaa', 'noun', "father's sister", 2, 'common', '👩',
       'ਭੂਆ ਦਾ ਪਿੰਡ ਨੇੜੇ ਹੈ।', 'bhooaa da pind nerhe hai.'],
      ['ਮਾਸੀ', 'maasi', 'noun', "mother's sister", 2, 'common', '👩',
       'ਮਾਸੀ ਨੇ ਬੜਾ ਲਾਡ ਕੀਤਾ।', 'maasi ne barhaa laad keetaa.'],
      ['ਮਾਮਾ', 'maama', 'noun', "mother's brother", 1, 'common', '👨',
       'ਮਾਮਾ ਜੀ ਲੈਣ ਆਏ ਨੇ।', 'maama ji lain aae ne.'],
      ['ਪੁੱਤ', 'putt', 'noun', 'son; term of endearment', 1, 'common', '👦',
       'ਪੁੱਤ, ਰੋਟੀ ਖਾ ਲੈ।', 'putt, roti khaa lai.'],
      ['ਧੀ', 'dhee', 'noun', 'daughter', 1, 'common', '👧',
       'ਧੀ ਘਰ ਦੀ ਰੌਣਕ ਹੁੰਦੀ ਹੈ।', 'dhee ghar di raunak hundi hai.'],
      ['ਨੂੰਹ', 'noonh', 'noun', 'daughter-in-law', 2, 'common', '👰',
       'ਨੂੰਹ ਘਰ ਆਈ ਹੈ।', 'noonh ghar aaee hai.'],
      ['ਜਵਾਈ', 'javaaee', 'noun', 'son-in-law', 2, 'common', '🤵',
       'ਜਵਾਈ ਜੀ ਆਏ ਨੇ।', 'javaaee ji aae ne.'],
      ['ਸੱਸ', 'sass', 'noun', 'mother-in-law', 2, 'common', '👵',
       'ਸੱਸ ਨੇ ਅਸੀਸ ਦਿੱਤੀ।', 'sass ne asees ditti.'],
      ['ਸਹੁਰਾ', 'sohra', 'noun', 'father-in-law', 2, 'common', '👴',
       'ਸਹੁਰਾ ਸਾਹਬ ਬੈਠੇ ਨੇ।', 'sohra saahab baithe ne.'],
      ['ਦਿਓਰ', 'dior', 'noun', "husband's younger brother", 3, 'common', '👦',
       'ਦਿਓਰ ਬੜਾ ਮਖੌਲੀਆ ਹੈ।', 'dior barhaa makhaulia hai.'],
      ['ਜੇਠ', 'jeth', 'noun', "husband's elder brother", 3, 'common', '🧔',
       'ਜੇਠ ਜੀ ਦਾ ਬੜਾ ਅਦਬ ਹੈ।', 'jeth ji da barhaa adab hai.'],
      ['ਨਣਦ', 'nanad', 'noun', "husband's sister", 3, 'common', '👩',
       'ਨਣਦ ਨਾਲ ਚੰਗੀ ਬਣਦੀ ਹੈ।', 'nanad naal changi bandi hai.'],
      ['ਪੇਕੇ', 'peke', 'noun', "a married woman's parental home", 3, 'common', '🏡',
       'ਉਹ ਪੇਕੇ ਗਈ ਹੋਈ ਹੈ।', 'oh peke gaee hoee hai.'],
      ['ਸਹੁਰੇ', 'sohre', 'noun', "in-laws' home", 2, 'common', '🏘️',
       'ਸਹੁਰੇ ਪਿੰਡ ਦੂਰ ਹੈ।', 'sohre pind door hai.'],
      ['ਸ਼ਰੀਕ', 'shareek', 'noun', 'kin-rival, extended-family rival', 3, 'malwai', '⚔️',
       'ਸ਼ਰੀਕਾਂ ਨਾਲ ਜ਼ਮੀਨ ਦਾ ਝਗੜਾ ਹੈ।', 'shareekaan naal zameen da jhagrhaa hai.'],
      ['ਯਾਰ', 'yaar', 'noun', 'close friend', 1, 'common', '🤝',
       'ਯਾਰਾਂ ਬਿਨਾਂ ਨਹੀਂ ਸਰਦਾ।', 'yaaraan binaan naheen sarda.'],
      ['ਗੁਆਂਢੀ', 'guaandhi', 'noun', 'neighbour', 1, 'common', '🏘️',
       'ਗੁਆਂਢੀ ਬੜੇ ਚੰਗੇ ਨੇ।', 'guaandhi barhe change ne.']
    ],

    /* ── ਭਾਵਨਾ · EMOTION ──────────────────────────── */
    emotion: [
      ['ਖ਼ੁਸ਼ੀ', 'khushi', 'noun', 'happiness', 1, 'common', '😄',
       'ਘਰ ਵਿੱਚ ਖ਼ੁਸ਼ੀ ਦਾ ਮਾਹੌਲ ਹੈ।', 'ghar vich khushi da maahaul hai.'],
      ['ਦੁੱਖ', 'dukkh', 'noun', 'sorrow, pain', 1, 'common', '😢',
       'ਉਹਦਾ ਦੁੱਖ ਸਮਝ ਆਉਂਦਾ ਹੈ।', 'ohda dukkh samajh aaunda hai.'],
      ['ਮੋਹ', 'moh', 'noun', 'affection, attachment', 2, 'common', '💛',
       'ਮਾਂ ਦਾ ਮੋਹ ਬੜਾ ਡੂੰਘਾ ਹੁੰਦਾ ਹੈ।', 'maan da moh barhaa doongha hunda hai.'],
      ['ਗੁੱਸਾ', 'gussa', 'noun', 'anger', 1, 'common', '😠',
       'ਬਾਪੂ ਨੂੰ ਗੁੱਸਾ ਆ ਗਿਆ।', 'baapu nu gussa aa giaa.'],
      ['ਡਰ', 'dar', 'noun', 'fear', 1, 'common', '😨',
       'ਹਨੇਰੇ ਤੋਂ ਡਰ ਲੱਗਦਾ ਹੈ।', 'hanere ton dar laggda hai.'],
      ['ਹਾਸਾ', 'haasa', 'noun', 'laughter', 1, 'common', '😂',
       'ਸਾਰੇ ਪਾਸੇ ਹਾਸਾ ਪੈ ਗਿਆ।', 'saare paase haasa pai giaa.'],
      ['ਰੋਣਾ', 'rona', 'verb', 'to cry', 1, 'common', '😭',
       'ਨਿਆਣਾ ਰੋਣ ਲੱਗ ਪਿਆ।', 'niaana ron lagg piaa.'],
      ['ਸ਼ਰਮ', 'sharam', 'noun', 'shyness, shame', 2, 'common', '😳',
       'ਉਹਨੂੰ ਸ਼ਰਮ ਆ ਗਈ।', 'ohnu sharam aa gaee.'],
      ['ਹੌਸਲਾ', 'hausla', 'noun', 'courage, morale', 2, 'common', '💪',
       'ਹੌਸਲਾ ਨਾ ਹਾਰ।', 'hausla naa haar.'],
      ['ਉਦਾਸੀ', 'udaasi', 'noun', 'sadness, gloom', 2, 'common', '😔',
       'ਚਿਹਰੇ ਤੇ ਉਦਾਸੀ ਛਾਈ ਹੋਈ ਸੀ।', 'chehre te udaasi chhaaee hoee si.'],
      ['ਚਾਅ', 'chaa', 'noun', 'eager delight, longing', 3, 'common', '🤩',
       'ਵਿਆਹ ਦਾ ਬੜਾ ਚਾਅ ਹੈ।', 'viaah da barhaa chaa hai.'],
      ['ਤਾਂਘ', 'taangh', 'noun', 'yearning', 3, 'common', '🥺',
       'ਪਿੰਡ ਦੀ ਤਾਂਘ ਲੱਗੀ ਰਹਿੰਦੀ ਹੈ।', 'pind di taangh laggi rehndi hai.'],
      ['ਹੇਰਵਾ', 'herva', 'noun', 'ache of separation, homesickness', 3, 'majhi', '💔',
       'ਪਰਦੇਸ ਵਿੱਚ ਹੇਰਵਾ ਵੱਢ ਵੱਢ ਖਾਂਦਾ ਹੈ।', 'pardes vich herva vaddh vaddh khaanda hai.'],
      ['ਸਬਰ', 'sabar', 'noun', 'patience, forbearance', 2, 'common', '🧘',
       'ਸਬਰ ਰੱਖ, ਸਭ ਠੀਕ ਹੋਊ।', 'sabar rakkh, sabh theek hoo.'],
      ['ਈਰਖਾ', 'eerkha', 'noun', 'envy', 3, 'common', '😒',
       'ਈਰਖਾ ਬੰਦੇ ਨੂੰ ਖਾ ਜਾਂਦੀ ਹੈ।', 'eerkha bande nu khaa jaandi hai.'],
      ['ਮਾਣ', 'maan', 'noun', 'pride, honour', 2, 'common', '🎖️',
       'ਸਾਨੂੰ ਤੇਰੇ ਤੇ ਮਾਣ ਹੈ।', 'saanu tere te maan hai.'],
      ['ਲਾਡ', 'laad', 'noun', 'pampering affection', 2, 'common', '🤗',
       'ਨਿਆਣਿਆਂ ਨੂੰ ਬੜਾ ਲਾਡ ਕਰਦੀ ਹੈ।', 'niaaniaan nu barhaa laad kardi hai.'],
      ['ਤਰਸ', 'taras', 'noun', 'pity, compassion', 2, 'common', '🕊️',
       'ਮੈਨੂੰ ਉਹਦੇ ਤੇ ਤਰਸ ਆਇਆ।', 'mainu ohde te taras aaiaa.'],
      ['ਥਕੇਵਾਂ', 'thakevaan', 'noun', 'tiredness', 2, 'malwai', '😩',
       'ਸਾਰੇ ਦਿਨ ਦਾ ਥਕੇਵਾਂ ਲਹਿ ਗਿਆ।', 'saare din da thakevaan leh giaa.'],
      ['ਸੁੱਖ', 'sukkh', 'noun', 'ease, wellbeing', 2, 'common', '☮️',
       'ਰੱਬ ਸੁੱਖ ਰੱਖੇ।', 'rabb sukkh rakkhe.'],
      ['ਫ਼ਿਕਰ', 'fikar', 'noun', 'worry', 2, 'common', '😟',
       'ਫ਼ਿਕਰ ਨਾ ਕਰ।', 'fikar naa kar.'],
      ['ਹਿੰਮਤ', 'himmat', 'noun', 'grit, resolve', 2, 'common', '🔥',
       'ਹਿੰਮਤ ਕਰ, ਹੋ ਜਾਊ।', 'himmat kar, ho jaoo.'],
      ['ਨਿਮਰਤਾ', 'nimarta', 'noun', 'humility', 3, 'common', '🙏',
       'ਨਿਮਰਤਾ ਵੱਡੀ ਚੀਜ਼ ਹੈ।', 'nimarta vaddi cheez hai.'],
      ['ਗਿਲਾ', 'gila', 'noun', 'grievance, complaint', 3, 'common', '😤',
       'ਮੈਨੂੰ ਤੇਰੇ ਨਾਲ ਕੋਈ ਗਿਲਾ ਨਹੀਂ।', 'mainu tere naal koee gila naheen.'],
      ['ਧਰਵਾਸ', 'dharvaas', 'noun', 'consolation, reassurance', 3, 'majhi', '🫂',
       'ਉਹਨੇ ਮੈਨੂੰ ਧਰਵਾਸ ਦਿੱਤਾ।', 'ohne mainu dharvaas dittaa.'],
      ['ਅਸੀਸ', 'asees', 'noun', 'blessing', 2, 'common', '🙌',
       'ਵੱਡਿਆਂ ਦੀ ਅਸੀਸ ਲੈ।', 'vaddiaan di asees lai.'],
      ['ਰੌਣਕ', 'raunak', 'noun', 'liveliness, festive bustle', 2, 'common', '🎉',
       'ਵਿਆਹ ਵਾਲੇ ਘਰ ਰੌਣਕ ਹੈ।', 'viaah vaale ghar raunak hai.']
    ],

    /* ── ਸਮਾਂ · TIME ──────────────────────────────── */
    time: [
      ['ਸਵੇਰ', 'saver', 'noun', 'morning', 1, 'common', '🌅',
       'ਸਵੇਰੇ ਜਲਦੀ ਉੱਠੀਂ।', 'savere jaldi utthheen.'],
      ['ਦੁਪਹਿਰ', 'dupehar', 'noun', 'afternoon', 1, 'common', '🌞',
       'ਦੁਪਹਿਰ ਨੂੰ ਬੜੀ ਗਰਮੀ ਸੀ।', 'dupehar nu barhi garmi si.'],
      ['ਸ਼ਾਮ', 'shaam', 'noun', 'evening', 1, 'common', '🌇',
       'ਸ਼ਾਮ ਨੂੰ ਮਿਲਦੇ ਹਾਂ।', 'shaam nu milde haan.'],
      ['ਰਾਤ', 'raat', 'noun', 'night', 1, 'common', '🌃',
       'ਰਾਤ ਨੂੰ ਮੀਂਹ ਪਿਆ।', 'raat nu meenh piaa.'],
      ['ਅੱਜ', 'ajj', 'adv', 'today', 1, 'common', '📅',
       'ਅੱਜ ਛੁੱਟੀ ਹੈ।', 'ajj chhutti hai.'],
      ['ਕੱਲ੍ਹ', 'kallh', 'adv', 'yesterday; tomorrow', 1, 'common', '🗓️',
       'ਕੱਲ੍ਹ ਆਵਾਂਗਾ।', 'kallh aavaanga.'],
      ['ਪਰਸੋਂ', 'parson', 'adv', 'day before yesterday / after tomorrow', 2, 'common', '📆',
       'ਪਰਸੋਂ ਪਿੰਡ ਜਾਣਾ ਹੈ।', 'parson pind jaana hai.'],
      ['ਵੇਲ਼ਾ', 'vela', 'noun', 'time, occasion', 2, 'common', '⏰',
       'ਵੇਲ਼ਾ ਸਿਰ ਪਹੁੰਚ ਜਾਈਂ।', 'vela sir pahunch jaaeen.'],
      ['ਸਿਆਲ਼', 'siaal', 'noun', 'winter', 2, 'common', '🥶',
       'ਸਿਆਲ਼ ਬੜਾ ਕੜਾਕੇ ਦਾ ਹੈ।', 'siaal barhaa karhaake da hai.'],
      ['ਹੁਨਾਲ਼', 'hunaal', 'noun', 'summer', 3, 'malwai', '🥵',
       'ਹੁਨਾਲ਼ ਵਿੱਚ ਲੂ ਵਗਦੀ ਹੈ।', 'hunaal vich loo vagdi hai.'],
      ['ਬਰਸਾਤ', 'barsaat', 'noun', 'rainy season', 2, 'common', '🌧️',
       'ਬਰਸਾਤ ਸ਼ੁਰੂ ਹੋ ਗਈ।', 'barsaat shuroo ho gaee.'],
      ['ਸਾਲ', 'saal', 'noun', 'year', 1, 'common', '📅',
       'ਸਾਲ ਲੰਘ ਗਿਆ।', 'saal langh giaa.'],
      ['ਮਹੀਨਾ', 'maheena', 'noun', 'month', 1, 'common', '🗓️',
       'ਮਹੀਨਾ ਹੋ ਗਿਆ ਮਿਲਿਆਂ ਨੂੰ।', 'maheena ho giaa miliaan nu.'],
      ['ਹਫ਼ਤਾ', 'hafta', 'noun', 'week', 1, 'common', '📆',
       'ਅਗਲੇ ਹਫ਼ਤੇ ਆਵਾਂਗਾ।', 'agle hafte aavaanga.'],
      ['ਦਿਨ', 'din', 'noun', 'day', 1, 'common', '☀️',
       'ਦਿਨ ਚੜ੍ਹ ਗਿਆ।', 'din charrh giaa.'],
      ['ਘੜੀ', 'gharhi', 'noun', 'moment; watch', 2, 'common', '⌚',
       'ਦੋ ਘੜੀਆਂ ਬਹਿ ਜਾ।', 'do gharhiaan beh ja.'],
      ['ਤੜਕੇ', 'tarhke', 'adv', 'at dawn, very early', 3, 'malwai', '🌄',
       'ਤੜਕੇ ਉੱਠ ਕੇ ਖੇਤ ਗਿਆ।', 'tarhke utth ke khet giaa.'],
      ['ਲੌਢਾ ਵੇਲ਼ਾ', 'laudha vela', 'noun', 'late afternoon', 3, 'malwai', '🌅',
       'ਲੌਢੇ ਵੇਲ਼ੇ ਮੁੜ ਆਈਂ।', 'laudhe vele murh aaeen.'],
      ['ਡੂੰਘੀ ਰਾਤ', 'doonghi raat', 'noun', 'deep night', 3, 'common', '🌌',
       'ਡੂੰਘੀ ਰਾਤ ਤੱਕ ਗੱਲਾਂ ਕਰਦੇ ਰਹੇ।', 'doonghi raat takk gallaan karde rahe.'],
      ['ਹੁਣ', 'hun', 'adv', 'now', 1, 'common', '⏱️',
       'ਹੁਣ ਚੱਲੀਏ।', 'hun challiye.'],
      ['ਫੇਰ', 'pher', 'adv', 'then, again, later', 1, 'common', '🔁',
       'ਫੇਰ ਮਿਲਾਂਗੇ।', 'pher milaange.'],
      ['ਛੇਤੀ', 'chheti', 'adv', 'quickly, soon', 1, 'common', '⚡',
       'ਛੇਤੀ ਕਰ।', 'chheti kar.'],
      ['ਦੇਰ', 'der', 'noun', 'delay, lateness', 1, 'common', '🐢',
       'ਬੜੀ ਦੇਰ ਹੋ ਗਈ।', 'barhi der ho gaee.'],
      ['ਸਦਾ', 'sada', 'adv', 'always, forever', 2, 'common', '♾️',
       'ਸਦਾ ਖ਼ੁਸ਼ ਰਹੁ।', 'sada khush rahu.'],
      ['ਕਦੇ', 'kade', 'adv', 'ever, sometime', 1, 'common', '❓',
       'ਕਦੇ ਪਿੰਡ ਵੀ ਆ ਜਾਇਆ ਕਰ।', 'kade pind vi aa jaaiaa kar.'],
      ['ਪਹਿਲਾਂ', 'pehlaan', 'adv', 'before, earlier', 1, 'common', '⬅️',
       'ਪਹਿਲਾਂ ਰੋਟੀ ਖਾ ਲੈ।', 'pehlaan roti khaa lai.'],
      ['ਮਗਰੋਂ', 'magron', 'adv', 'afterwards', 2, 'malwai', '➡️',
       'ਮਗਰੋਂ ਗੱਲ ਕਰਾਂਗੇ।', 'magron gall karaange.']
    ]
  };

  /* ── Expand tuples into full records ─────────────── */
  var WORDS = [];
  Object.keys(RAW).forEach(function (category) {
    RAW[category].forEach(function (t, i) {
      WORDS.push({
        id: category + '-' + String(i + 1).padStart(3, '0'),
        gurmukhi: t[0],
        latin: t[1],
        pos: t[2],
        meaning: t[3],
        category: category,
        tier: t[4],
        dialect: t[5],
        emoji: t[6],
        example: { gurmukhi: t[7], latin: t[8] },
        status: 'verified',
        source: 'seed'
      });
    });
  });

  global.VOCAB = WORDS;
  global.VOCAB_CATEGORIES = CATEGORIES;
  global.VOCAB_DIALECTS = DIALECTS;
  global.VOCAB_TIERS = TIERS;

})(window);
